### ISSUE TITLE
"Show Document Symbols Tree" can't work with multiple variable declarations in a single line

### ISSUE THREAD

**Issue by DavidFeldhoff** [anzwdev/al-code-outline#102]
With the new release wave it is possible to declare multiple variables in one line. But the variables aren't shown in the Document Symbols Tree.
![image](https://user-images.githubusercontent.com/53570297/79184301-0b2a7900-7e14-11ea-8a3a-ac4f667686bb.png)

**Comment by anzwdev** [comment]
Thank you for reporting your issue. I've released a new version of the extension, you should see these variables in the symbols tree now.
