### ISSUE TITLE
Investigate possibility of implementing "extract method" code action

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#104]

**Comment by DavidFeldhoff** [comment]
Hi Andrzej, are you already developing on this one? I'm currently trying it as well. Maybe we could meet up and talk about the implementation ideas and decide afterwards what our next steps are. What do you think?

**Comment by anzwdev** [comment]
Hi. I haven't started any development, I just wanted to investigate what can be done and how much work is required. If you are also trying to do it, then I agree, it is a good idea to talk about it. I'll send you a message with my contact details.

**Comment by anzwdev** [comment]
Issue closed as functionality has been implemented by @DavidFeldhoff in his "AL Code Actions" extension available here: https://marketplace.visualstudio.com/items?itemName=davidfeldhoff.al-codeactions
