### ISSUE TITLE
AL Code Outline not working on MacOS

### ISSUE THREAD

**Issue by johbor** [anzwdev/al-code-outline#11]
The extension version 0.0.9 does not show the objects of the Microsoft_Application_13.0.24630.0.app when used on macOS Sierra 10.12.6 and VS Code Version 1.29.0

![screen shot 2018-11-14 at 22 24 33](https://user-images.githubusercontent.com/9353297/48514873-a1ddb980-e85f-11e8-9d0c-83ad759acdc2.png)

**Comment by elweilando** [comment]
It would be great if this works also in osx.

**Comment by anzwdev** [comment]
I've updated .net language server to use .net core and run on Mac. New version of the extension is available in the marketplace. I haven't tested in on macOS as I don't have Mac but I created separate dev version of the extension for Linux and it worked there.

**Comment by elweilando** [comment]
It works on macOS. Thank you!
