### ISSUE TITLE
Add multiple fields

### ISSUE THREAD

**Issue by antonyotto** [anzwdev/al-code-outline#114]
Since the last updated of VS Code , I cannot use Add multiple fields anymore. The action didn't appear in the editor. 

![image](https://user-images.githubusercontent.com/39110900/81355430-98ff3880-9122-11ea-9135-d1f787986d3b.png)

**Comment by rvanbekkum** [comment]
Other code-actions unfortunately don't seem to work either anymore 😯

**Comment by DavidFeldhoff** [comment]
That's not the VS Code update that broke the extension. It's the latest AL Language Extension Update (5.0.270354) that broke it. With version 5.0.254558 everything is fine, so if you need these functionalities, just install the older version of the al lanaguge ;)

**Comment by anzwdev** [comment]
New version of Microsoft AL Language extension contains updated compiler. I am looking at it now and trying to find what has changed.

**Comment by anzwdev** [comment]
I've found and fixed the problem. New version of the extension is available in the Visual Studio Marketplace.

**Comment by antonyotto** [comment]
awesome. thanks

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
