### ISSUE TITLE
Add Missing Application Area does not work for Page Extension

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#115]
Is it expected that the command for adding missing application Area does not work for Page Extensions?

To reproduce: 
I have created an page Extension for the `Sales Order Subform` and added a field to two actions, but anytime I start the command for adding application area I receive the following message:

![image](https://user-images.githubusercontent.com/56249171/81379776-faff7400-9109-11ea-87a7-188d25927dec.png)

**Comment by anzwdev** [comment]
It should work for both pages and page extensions. I'll check it and fix the problem.

**Comment by anzwdev** [comment]
Hi

I've retested this functionality and it works fine with my test files. My extension had a problem with loading syntax trees 1.5 week ago after Micrsoft updated their AL Extension, so maybe that was the reason why it was not working for you. I've released a new version last week, it should solve this issue. Does it work now or is it still broken on your side?

**Comment by anzwdev** [comment]
I am closing the issue as it seems to be working without any problems now.
