### ISSUE TITLE
New Table Wizard: missing length

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#117]
Witam Andrzej, when I enter this into the New Table Wizard:
![image](https://user-images.githubusercontent.com/34504100/82032181-2995c580-969b-11ea-94d8-a7c8ac379360.png)
then I get this:
![image](https://user-images.githubusercontent.com/34504100/82032308-4d590b80-969b-11ea-985c-43fa91ff72fc.png)

**Comment by anzwdev** [comment]
Czesc :) 
Thank you for letting me know about it. Looks like a bug, I'll fix it as soon as possible.

**Comment by anzwdev** [comment]
I've fixed the issue and uploaded new version of the extension to the Visual Studio Marketplace.

**Comment by NKarolak** [comment]
Confirmend; thank you :-)
