### ISSUE TITLE
AL Object Browser is blank

### ISSUE THREAD

**Issue by skkulla** [anzwdev/al-code-outline#118]
This feature used to work, but from last couple of weeks this shows blank screen. I am working on NAV 2018 version.

**Comment by anzwdev** [comment]
Some functions might not be working when you use Microsoft AL extension from Nav 2018, but AL Object Browser show be able to open app files and show list of objects. Are you opening it by right clicking on app file and selecting "Open in AL Object Browser" or are you using "Show All Project Symbols" or "Show Project Symbols without Dependencies" commands?

**Comment by skkulla** [comment]
By right clicking on app file

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anzwdev** [comment]
I've tested my extension with a few versions of Microsoft AL Extension from Nav 2018 and app symbols files downloaded from that version and it works without any problems. Maybe you are using runtime packages?

**Comment by skkulla** [comment]
It is working on my BC extension, but not on NAV 2018. Again it used to work earlier, this issue happening only from last few weeks

**Comment by skkulla** [comment]
Thank you
