### ISSUE TITLE
Suggestion: Show Type of Field/Var in Outline

### ISSUE THREAD

**Issue by KristofKlein** [anzwdev/al-code-outline#12]
Hi,

would be cool if the outline could show not only the name of a Field but also the Type (Text,Int, etc) 
If it is a big table that utilizes many of the properties it is hard to see if e.g. a Blob field is used. If Outline could jump in here for the rescue would be cool.

**Comment by anzwdev** [comment]
Extension is now starting it's own language server and parses currently opened file to display more symbols than the standard outline (i.e. function parameters, local variables), but it is not compiling whole solution to be able to access data types from other objects. For table fields, variables and parameters type is defined in the same file and can be included in outline node description. For page fields outline nodes descriptions are merged with symbols returned from Microsoft AL language server as it returns data type there.
