### ISSUE TITLE
New AL File Wizard: sort properties

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#121]
It would be great if the New AL File Wizard would immediately apply "sort properties" #93 

The current output without calling the function manually is looking like this now:
![image](https://user-images.githubusercontent.com/34504100/82185936-4d9b1600-98ea-11ea-9be3-f42c4f55de2e.png)

**Comment by anzwdev** [comment]
Good idea, I'll update the wizard

**Comment by anzwdev** [comment]
I've released a new version of the extension, it sorts properties in files created by all wizards now. Thank you for reporting this issue.

**Comment by NKarolak** [comment]
Confirmed, thank you :-)
