### ISSUE TITLE
codeActionsOnSave ignored

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#122]
According to https://github.com/anzwdev/al-code-outline/issues/93#issuecomment-613447434,  I am using the following folder settings:
```
  "editor.codeActionsOnSave": {
        "source.fixAll": true
    },
    "alOutline.codeActionsOnSave": [
        "SortProperties"
    ]
```
1. Immediately after having added "SortProperties" to the settings, the "sort properties" action is removed from all objects:
![image](https://user-images.githubusercontent.com/34504100/82188547-555cb980-98ee-11ea-8a44-3d63924052dc.png)
Is that actually intended?

2. [My main issue] My page had already sorted properties. I have now moved the Caption property to the very end, saved the object ... and nothing has been fixed.
What am I doing or understanding wrong?

**Comment by anzwdev** [comment]
Hi

Yes, when you add SortProperties to the "alOutline.codeActionsOnSave" setting, code action is reported to the Visual Studio with a different type. VS Code runs them on document save but no longer shows them in the code editor.

Your document should be fixed on save, if it does not work, then maybe I broke something with my latest changes. I'll check it.

**Comment by anzwdev** [comment]
I run a few tests and everything works for me. Does it work if you remove SortProperties from alOutline.codeActionsOnSave and ther run the command from the code actions menu? Can you see PropertyList node and all properties on the list of symbols inside the "AL Outline" panel?

**Comment by NKarolak** [comment]
Thanks for checking!

Running the function manually works fine.

AL Outline panel - I am not sure about the requested node.
Manual mode:
![image](https://user-images.githubusercontent.com/34504100/82290632-abd9fe80-99a7-11ea-8807-c6b3e2a2bd77.png)

Automatic mode:
![image](https://user-images.githubusercontent.com/34504100/82290545-7a613300-99a7-11ea-97ed-99fe28421fca.png)

**Comment by anzwdev** [comment]
Hi

I am sorry, I was busy today and I was not able to aswer faster. I was asking about properties node in the AL Code Outline panel when you have your AL file opened, but sorting properties work in manual mode for you so it is not important in this case.

My extension uses "alOutline.codeActionsOnSave" setting to decide which type of code action should be used when "Sort Properties" is reported to the VS Code. If this setting contains 'SortProperties' entry, then 'SourceFixAll' type will be used and the code action it won't be displayed on the lightbulb menu. Then visual studio code will use "editor.codeActionsOnSave" setting to decide if 'SourceFixAll' code actions should be run automatically during save.
Are you sure that you don't have
"editor.codeActionsOnSave": {
        "source.fixAll": false
    }
somewhere else in the settings (i.e. global settings, workspace settings)?

Could you also try to run 'Source Action' command from the visual studio command palette when the cursor is inside 'page' keyword? It should show lightbulb menu with 'SourceFixAll' actions and 'Sort Properties' should be there.

**Comment by NKarolak** [comment]
I've doublechecked, but "editor.codeActionsOnSave" is not used anywhere else.

When I call "Source action" while "editor.codeActionsOnSave" and "alOutline.codeActionsOnSave" are active, it does **not** display SourceFixAll, but only "Sort properties". When I click on "Sort properties", it does work.

When I comment out on or both settings, and "Source action" will return "No source actions available".

If you're interested, I could share my screen on Teams?

**Comment by anzwdev** [comment]
So all settings look good, "Sort properties" code action is created with correctly type, but vs code is not running it on save. How big is your file?

**Comment by NKarolak** [comment]
Very small, 4 KB.

**Comment by anzwdev** [comment]
I've just found an issue with this functionality when you use SaveAll and there are more than 1 file to save. I am going to fix it, maybe it will also fix your issue.

**Comment by anzwdev** [comment]
I've found a bug in the code, fixed it and released a new version of the extension. It should work now.

**Comment by NKarolak** [comment]
Confirmed, now it works. Thanks a lot!

Just out of curiosity; why did it work for you, but not for me?
