### ISSUE TITLE
Insert Paranatheses OnSave results in wrong parantheses

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#124]
I activated the feature to add automatically brackets on Save and now the brackets are inserted on the suspected and the direct following line.

**Comment by anzwdev** [comment]
I've released new version of the extension with some changes in this functionality. Could you check if it fixes your problem? If it still does not work, could you post here some example code that I can use to replicate the issue?

**Comment by pri-kise** [comment]
Yeah :) Works fine now.
