### ISSUE TITLE
"Add multiple fields": consider existing field group properties

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#128]
First of all, I love "Add multiple fields"! I already used it assuming it was a feature from the AL Language extension 🙈

However, there is one little glitch, when working with a page field group as shown here: https://github.com/anzwdev/al-code-outline/raw/master/resources/screen2-addfieldscodeaction.gif

When I create a new field group, I mostly immediately add the Caption property to it. 
"Add multiple fields" is available above the property only, and it will insert the fields above the properties only. It would be nice to have that fixed.

**Comment by anzwdev** [comment]
I've noticed it a few days ago and it is on my list of things to fix. When I created "add multiple fields" functionality, it was adding new fields below properties.

**Comment by anzwdev** [comment]
I've fixed the bug and released new version of the extension. Thank you for reporting it.

**Comment by NKarolak** [comment]
Confirmed, thank you :)
