### ISSUE TITLE
"AL Outline" panel is blank

### ISSUE THREAD

**Issue by B0uMe** [anzwdev/al-code-outline#131]
"AL Outline" panel is not showing details of selected object anymore (since more than 3 weeks).

**Comment by anzwdev** [comment]
Hi

Could you check if you are using the latest version (1.0.48) of my extension? Are you using Microsoft AL Extension from the Visual Studio Marketplace or from manually installed vsix file?

**Comment by B0uMe** [comment]
Hello,

Yes I am using the latest version (1.0.48) from the Visual Studio Marketplace.

**Comment by anzwdev** [comment]
Are you working with BC or Nav 2018?

**Comment by B0uMe** [comment]
I am working with Nav 2018

**Comment by B0uMe** [comment]
Hello,

The same problem came back.

**Comment by anzwdev** [comment]
I've released a new version of the extension which fixes this bug. Modifications that I was making in the background language server for the latest BC were breaking logic for Nav 2018 so I've decided to split the functionality and keep Nav 2018 logic separate. Thank you for reporting this problem.
