### ISSUE TITLE
Documentation comment does not add <returns> for named return value

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#133]
Hi @anzwdev,
I noticed that the documentation comment support does not add the `<returns>`-line if your procedure has a named return value.
Is this something you can fix?

![named_return_value_docs](https://user-images.githubusercontent.com/7383241/84640347-d90fc300-aef9-11ea-9467-de11abc7f2e6.gif)

**Comment by anzwdev** [comment]
I've released a new version of the extension, it fixes this issue.

**Comment by rvanbekkum** [comment]
Yes, it works now. Thanks! 👍
