### ISSUE TITLE
Sort Properties crashes document under specific circumstances

### ISSUE THREAD

**Issue by DavidFeldhoff** [anzwdev/al-code-outline#135]
In the most cases the sort properties works just fine, but if the document has some syntax issues then the command sometimes breaks the document. In this case it is when after the caption property the semicolon is missing.
https://1drv.ms/u/s!ApL7yYkbo0jQg5lVSS3qVUPznH6yww?e=ApjxhQ

**Comment by anzwdev** [comment]
Thank you for reporting it. It does not look good, I'll check what I can do.

**Comment by anzwdev** [comment]
I've released a new version of the extension. It no longer creates "sort" code actions if there are bugs inside code.

**Comment by DavidFeldhoff** [comment]
Thanks for that :)
