### ISSUE TITLE
Add Tooltips: caption instead of field name

### ISSUE THREAD

**Issue by LucVanDyck** [anzwdev/al-code-outline#140]
Can you use the caption of the fields in the tooltip instead of the field names? This to omit the pre- and suffixes in a field name.

**Comment by anzwdev** [comment]
Yes, I will add additional logic to extract field captions from table definitions.

**Comment by anzwdev** [comment]
I've released a new version of the extension that includes this functionality. It can only use table field captions from the same project as it is not possible to get them from *.app files. Thank you for reporting this issue.
