### ISSUE TITLE
Use ruleset editor for file with filename "ruleset.json"

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#143]
Hi @anzwdev,
I noticed you added a visual editor for AL-related JSON files:
> I've release a new version of the extension with app.json, rulesets (*.ruleset.json) and AppSourceCop.json custom editors. These editors are defined as "secondary" which means that developers have to right click on the file in the EXPLORER and choose "Open With..." option. It will display list of available editors for selected file. It is also possible to change default editor on this list.

For a project-specific ruleset file we typically, simply use the filename "ruleset.json".
Is it possible to make it work for files with that filename as well?

**Comment by anzwdev** [comment]
Yes, it can be done

**Comment by anzwdev** [comment]
I've added "ruleset.json" to valid file patterns for the ruleset editor. Modification has been included in the latest release of the extension. Thank you for your suggestion.
