### ISSUE TITLE
AppSourceCop.json Visual Editor: "unknown" property (for "publisher" property)

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#144]
Hi @anzwdev,
I noticed the AppSourceCop.json visual editor that you've added very recently shows an "unknown" property:
![unknown_AppSourceCopJSON](https://user-images.githubusercontent.com/7383241/85998627-57488b00-ba0b-11ea-9971-5546d943a732.png)
It seems like it should be the "publisher" property.

**Comment by anzwdev** [comment]
I've fixed it and released a new version of the extension. Thank you for reporting this problem.
