### ISSUE TITLE
Set the default object ID suggested by the symbols-based wizards to the next available object ID

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#147]
Hi @anzwdev,
It would be helpful if the symbols-based wizards would suggest the next available object ID for the object type (e.g., the "New Page Extension" command that can be invoked from the AL Object Browser).
I noticed that you already added this to AL File Wizards, which retrieve the next object ID with the following call:
```
let alLangProxy : ALLangServerProxy = new ALLangServerProxy();
let nextObjectId : string = await alLangProxy.getNextObjectId(<resourceURI>, <objectType>);
```
I think the resourceURI can be the URI of the workspace folder for which you opened the AL Object Browser.

I tried to make a change for this myself, but I was not able to build the project from the sources anymore.
I managed to get the `AZALDevToolsServer.NetCore` project to build and run, but as soon I try to open up the AL Object Browser in VSCode during a debug session, I am running into the following error:
![objectbrowser-exception](https://user-images.githubusercontent.com/7383241/86242515-2439ff00-bba5-11ea-87cf-2f4bb7e88901.png)
Do you maybe have some advice for me to get this working?

**Comment by anzwdev** [comment]
.net core version is used only for Mac, for Windows it loads netframework version of the language server.I decided to do it this way because netframework version is much smaller. When you build "AZALDevToolsServer.NetFramework" project from the solution, it should copy all required files automatically to the correct folders of al-code-outline project the same way as in the previous version.

**Comment by rvanbekkum** [comment]
Hi @anzwdev,
Thanks for the tip. I had some issues with getting the "AZALDevToolsServer.NetFramework" project to build: when building it, it could not find types from the "ALTools" namespace (Visual Studio did not report any errors though). After looking at the _warnings_ (instead of the errors) it turned out that it was an issue with the target framework which needed to be .NET Framework 4.8, which was because the DLLs (e.g., Microsoft.Dynamics.Nav.CodeAnalysis) that ship with the AL Language extension (which the "ALTools"/"ALTools.Server" project has a dependency on) were also built with 4.8.

**Comment by anzwdev** [comment]
I've released a new version of the extension, symbols based wizards use next available id for new objects.

**Comment by anzwdev** [comment]
I've just added a small fix and released new version of the extension. Previous change was not allowing users to change suggested object id.

**Comment by rvanbekkum** [comment]
Seems to work perfectly. Thanks!
I will close the issue.
