### ISSUE TITLE
SymbolsService does not load Symbols with AL Language version 3.x

### ISSUE THREAD

**Issue by DavidFeldhoff** [anzwdev/al-code-outline#152]
Hi Andrzej,

I got a request that with the version 3.x of the AL Language extension my extension isn't working. It's because the ALSymbolsService.loadDocumentSymbols does return an undefined rootSymbol.
![image](https://user-images.githubusercontent.com/53570297/87052700-5d0b5100-c201-11ea-9d01-195b004827c7.png)

The whole fullName says
_"Der Typ "Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableListDeclarationSyntax" in der Assembly "Microsoft.Dynamics.Nav.CodeAnalysis, Version=3.0.2.37806, Culture=neutral, PublicKeyToken=31bf3856ad364e35" konnte nicht geladen werden."_

Do you see a chance that this can be fixed?
The error is reproducable probably with any file, but it's tested with this one and the AL Language version 3.0.168874:
```
pageextension 50000 "sd" extends "Vendor List"
{
    layout
    {

    }

    actions
    {
    }
    trigger OnOpenPage()
    begin
        ontestsomething();
    end;
}
```

Best regards
David

**Comment by anzwdev** [comment]
Hi David

Thank you for reporting this bug. I'll fix it and include it in the next release of the extension.

**Comment by anzwdev** [comment]
I've released a new version of the extension that fixes this issue. It should work with all version of Microsoft AL Extension now, including the one from Nav 2018.

**Comment by DavidFeldhoff** [comment]
Thanks Andrzej :) Just tested it and it works. Thumbs up 👍
