### ISSUE TITLE
AL Page wizard: Previous button

### ISSUE THREAD

**Issue by LucVanDyck** [anzwdev/al-code-outline#155]
After adding fields to the fast tabs I used the Previous button to add an extra Fast tab. When pressing Next, all previous added fields were gone and I had to start over. Can the fields be preserved when using Previous/Next?

**Comment by anzwdev** [comment]
I've just released a new version of the extension with modification that solves this problem. Thank you for reporting it.

**Comment by LucVanDyck** [comment]
Awesome support. Thx!
