### ISSUE TITLE
Add "follow cursor" functionality to the AL Outline Panel

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#158]
~~Requested~~ **Suggested** by Natalie Karolak on Twitter.

**Comment by NKarolak** [comment]
Suggested, not requested ;-)

**Comment by anzwdev** [comment]
:)

**Comment by anzwdev** [comment]
I've released a new version of the extension with this functionality. Thank you for your suggestion.

**Comment by NKarolak** [comment]
It's working very well, thank you :)
