### ISSUE TITLE
All wizards: Pasted twice

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#159]
When using the object wizards, e.g. the "New Enum Wizard", values you paste into text fields (e.g. "Object Name") are always pasted twice.

Example: 
copy `test1,test2,test3`
Pasted value into field "Object Name": `test1,test2,test3test1,test2,test3`

**Comment by anzwdev** [comment]
I've tried it on a few different computers but I was not able to replicate it. Have you tried to replicate it on a different machine? How are you invoking paste? By Ctrl+V or Shift+Insert? Could you check if both these combinations work the same way? Are you always copying it from the same application?

**Comment by NKarolak** [comment]
I am not using VS Code on other machines, however my colleague could not reproduce it on his machine. I feared it would be somethin machine or environment specific ...

I am always pasting with Ctrl+V, but Shift+Insert does not make any difference.

The bug affects really only your wizard fields. Pasting anywhere else (also in other applications) behaves normally. Let me show you:
![image](https://user-images.githubusercontent.com/34504100/88140272-b441f600-cbf1-11ea-847d-82da7b12ab82.png)

**Inside VS Code, but outside the wizard:**
- ![image](https://user-images.githubusercontent.com/34504100/88140319-cae84d00-cbf1-11ea-8e6c-7cdd8bde7dc7.png)

- ![image](https://user-images.githubusercontent.com/34504100/88140344-db002c80-cbf1-11ea-9d77-fda5629c5757.png)

- ![image](https://user-images.githubusercontent.com/34504100/88140434-0551ea00-cbf2-11ea-8f21-6e6fc2aa2ce9.png)

**Outside VS Code**
- ![image](https://user-images.githubusercontent.com/34504100/88140501-2ca8b700-cbf2-11ea-8a9b-ea70e10a1808.png)

**Comment by NKarolak** [comment]
Resolved by updating VS Code to version 1.47.2.
