### ISSUE TITLE
extensionDependency on crs-al-language-extension?

### ISSUE THREAD

**Issue by waldo1001** [anzwdev/al-code-outline#16]
may be it's interesting to implement an extension-dependency on my extension?  

That way, you also get the prefixing in place, and people don't have to set the same (kind of) properties twice (like the filenamepatterns and such... ).  If not set exactly the same, this can cause conflicting scenarios...

Just a suggestion... :-)

**Comment by anzwdev** [comment]
It is a good suggesion :) It is always better to enter settings once.

**Comment by anzwdev** [comment]
Issue can be closed as extension dependency has been implemented and released.
