### ISSUE TITLE
Table Wizard: switch columns

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#160]
In the New Table Wizard, could the last two columns please be switched, so that "Data Type" is followed by "Length"?
That seems to be more intuitive, imo.

![image](https://user-images.githubusercontent.com/34504100/87932003-0e747700-ca8b-11ea-8490-cb344b7e0448.png)

**Comment by anzwdev** [comment]
I've released a new version that fixes this issue. Thank you for reporting it.

**Comment by NKarolak** [comment]
Confirmed. Thanks a lot jak zawsze :-)
