### ISSUE TITLE
Table Wizard: Mark PK fields

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#162]
Using the New Table Wiziard, it would be handy if we could mark primary key fields (e.g. with a new Boolean field column). 
The first field would get that mark automatically, whereas the other fields would need an update by the user.

**Comment by anzwdev** [comment]
That's a good idea, I'll add it.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it adds new boolean "PK" column to the table wizard. Thank you for posting this idea.

**Comment by NKarolak** [comment]
Works like a charm, dzięki! :-)
