### ISSUE TITLE
Rename or remove "Sort procedures" code-action at procedure-level

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#165]
Hi @anzwdev,
There are two ways to invoke the "Sort procedures" code-action: (1) at object-level (e.g., hovering over the first line of the object) and (2) at procedure-level (e.g., hovering over the first line of a specific procedure).
When the code-action is invoked at procedure-level, then what the command actually does is sort the procedures of the same type, e.g., when invoked from a local procedure it only sorts the local procedures together.
Would it be an idea to either rename the code-action ("Sort local procedures", "Sort global procedures", ...) or remove the code-action at procedure-level completely?

Here is an example where you can see the behaviour if you invoke the code-action from the second local procedure:
```
codeunit 50100 MyCodeunit
{
    local procedure LProcedure()
    var
        myInt: Integer;
    begin

    end;

    procedure GProcedure()
    var
        myInt: Integer;
    begin

    end;

    local procedure LProcedure2()
    var
        myInt: Integer;
    begin

    end;

    internal procedure IProcedure2()
    begin

    end;

    procedure GProcedure2()
    var
        myInt: Integer;
    begin

    end;
}

```

**Comment by anzwdev** [comment]
Changing procedure level code action name makes sense as it only sorts procedures of the same type but removing it seems to be a better option as I would expect that people want to sort everything, not just some of the procedures. I'll remove it.

**Comment by anzwdev** [comment]
I've decided to leave code actions at the procedure level but change the functionality to sort all procedures, so it works the same way as at the object level. I did it to make it consistent with other actions, i.e. "Sort report columns" on report column sorts all columns in the same dataitem.

**Comment by rvanbekkum** [comment]
Thanks for the update.

Unfortunately, I think the latest release broke something. The sorting is not working correctly anymore.
```pascal
    local procedure ABC100_MyProcedure()
    begin

    end;

    local procedure ABC40_MyProcedure()
    begin

    end;
```
The sorting functionality used to sort these with `localeCompare` with the result of 40 coming before 100.
Could you have a look at this? I can also file a new issue if that's easier for tracking.

**Comment by anzwdev** [comment]
I've fixed that and released a new version of the extension

**Comment by rvanbekkum** [comment]
Thanks! :)
