### ISSUE TITLE
Problem using multiple codeactions on save

### ISSUE THREAD

**Issue by ti-jalopez** [anzwdev/al-code-outline#170]
After upgrade a project using txt2al, I've tested our extension to fix order of variables, procedures and properties.
I've set CondeActionsOnSave to do all kings of sort at the same time:
...
    "editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.organizeImports": false
    },
    "alOutline.codeActionsOnSave": [
        "SortProperties", "SortProcedures", "SortReportColumns", "SortVariables"
    ]
...
After that, there are some errors using AL: package:
![20200804-ErrorAllCodeActionsOnSave](https://user-images.githubusercontent.com/68008246/89291746-613d5980-d65b-11ea-988c-d87832a934f7.png)

I've finally made it setting only one kind of sort object every time (first, SortVariable and save all objects, second SortProcedure and save all objects, etc..).

I think there is a problem when run multiple sort types on save, since individually it runs fine.

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I'll change my code actions implementation to return only one "onsave" codeaction that will contain all required changes for the document.

**Comment by anzwdev** [comment]
I've released a new version of the extension, all "onsave" code actions for a file create a single editor edit now. I hope that it solves the problem.

**Comment by ti-jalopez** [comment]
Hi @anzwdev,
I've tested de new version v.2.0.9, but when more than one option in setup it don't meke any change. My test configuration is:
    "editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.organizeImports": false
    },
    "alOutline.codeActionsOnSave": [
        // "SortProperties", "SortProcedures", "SortReportColumns", "SortVariables"
        // "SortProperties",
        // "SortProcedures" //Se producen errores, falla SortProcedures !! JAL 31/07/20
        // "SortReportColumns",
        // "SortVariables"
        "SortProcedures", "SortVariables"
    ]

If I test using only one option "SortProcedures" or "SortVariables", when save file runs fine.

Best regards,

**Comment by StefanMaron** [comment]
I sometimes encounter problems where the on save actions seem to merge two files/objects. It seems like the same ID different object types.

**Comment by anzwdev** [comment]
It does not look right. I have to review and maybe redesign a bit this functionality.

**Comment by ti-jalopez** [comment]
Hi anzwdev,

I'm testing a bit more, using settings at workspace level, and these are my results.

Settings which run ok sometimes (only SortProcedures or other settings excluding SortProcedures):

- "SortProperties", "SortVariables"

- "SortProperties", "SortVariables", "SortReportColumns"

- "SortProcedures"

Settings which doesn't do anythink (SortProcedures with others settings at the same time):

- "SortProperties", "SortVariables", "SortProcedures"

```
{
	"folders": [
		{
			"path": "bc160_costaapp"
		},
		{
			"path": "bc160_costaapp-test"
		}
	],
	"settings": {
		"formatFiles.extensionsToInclude": "al",
		"editor.codeActionsOnSave": {
			"source.fixAll": true,
			"source.organizeImports": false
		},
		"alOutline.codeActionsOnSave": [
			"SortProperties", "SortVariables", "SortReportColumns"
		]
	}
}
```

**Comment by anzwdev** [comment]
Hi ti-jalopez

Thank you for your tests. I can see where the problem is, I have to redesign this functionality to make it work.

**Comment by anzwdev** [comment]
Implementing these codeactions in typescript and on source code level was not a good idea. I've moved it to the .net background process for on save actions and my tests show that it works now. New version of the extension is available in the visual studio marketplace, you can check if it works for you.

**Comment by NKarolak** [comment]
So "SortVariables" is really supported on save? I'm asking because of the description:
![image](https://user-images.githubusercontent.com/34504100/93737284-0ba91600-fbe3-11ea-9377-8bafb25e673e.png)

**Comment by ti-jalopez** [comment]
Hi @anzwdev,
I do a first test with multiple codeactions onsave including SortProcedures, and it looks like.
I think a small changed is made in SortVariables, because if I do that in objects that I done in the past, the result is a bit different, although the coderule AA0021 Variable declarations should be ordered by type is not fired, so is ok but in different order.
![image](https://user-images.githubusercontent.com/68008246/93741449-bb36b600-fbec-11ea-85c2-12fda8d9a3a8.png)

**Comment by anzwdev** [comment]
Hi ti-jalopez

Sorry for that, I missed that one additional comparison when I was moving code from type script to c#. I'll release a new version of the extension in the morning.

**Comment by anzwdev** [comment]
Hi NKarolak

Yes, you can also sort variables on document save, I'll update setting description.

**Comment by ti-jalopez** [comment]
Hi @anzwdev,

SortVariables runs fine, just like before version 2.0.11. 

Thank you 👍
