### ISSUE TITLE
Extends property is empty for EnumExtension and TableExtension symbols

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#173]
Dear @anzwdev,
If you load the (document) symbols tree then the `extends` property appears to be empty for both "EnumExtension" and "TableExtension" object symbols, but for "PageExtension" object symbols it is filled as expected.
Is it possible to make a change so that the `extends` property is filled for all extension object symbols?

**Comment by anzwdev** [comment]
Hi Rob

I'll add it

**Comment by rvanbekkum** [comment]
Thanks! 😄

**Comment by anzwdev** [comment]
I've released a new version of the extension, "extends" property is populated for all all extension object types.
