### ISSUE TITLE
Add DataClassification to the Active Editor/Project

### ISSUE THREAD

**Issue by apoyas** [anzwdev/al-code-outline#176]
Hi @anzwdev 
Thanks for the amazing extension! Much appreciated.

Would it be possible to extend the functionality with commands to add DataClassification property to active editor/project, as you did it for ApplicationArea and ToolTips?
Thanks!

**Comment by anzwdev** [comment]
Hi

Thank you for your suggestion, I will add it.

**Comment by apoyas** [comment]
Hi @anzwdev
Thanks for the update. It's amazing!
The only issue I've found so far is that DataClassification property shouldn't be added to FlowFields and FlowFilters. In fact "the property 'DataClassification' can only be set if the property 'FieldClass' is set to 'Normal'".
Could you please look into it?
Many thanks.

**Comment by anzwdev** [comment]
Hi

I'm sorry, I forgot about that. New version of the extension is available in the visual studio marketplace.

**Comment by apoyas** [comment]
Hi @anzwdev
Thanks! It looks perfect now :)
