### ISSUE TITLE
New Report Missing

### ISSUE THREAD

**Issue by bdgjope** [anzwdev/al-code-outline#177]
Hi 
I don't know if I'm missing some setting or something. But there are a number of options missing from the new file wizard. Mine looks like this:
![image](https://user-images.githubusercontent.com/58292875/92610407-f1ed0200-f2b7-11ea-91d6-a7c3720d891a.png)

So e.g. Report and Enum is missing.
I'm using version 2.0.9 of the extension and 1.48.2 of Visual Studio Code.
What can be wrong?
Thanks

**Comment by anzwdev** [comment]
Hi

This list is scrollable and vs code shows only a few items if you have a small screen. Have you tried to scroll it down?

**Comment by bdgjope** [comment]
OK, i feel officially stupid. There plenty of room beneath the list but I still needed to scroll to find the missing Items. Thanks.
