### ISSUE TITLE
Suggestion: add action to Action Images page to display images in web client format

### ISSUE THREAD

**Issue by lvanvugt** [anzwdev/al-code-outline#178]
Still love you extension. Today only I learned about the _Action Images_ page (through AJ Kauffmann as I asked whether there was a BC version of his Image Library tool; he pointed me to your "follow up").

Like it, not in the least as it is a kind of intuitively the same as AJ's tool. But .... ;-) would it be possible to display the images like the web client displays them? Then it's more clear how it will show when the \user is going to (want to) select an action.

It would be great if there was a kind of mode to activate on the _Action Images_ page that would put a filter on the images.

**Comment by anzwdev** [comment]
Hi

My extensions does not store these images, they are collected dynamicaly from intellisense entries returned by the Microsoft AL Extension, so unfortunately I am not able to make them look the same as in the web client :(

![intellisense](https://user-images.githubusercontent.com/24944969/93133047-84cdd800-f6ce-11ea-8d03-e8602733c24b.png)

There is a filter text box and "Search" button at the top of the Action Images page, you can use them for filtering results. Do you want me to add another type of filter there?

![filteredimages](https://user-images.githubusercontent.com/24944969/93133043-84354180-f6ce-11ea-8759-f19768ca8aba.png)

**Comment by lvanvugt** [comment]
Andrzej, what I mean with "It would be great if there was a kind of mode to activate on the Action Images page that would put a filter on the images" is that the images themselves are filtered to they are shown as how they will be displayed on the web client, i.e. monochrome.

**Comment by rvanbekkum** [comment]
Oh, so like a dropdown, that let's you pick between 'Classic' and 'Monochrome' (or whatever we should call these two options)?

**Comment by lvanvugt** [comment]
Yes



Hartelijke groet/best regards

Luc van Vugt


-------- Oorspronkelijk bericht --------
Van: Rob van Bekkum <notifications@github.com>
Datum: 21-09-20 12:56 (GMT+01:00)
Aan: anzwdev/al-code-outline <al-code-outline@noreply.github.com>
Cc: Luc van Vugt <lvanvugt@live.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [anzwdev/al-code-outline] Suggestion: add action to Action Images page to display images in web client format (#178)


Oh, so like a dropdown, that lets you pick between 'Classic' and 'Monochrome' (or whatever we should call these two options)?

**Comment by anzwdev** [comment]
As I wrote above, unfortunately I am not able to do it. I am showing images returned by the AL compiler, but unfortunatley it contains old resources that are no longer used by the web client :(
