### ISSUE TITLE
"Run in WebClient" enhancements

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#18]
Hi @anzwdev,

I have some suggestions for improvements for the "Run in Web Client" command.
This commands prompts you only for the port number of your web client. After that it seems to take the server name of the _first_ configuration from your `launch.json` and build an URL from it to open.
However, for my case, the server name in the configuration is not the same as the web client base url, so this command won't generate the correct URL.
Also, I have multiple configurations in my `launch.json` file, but the "Run in Web Client" command always seems to just take the first configuration.

For this I have the following suggestions:
* Add a new property `alOutline.webClientBaseURL` to specify a web client base URL manually. If no setting is provided, the command will just default to the server name.
Maybe it would be good to allow a placeholder for the serverInstance name in this setting to support multiple configurations from the `launch.json` file? This will cover most cases, but not all of course (for that you would need to read the actual configurations).
* If there are multiple configurations in the `launch.json` file, then when running this command, first show a selection in the top to choose which configuration you want to use. (Just like what happens when you try to download symbols ("AL: Download Symbols") or publish ("AL: Publish") when you have multiple configurations)

If you have any further thoughts on the above, please let me know.

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

Thank you for your suggestion. You are right, support for multiple configurations and different web client URLs is a very good idea. The best option would be to allow user to select configuration and then get web client address from the development service, but I don't know how to do it. Maybe we could try to change startup object id in launch.json and then trigger standard "run" process? It will be slower than just opening web browser, but will compile and deploy all latest changes from the project. It might be a good idea to check the lates BC previews, maybe there is something that could help and it won't take long to wait for April release.

**Comment by rvanbekkum** [comment]
Maybe the [CRS Extension API from your pull request](https://github.com/CloudReadySoftware/crs-al-language-extension/pull/104) can be utilized here as well?
As you are planning to use this API for the object/file name generation, it might be an idea to also use the settings and functions for running objects from this API as well.

**Comment by anzwdev** [comment]
That was my original plan, it would allow you to specify web client base url in the workspace settings, but I don't think that it would solve your problem with multiple configurations. That's why I wanted to take a look at bc preview first.

**Comment by anzwdev** [comment]
April release of BC allows to start debugger without building and deploying AL code. I can check version of the active Microsoft AL extension and if it is 3.0, then I can start debugger session without deployment. If older version of AL extension is active, I would run current code to open web browser. Obviously I would show configuration selection in both cases.

**Comment by anzwdev** [comment]
Extension has been updated. If April (or newer) release of Microsoft AL extension is active, developer will be asked to select configuration and then debugger will start showing selected object without deploying al code. If older version of Microsoft AL extension is active, old code running objects will be used.

**Comment by rvanbekkum** [comment]
Just tested this again with BC14 CU02, where they also _finally_ fixed the issue where you could not have multiple launch configurations.
Seems to work great, so I think you can close this issue.

**Comment by anzwdev** [comment]
That's great, thank you for testing it.
