### ISSUE TITLE
New AL File Wizard: Keep line ending settings (CRLF vs. LF)

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#184]
Hi Andrzej,

my default "End of Line Sequence" in VS Code is CRLF:
![image](https://user-images.githubusercontent.com/34504100/94526801-5c99b980-0236-11eb-8b0c-95ddfe8a1b62.png)

When I use the New AL File Wizard, it is instantly switched to LF. This has a very mysterious side effect on my development: 
https://github.com/microsoft/AL/issues/6170

Is it somehow possible to automatically create the new file with the user's default end of line sequence? Just in case, there are some other AL "goodies" waiting for us ;-)

**Comment by anzwdev** [comment]
Hi Natalie

I'll fix it

**Comment by NKarolak** [comment]
Working in v 2.0.17, thank you :-)
