### ISSUE TITLE
"Remove 'with' usage" adds redundant names of Rec *and* other vars to field names

### ISSUE THREAD

**Issue by dtkb** [anzwdev/al-code-outline#186]
The action prepends pointless `Rec.` or other record variable name qualifiers to field names in methods that are already specifying the `Rec.`, and so in which the field must come from that record and don't require qualification - which makes code and `git diff` noisier for no reason.

![image](https://user-images.githubusercontent.com/63455896/95186089-7cdef080-07c1-11eb-9f58-c1cb3a0c134b.png)

As shown, this happens both with `Rec.` (i.e. implicit `with`) and *also* with other records, which are equally unambiguous, and which weren't using `with` at all, in the first place!

Thus, what would be a great feature actually becomes unusable, because the work of correcting false qualifiers counterbalances the time saved from whatever legit things it does.

I see as in the following link that similar/same is also reported at Microsoft/AL, so maybe the extension just runs their commands and inherits their problems ;-)

**Comment by anzwdev** [comment]
I missed this issue during my tests, because converted code compiles without any problem, but I agree, it looks better without Rec/variable name.
I've modified my code, it seems to be working, I will release a new version of the extension tomorrow.

**Comment by anzwdev** [comment]
I've fixed the problem and released a new version of the extension

**Comment by dtkb** [comment]
Thanks! I can't see the code change here, but I got the new extension thru VS Code and it seems fixed - e.g. it does Rec.CalcFields("Installments Total") instead of formerly Rec.CalcFields(Rec."Installments Total"). So looks good to me :-)
