### ISSUE TITLE
API pages naming and no translation

### ISSUE THREAD

**Issue by jwikman** [anzwdev/al-code-outline#187]
According to the docs (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-api-pagetype) all attributes (fields) in  API page should use camelCase. 
When using the "New AL File Wizard" command and you select to create a API page, the fields and captions are named with PascalCase, not camelCase.

Please use camelCase for field names and captions if the PageType is API, otherwise it should remain as PascalCase.
Please also add Locked=True to the captions in API page, since we do not have any benefits of translating API pages.

Make the two requests above configurable if you do not want to change the current behavior for all old users.

**Comment by anzwdev** [comment]
Thank you for reporting it, I'll do it

**Comment by anzwdev** [comment]
I've released a new version of the extension with this modification.

**Comment by jwikman** [comment]
Thanks @anzwdev !

But I found one issue: Numbers should be allowed in field names and captions
Now I get this:
```
                field(globalDimensionCode; Rec."Global Dimension 1 Code")
                {
                    ApplicationArea = All;
                    Caption = 'globalDimensionCode', Locked = true;
                }
```
But it should be this:
```
                field(globalDimension1Code; Rec."Global Dimension 1 Code")
                {
                    ApplicationArea = All;
                    Caption = 'globalDimension1Code', Locked = true;
                }

```
Other than that it looks great!

**Comment by jwikman** [comment]
@anzwdev - Do you want the last comment as a new issue for better tracking?

**Comment by anzwdev** [comment]
@jwikman - You can leave the comment here, I will fix it as part of this issue

**Comment by anzwdev** [comment]
I've fixed the issue and released a new version of the extension.

**Comment by jwikman** [comment]
Beautiful!

**Comment by jwikman** [comment]
@anzwdev I just noticed that the field naming of "Bill-to Address" becomes "billtoAddress" and not "billToAddress" as expected. I cannot find any good docs on that, but other tools would have ended up with "billToAddress" :)

**Comment by jwikman** [comment]
As a suggestion, use the camelCase function from [lodash](https://www.npmjs.com/package/lodash) - Then you do not need to implement your own camelCase logic.
