### ISSUE TITLE
Formatting result after using "Remove 'with' usage"

### ISSUE THREAD

**Issue by bvbeek** [anzwdev/al-code-outline#188]
Hi,

Nice that there is a function for updating this!
Please can you take a look at this?
We got 4000+ files so manually saving to format this is not an option ;)

Current output:
![image](https://user-images.githubusercontent.com/28626283/95554071-dc324000-0a0f-11eb-8106-a5be0e931827.png)

Expected output:
![image](https://user-images.githubusercontent.com/28626283/95554261-2fa48e00-0a10-11eb-8ea0-ec8dddf1aca0.png)

This is not working:
![image](https://user-images.githubusercontent.com/28626283/95555281-d0e01400-0a11-11eb-8750-903e409ddc1c.png)

**Comment by dtkb** [comment]
I found the same thing.

> We got 4000+ files so manually saving to format this is not an option ;)

I searched, and in the meantime you can use the VS Code extension Format Files to do all files in Workspace:

![image](https://user-images.githubusercontent.com/63455896/95735222-74ccf800-0c7c-11eb-8edd-aadb7be749de.png)

![image](https://user-images.githubusercontent.com/63455896/95735269-81515080-0c7c-11eb-8b8f-266b5c31f036.png)

It has to simulate the user opening/saving all files, so it's slightly slower for that, but it seemed to work well and fast enough on my current ~250 file project.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it formats documents at the end of processing now.
