### ISSUE TITLE
Add multiple fields - sort by field id

### ISSUE THREAD

**Issue by theschitz** [anzwdev/al-code-outline#190]
When using the code action **Add multiple fields** it would be helpful to have the fields added ordered by field id. Would that be possible? The way I create and think of tables is often in field order which is by field id order, at least in the first iteration. 

I took a look in your elegant solution in an effort trying to achieve a PR but I had some problems debugging it. If I find the time I might give it another try. Depending on the response on this issue ofc ;)

Thank you for a great and very helpful extension!

**Comment by anzwdev** [comment]
Hi

I am afraid that it cannot be done with the current solution. Add multiple fields functionality gets list of fields from the Microsoft AL language server and that list does not contain field ids.

**Comment by theschitz** [comment]
I suspected as much :disappointed: Maybe in the future!
