### ISSUE TITLE
"Remove 'with' usage" still prepends redundant record names to 2nd/3rd/later fields

### ISSUE THREAD

**Issue by dtkb** [anzwdev/al-code-outline#191]
As a follow-up to #186, bugs remain: we still get unnecessary record variable names prepended to fields other than the 1st, in statements such as `SetAutoCalcFields()` and `SetCurrentKey()`, where a rec name is unnecessary as we can only possibly be referring to its own fields. Also, it differs between commands which fields get that prepended: both work correctly for the first field or 2 respectively, but then resume prepending the record variable name for subsequent fields. So it seems some iteration or something is wrong.

Please fix, so that no such commands prepend a redundant rec var name, to any fields in a method call that can _only_ be members of that table - 1st or 2nd or 3rd or any other :-)

e.g. before:

![image](https://user-images.githubusercontent.com/63455896/95735766-2e2bcd80-0c7d-11eb-97c4-e7fe55950494.png)

after (includes formatting bug from #188):

![image](https://user-images.githubusercontent.com/63455896/95735863-53204080-0c7d-11eb-9dd0-1f745eb11547.png)

expected is of course:

![image](https://user-images.githubusercontent.com/63455896/95735921-67643d80-0c7d-11eb-86cd-bc20a60342d8.png)

**Comment by anzwdev** [comment]
Thank you for reporting the issue. The problem was caused by incorrect handling of optional parameters in my code. I've fixed it and will release a new version of the extension tomorrow morning.

**Comment by dtkb** [comment]
Looks great now, thanks a lot!
