### ISSUE TITLE
Bug found: The identifier x could not be found

### ISSUE THREAD

**Issue by bvbeek** [anzwdev/al-code-outline#192]
Hi,

Found a small bug (maybe it's a Microsoft issue).

On open page I get this error:
![image](https://user-images.githubusercontent.com/28626283/95976490-e0979800-0e17-11eb-8388-396df18f326e.png)

After changing this, it's solved:
![image](https://user-images.githubusercontent.com/28626283/95976456-d1b0e580-0e17-11eb-9641-dbf133222478.png)

Now warnings came up after the change, I think it should not be  modified in properties.

**Comment by anzwdev** [comment]
Hi

Which version of Business Central are you using? Not all properties support "Rec." in versions earlier than BC 17.

**Comment by anzwdev** [comment]
Hi @bvbeek

The problems looks like a result of running "Remowe 'with'" command on AL code for BC version older than BC 17. It does not work with these old versions as they don't support removing implicit WITH from some of the fields and actions properties.

I haven' received any response from you so I am closing the issue. If you have any questions or comments, please add them here, we can always reopen it.
