### ISSUE TITLE
Wizard for Custom Object

### ISSUE THREAD

**Issue by 19sam88** [anzwdev/al-code-outline#196]
Hi, 
it's possible to view in Object Browser the custom objects created with the wizard, in order to complete them?

thanks,
best regards

Samuele

**Comment by anzwdev** [comment]
Hi

You can use "AZ AL Dev Tools: Show Project Symbols without Dependencies" or "AZ AL Dev Tools: Show All Project Symbols" to open AL Object Browser with list of objects from the current project.
