### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#197]
I've a AL project with 4500+ files and got 51k+ 'implicit with' warnings.

When running 'Remove with usage from the active project', approx. 800 files got fixed, getting the warnings down to 37K+ (Great!). However, after a certain time, I receive the error "Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index".

Any chance of fixing this, since I don't want to open each file separatly? 
I cannot treat the files by folder / in smaller groups.

**Comment by anzwdev** [comment]
Thank you for reporting the problem. There was an issue which was causing the crash when al file contained WITH statement with begin..end block without any statements inside. I've released a new version of the extension with the fix, could you check if it works for you now?

**Comment by fvet** [comment]
Thanks for the quick fix, all files have been processed without further problems. Your extension saved me quite some hours of work!!
