### ISSUE TITLE
AZALDevToolsServer.NetCore is not unloading after VS-Code is closed

### ISSUE THREAD

**Issue by sauerkreut** [anzwdev/al-code-outline#198]
Hi,
the AZALDevToolsServer.NetCore us not properly unloaded after VS-Code is closed.
It's not a big issue but it's annoying the kick the tasks all the time.
Kind regards
Walter
<img width="558" alt="Screenshot 2020-11-24 at 13 56 59" src="https://user-images.githubusercontent.com/43308169/100059373-8ef21c80-2e5d-11eb-989f-990d678f73a0.png">

**Comment by sauerkreut** [comment]
Is there any movement on this issue or do I have to live with it?
I am not restarting my machine often. So after a moth AZALDevToolsServer is consuming a lot of memory and it's really annoying closing all the tasks manually.
If it helps, I am on macOS Mojave 10.14.6 (18G8022)

**Comment by anzwdev** [comment]
Hi

My main problem is that I don't have a Mac, so I am not able to test and debug it. That's why I was keeping this issue open but unfortunately with a low priority. I've just reviewed code carefully again and found one place where one line of code was missing. I've fixed it and released a new version of the extension but I don't know if it will fix your problem. Please check it and let me know if anything has changed.

**Comment by sauerkreut** [comment]
Hi Andrzej,

thank you for having a look into it. This morning it looked like this:

I installed v3.0.10, closed VS-Code and killed all the processes.
After restarting VS-Code and close it again after a few minutes, the process is available.

As said, thank you for your effort. 
Other installed VS-Code extensions might conflict wit your extension. But your extension is more valuable for me than the memory consumed. I just have to kill the processes on a weekly base.

Kind regards
Walter

**Comment by anzwdev** [comment]
Hi Walter

I've released another version of the extension with another small fix to this area. Could you check if it now unloads AZALDevToolsServer on your machine?

Andrzej

**Comment by sauerkreut** [comment]
Hi Andrzej,
after working with the new version for a few weeks now, it seems the AZALDevToolsServer.NetCore is properly unloaded after closing VS-Code. Thank you for the effort you put into the tool. Great work.
Kind regards
Walter
