### ISSUE TITLE
Effects of implicit With removal

### ISSUE THREAD

**Issue by gunnargestsson** [anzwdev/al-code-outline#199]
Hi,

Now fields in pages and reports need to have Rec. prefix.
This also requires a caption to be added to the field properties.

The command Add Field Captions seem to only work on table objects, not on page objects.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting the issue, I'll take a look at it.

**Comment by anzwdev** [comment]
Are you sure that it is broken? I've run a few tests in BC 15, BC 17.1 and BC 17.2 with page fields based on "Rec.FieldName" expressions and captions defined at the table level are properly displayed in all these versions of Business Central.

**Comment by gunnargestsson** [comment]
Is it not just the field control name that is displayed?  What happens if you change that?  Still getting caption from Rec.FieldCaption ?

**Comment by anzwdev** [comment]
No, it displays value of the caption property from the table field.

**Comment by gunnargestsson** [comment]
Then, adding a caption to all fields in the base app has no meaning I guess.

Kveðja/Kind regards,
Gunnar Þór Gestsson
________________________________

**Comment by anzwdev** [comment]
Remember that ToolTip property is available on pages only so some people may prefer to populate both captions and tooltips together on pages.

**Comment by anzwdev** [comment]
I've released a new version of the extension with 2 new commands: "Add Page Controls Captions to the Active Editor" and "Add Page Controls Captions to the Active Project"
