### ISSUE TITLE
Bug: "null" at the top of the AL Object Browser

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#20]
Dear @anzwdev,

A few days ago I started noticing that now a string appears with the text `null` at the top of the AL Object Browser, see the screenshot below:

![image](https://user-images.githubusercontent.com/7383241/53686237-de58f680-3d24-11e9-9126-6d1a6b74f0de.png)

I am pretty sure this wasn't here before, so it is probably due to an upgrade of either VSCode or the AL Language extension that this now pops up.

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

Thank you for reporting this issue. It is vs code bug, it has been fixed in insiders version of vs code a few days ago.

https://github.com/Microsoft/vscode/issues/68953

**Comment by rvanbekkum** [comment]
Good to know it has already been addressed. This should resolve itself then with a future update of VSCode. For now I will leave the issue open, which might be useful for tracking.

Thanks for your reply!

**Comment by rvanbekkum** [comment]
Seems to be fixed in the latest VSCode releases (>=1.32.1).
