### ISSUE TITLE
Suggestion for Table/Table Extension Wizard

### ISSUE THREAD

**Issue by mjmatthiesen** [anzwdev/al-code-outline#200]
Would be great if fields were autonumbered:
For tables, start at 1, increase with each line.
For extensions, start at the first id of the project range, increase with each line.

Hope that makes sense. It's not much, but a small qol.

Thanks for the extension

**Comment by anzwdev** [comment]
I've released a new version of the extension, it contains functionality that you've suggested. Thank you for posting your request.

**Comment by mjmatthiesen** [comment]
Works great. Thanks!
