### ISSUE TITLE
New File Wizard: Format new file name

### ISSUE THREAD

**Issue by FabianBigler** [anzwdev/al-code-outline#201]
Whenever I create a file it does not meet our guidelines so I have to manually change it after.
For example: I want to create a new file for codeunit "ItemGenerator" with id 71012.
The created file name is "Cod71012.ItemGenerator.al". However, in our guidelines it should be "ItemGenerator.al".

Could you provide a setting for this, so we can set the format of the created file? E.g. default is [ObjectId].[ObjectName].al. Then in our case we could just change that value to "[ObjectName].al".

That would be supercool!
Thank you!
Kind Regards

**Comment by anzwdev** [comment]
My extension uses api exposed by Waldo's CRS AL Language extension to generate file names. If you want to change file name template, you can do it by changing "CRS.FileNamePattern" and "CRS.FileNamePatternExtensions" vs code settings. You can find more information in the "Extension Settings" section here:
https://marketplace.visualstudio.com/items?itemName=waldo.crs-al-language-extension
