### ISSUE TITLE
AA0137 - "Unused variable" fixes can break code.

### ISSUE THREAD

**Issue by rdebath** [anzwdev/al-code-outline#204]
AA0137 describes a Return variable as "unused" and your auto fix damages code. 

If I try to apply the auto fix both the name and the type are deleted creating broken code as in Sample 2.

This also breaks function parameter list if one is removed and does not make any attempt to fix calls (for example remove the calling argument if it's "simple"; ie not a function call)  

**Code sample 1**
``` pascal
    local procedure SHA1(InText: Text) HexHash: Text[40]
    var
        EncryptionManagement: Codeunit "Cryptography Management";
    begin
        exit(EncryptionManagement.GenerateHash(InText, 1));
    end;
```

**Code sample 2**
``` pascal
    local procedure SHA1(InText: Text)     var
        EncryptionManagement: Codeunit "Cryptography Management";
    begin
        exit(EncryptionManagement.GenerateHash(InText, 1));
    end;
```

PS: I [mis-identified](https://github.com/microsoft/AL/issues/6252)  where this came from, is there some way of saying "AZ-Tools suggests this fix" ?

**Comment by anzwdev** [comment]
Thank you for reporting the issue, I'll take a look at it.
I will also modify all my code actions to include "AZ Tools" in the code action name.

**Comment by anzwdev** [comment]
I've just found out that something went wrong and my previous extension upload to the vs marketplace failed. I've released a new verison of the extension which contains fix to your issue. Everything should work now. I'm sorry for not checking it earlier :(
