### ISSUE TITLE
Field list in order of fieldnumber

### ISSUE THREAD

**Issue by waldo1001** [anzwdev/al-code-outline#205]
Hi,

if possible, it would be very helpful to have all fields in the wizards in the order of fieldnumber:

![image](https://user-images.githubusercontent.com/12088142/103951826-a6e8db80-513f-11eb-9682-f4657edfe33b.png)

**Comment by anzwdev** [comment]
Unfortunately I don't have this information. I am using vs code intellisense api to get list of fields from AL compiler and it does not contain field ids.

**Comment by waldo1001** [comment]
No prob - there are worse things ;)

**Comment by waldo1001** [comment]
Cool!

**Comment by anzwdev** [comment]
I've redesigned big part of the core of the extension to get more information about al symbols and as a result it is now possible to sort fields by name and id in the wizards and in 'Add multiple fields' commands. There are "Sort by" buttons on the wizard pages and 2 small sort buttons on the top right side of the field selector displayed by 'Add multiple fields' command.

![image](https://user-images.githubusercontent.com/24944969/113434711-606eea00-93d9-11eb-8eba-23fc06133525.png)

![image](https://user-images.githubusercontent.com/24944969/113434595-2867a700-93d9-11eb-8f47-58a789b1675e.png)
