### ISSUE TITLE
ApplicationArea on a page object

### ISSUE THREAD

**Issue by gunnargestsson** [anzwdev/al-code-outline#207]
I used the action to add ApplicationArea to a page object.
The page had UsageCategory = None;
Still ApplicationArea was added to the page properties and caused an error.

**Comment by anzwdev** [comment]
I've just found out that something went wrong and my previous extension upload to the vs marketplace failed. I've released a new verison of the extension which contains fix to your issue. Everything should work now. I'm sorry for not checking it earlier :(
