### ISSUE TITLE
Selecting the last row in the AL Object Browser (List View) changes the row to a different object

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#211]
Hi @anzwdev,
For the AL Object Browser in the List View a weird bug appears if you set filters on the Object Name and then select the last row. Seems like the Object Changes to the object in the same row no. as in the unfiltered list.
Please see the GIF below:
![j09cHF891A](https://user-images.githubusercontent.com/7383241/107750409-47708380-6d1c-11eb-8edf-e23cd35cb6b2.gif)

**Comment by anzwdev** [comment]
Thank you for reporting this problem. I've fixed it and released a new version of the extension.
