### ISSUE TITLE
AL Object Browser does't work in a DevOps clone repository

### ISSUE THREAD

**Issue by 19sam88** [anzwdev/al-code-outline#216]
Hello!
if a try to use the "AL Object Browser" for Extensions stored in a local clone of DevOps repository I can't see the objects.

![image](https://user-images.githubusercontent.com/33227729/110139096-f4499800-7dd2-11eb-89d9-b63beab0248b.png)

the properties of the repository are like the image below.

![image](https://user-images.githubusercontent.com/33227729/110139724-a1bcab80-7dd3-11eb-9ee7-59c408b1811c.png)

**Comment by anzwdev** [comment]
I have redesigned core of my extension in version 3.0.0. Do you still have this issue?

**Comment by 19sam88** [comment]
Hello,
no I don’t have it anymore.



Samuele Galliani | Info Studi srl | www.infostudi.it<http://www.infostudi.it/> | +39 02 610.341.63
Follow us on Facebook<https://www.facebook.com/infostudi> and LinkedIn<https://www.linkedin.com/company/infostudi>
