### ISSUE TITLE
On new object: Take next free object id in object range

### ISSUE THREAD

**Issue by dannoe** [anzwdev/al-code-outline#217]
Would be cool if the object ID field in the wizard could be prefilled with the next unused object id.

If there are multiple ``idRanges`` in the app.json there could be a selection.

**Comment by anzwdev** [comment]
Which wizard are you using? Visual wizards are using vs code intellisense internally to suggest the same next object id that is suggested by Microsoft AL Extension when you are typing a new object in the code editor.

**Comment by dannoe** [comment]
Oops. I think my VS code was bugged at that the time. It actually works as intended. Sorry.
