### ISSUE TITLE
Can the prefix/postfix be removed when adding Captions or ToolTips?

### ISSUE THREAD

**Issue by DanielGoehler** [anzwdev/al-code-outline#218]
Is there any way to have the **mandatoryPrefix** or **mandatorySuffix** in **AppSourceCop.json** removed for the "Add Table Field Captions to the Active Project", "Add Page Controls Captions to the Active Project" and "Add ToolTips to the Active Project" actions?

**Comment by anzwdev** [comment]
It cannot be done at this moment, but I am in the middle of doing modifications to this functionality to support more scenarios so I will include your request on my list of changes.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it now removes prefixes and suffixes defined in mandatoryPrefix, mandatorySuffix and mandatoryAffixes settings in the AppSourceCop.json file.

**Comment by DanielGoehler** [comment]
I did not get this to work with v3.0. Is there something I miss? 
<img width="1920" alt="Screenshot" src="https://user-images.githubusercontent.com/9556549/114095567-db467200-98bd-11eb-8dfc-158b5f25bd9e.png">

**Comment by DavidFeldhoff** [comment]
Could it be that it's another issue that it has issues with table extensions? I think I noticed something similar that it does not get the captions of the fields of the table extension. I could double check it later today

**Comment by DanielGoehler** [comment]
Table Fields doesn't get prefixes or postfixes. Table Extensions are the only case for this.

**Comment by anzwdev** [comment]
I've fixed a small bug in the new logic detecting table fields and released new version of the extension. Could you check if you still have this issue?

**Comment by DanielGoehler** [comment]
Perfect. Thank you!
