### ISSUE TITLE
Display test functions differently in outline

### ISSUE THREAD

**Issue by lvanvugt** [anzwdev/al-code-outline#22]
Hey Andrzej,

Still loving your VSCode extension!

Now working on a lot of testing I wonder if you could add an attribute to functions that it is clearly visible it is not a normal funtion, but a test function or a UI handler.
In the folliwng screenshot the first three function are test functions. I know but can not see it straight form the outline. Would be great that I would instantly see what and how test functions there are. And what a handler functions is (being the last one in the listed functions on the screen shot).

I recon you get that the title of the issue is to strict.

![afbeelding](https://user-images.githubusercontent.com/18466198/54259477-20c0d580-4566-11e9-8bdd-53ed60ad37c1.png)

**Comment by anzwdev** [comment]
Hi Luc

It is nice to know that you like it, thank you. 

AL Outline does not parse source code, it displays list of document symbols returned from the AL language server. It tries to extract some additional information from these symbols, but there is not much that can be detected. Your request is not the first one when somebody asks for some additional information to be displayed, so I will check, if there is anything that can be done without creating something that could decrease performance of vs code.

**Comment by lvanvugt** [comment]
Clear and thanx.

**Comment by anzwdev** [comment]
I made a few .net experiments and it seems that it can be done. It looks like very interesting challenge, so I will try to do it, but because I would like to use c#, it will work on windows only.

**Comment by lvanvugt** [comment]
> ... it will work on windows only.
 Great and now problem for me.

**Comment by anzwdev** [comment]
I am still working on it, here is small example how it will look like:

![MethodIcons](https://user-images.githubusercontent.com/24944969/55690362-89924680-5988-11e9-8112-a64da23ce5ce.png)

**Comment by lvanvugt** [comment]
Wow, looking great.

**Comment by anzwdev** [comment]
I've finished the development and published it in the new version of the extension.

**Comment by lvanvugt** [comment]
Great, when will it be availble? It's not telling my VSCode there is a new version available.

**Comment by anzwdev** [comment]
I've published it yesterday, but I found that language server executable was compiled against .net framework 4.7.2, which might not be installed on many machines. I've just recompiled it against .net framework 4.7 and republished the extension. It should update automatically.

**Comment by lvanvugt** [comment]
Indeed updated, but it is not showing anything now.

**Comment by lvanvugt** [comment]
![afbeelding](https://user-images.githubusercontent.com/18466198/56277996-b0c5e200-6105-11e9-9633-6ed154680458.png)

**Comment by anzwdev** [comment]
Could you check if it has updated to version 1.0.1? Version 1.0.0 was using .net framework 4.7.2 and 1.0.1 uses 4.7. There is also an issue which I am going to fix later today - it does not loads symbols of currently opened file when you start visual studio code. You have to click on "refresh" or switch to another document and then go back. It should be easy to fix - the code that loads symbols from active document when extension is initialized is missing. First load after new project is opened might also take a bit more time because it waits for Microsoft AL Extension to finish parsing all files, but if standard outline shows symbols, AL Outline should show them too.

**Comment by anzwdev** [comment]
Do you have multiple versions of Microsoft AL Extension installed in your visual studio code?

**Comment by lvanvugt** [comment]
Yes/No, NAV 2018 AL extension Enabled, BC AL extension Disabled.

**Comment by lvanvugt** [comment]
Uninstalled BC extnsion (so only NAV 2018 extension). Same result.

**Comment by anzwdev** [comment]
That explains your problems. I am sorry for that, I've only tested it with BC version of the extension. My .net language server uses Microsoft AL Extension parser to parse source code. There must be API difference that breaks it somewhere. I will check it and try to release updated extension that supports both version as soon as possible.

**Comment by lvanvugt** [comment]
Thanx

**Comment by lvanvugt** [comment]
Don't know if you updated the extension again, but now it's working fine.

**Comment by anzwdev** [comment]
I tested it with Nav 2018 CU 7 version of Microsoft AL Extension and found a difference in one of the API functions. It is now fixed, new version of the extension (1.0.2) is available in the Visual Studio Marketplace. It should work with both Nav 2018 extensions installed from vsix files and with BC version of the extension from the Marketplace.

**Comment by lvanvugt** [comment]
Looking good. Wasn't aware it isn't simple to keep it working for different extension versions. Compliment for the work.

**Comment by anzwdev** [comment]
Thank you. It is good to know that it works for you with Nav 2018 version of the AL extension.
