### ISSUE TITLE
Remove 'with' usage is not working

### ISSUE THREAD

**Issue by pjllaneras** [anzwdev/al-code-outline#221]
Hi... first thanks a lot for this great VSC plugin!!!

We are trying to remove all with ussage and when use either "Remove 'with' usage from the Active Editor" or "Remove 'with' usage from the Active Project" ends with an error:

> Método no encontrado: 'Void Microsoft.Dynamics.Nav.CodeAnalysis.CompilationOptions..ctor(Boolean, Int32, Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.ReportDiagnostic, Boolean, Microsoft.Dynamics.Nav.CodeAnalysis.IdSpaces, Microsoft.Dynamics.Nav.CodeAnalysis.CompilationTarget, Boolean, Boolean, Microsoft.Dynamics.Nav.CodeAnalysis.CompilerFeatures, Boolean, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.ReportDiagnostic>>, Microsoft.Dynamics.Nav.CodeAnalysis.CompilationGenerationOptions, Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.NavAppSupportedLocales, Microsoft.Dynamics.Nav.CodeAnalysis.CodeGenerationOption, Boolean, System.String, Microsoft.Dynamics.Nav.CodeAnalysis.ConcurrencyLevel)'.

Visual Studio Code Version: 1.55.0
Al Language extension v7.1.441584
AZ AL Dev Tools/AL Code Outline extension v2.0.25

**Comment by anzwdev** [comment]
Hi

Thank you for reporting the issue. I am currently finishing testing and bugfixing the extension after a few bigger internal changes. I want to release it as soon as possible, new version will also fix your problem.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it works for me now, could you check if it also works for you?

**Comment by pjllaneras** [comment]
Hi @anzwdev ... Yes!!!! It works perfectly!!! You're awesome!!!
