### ISSUE TITLE
Can I create Captions for Tables and Pages?

### ISSUE THREAD

**Issue by DanielGoehler** [anzwdev/al-code-outline#223]
Is it possible to also add Captions for Table, Page, Report, XMLport and Query Objects?

**Comment by anzwdev** [comment]
Yoy can use "Add Table Field Captions" commands to add missing captions to the table fields and "Add Page Controls Captions" to copy captions from table fields to page controls. Do you want to be able to select an option on the wizard page to add captions or do you want to be able to run a command to copy captions from table fields to reports and queries in the current editor/all files in the project?

**Comment by DanielGoehler** [comment]
What would be cool is a command that adds missing object captions.
Before:
```
table 50000 "Prefix My Entry"
{
    fields
    {
        [..]
    }
}

```

```
page 50001 "Prefix My Entries"
{
    PageType = List;
    SourceTable = "Prefix My Entry";
	
    layout
    {
        [..]
    }
}
```

After:
```
table 50000 "Prefix My Entry"
{
    Caption = 'My Entry';
    fields
    {
        [..]
    }
}

```

```
page 50001 "Prefix My Entries"
{
    Caption = 'My Entries';
    PageType = List;
    SourceTable = "Prefix My Entry";
	
    layout
    {
        [..]
    }
}
```

**Comment by anzwdev** [comment]
I understand. That's a good idea, I'll add it.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it contains 2 new commands that you can use to add missing object captions to tables, pages, reports, xml ports and queries:
- "Add Object Captions to the Active Editor"
- "Add Object Captions to the Active Project"

I still have to modify object wizards to add captions without prefix/suffix to all these objects, there is a separate issue for it: https://github.com/anzwdev/al-code-outline/issues/231

**Comment by DanielGoehler** [comment]
Very cool, thank you!
