### ISSUE TITLE
New Remove unused variables

### ISSUE THREAD

**Issue by nikolaysotirov** [anzwdev/al-code-outline#226]
Hello , i wanted to ask if there is any chance that you can add feature like Remove unused variables.

**Comment by DavidFeldhoff** [comment]
@anzwdev I currently have a solution for that in place, but if you want to do that, I'd be totally fine as I want to focus again a little bit more on code actions instead of commands. If you do that, I'd remove my implementations

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extension, it contains two new commands that you can use to remove unused variables from the file opened in the editor or all files in the project:
- `Remove Unused Variables from the Active Editor`
- `Remove Unused Variables from the Active Project`
These commands need to compile whole solution to collect information about all symbols in the project, so it can take a few seconds to run them.
