### ISSUE TITLE
New AL File Wizard in multi root workspace

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#229]
We make use of multi root workspaces including a general scripts repo, and our extension repo with an \app and \test folder.

![image](https://user-images.githubusercontent.com/25268332/114836321-d0ff0900-9dd2-11eb-9565-e575a86e518a.png)

When using the 'New AL File Wizard', started from any selected file in the file explorer, within a proper folder having a .alpackages folder, the list of tables is properly loaded.

![image](https://user-images.githubusercontent.com/25268332/114835907-5b933880-9dd2-11eb-913b-e4b3d75c8413.png)

However, when using the 'New AL File Wizard' via the command Palette ..., the list of tables is not loaded (probably because the wizard does not know the context of the folder in which to operate, thus not being able to detect the valid .alpackages from the workspace).

![image](https://user-images.githubusercontent.com/25268332/114836262-c2b0ed00-9dd2-11eb-817f-0878a7d5b346.png)

Is there any setting / workaround to get this working? (e.g. detect the folder / .al packages based on the file opened in the current editor (if any). Or use a default setting in the workspace file to always use the \app folder?)

**Comment by anzwdev** [comment]
I've released a new version of the extension. If you run wizard from the command palette, it now uses path from file opened in the active editor and creates a new object in the same folder.
