### ISSUE TITLE
Add multiple fields ( AZ AL DEV Tools ) not working anymore

### ISSUE THREAD

**Issue by meckerlen** [anzwdev/al-code-outline#232]
Hi, 
Since few days, the add multiple fields function did'nt work in al code. It does'nt show you fields ...
Best regards,

![image](https://user-images.githubusercontent.com/57620690/115242716-7511e880-a122-11eb-8dcc-d1c69ccfe0a9.png)

![image](https://user-images.githubusercontent.com/57620690/115242744-7ba06000-a122-11eb-8f01-a20dc784fe05.png)

**Comment by anzwdev** [comment]
Are you using the latest version of Microsoft AL Extension from Visual Studio Marketplace?

**Comment by meckerlen** [comment]
Hi,
Yes, v3.0.2, we ( with my colleagues ) uninstall, install and test it with v3.0.2 and v3.0.0 and this is the same behavior.
Best,
Martial ECKERLEN

____________________________________________________________________________

**Comment by vsd1** [comment]
I can confirm Add multiple fields ( AZ AL DEV Tools ) feature is not working anymore for **PageExt** objects but is working for Page objects.
Tested it with v3.0.2 and v3.0.0

"platform": "18.0.0.0",
"application": "18.0.0.0",
"runtime": "7.0",

**Comment by anzwdev** [comment]
Which version of Microsoft AL Language extension are you using? Is it the latest 7.1.441584 from Visual Studio Marketplace? Do you have any other versions of that extension installed?

**Comment by meckerlen** [comment]
Hi, this is our version  : v7.1.441584 , this is the only one installed.

Martial Eckerlen
____________________________________________________________________________
Consultant Microsoft Business Solutions
Microsoft Business Solutions
***@***.******@***.***>
____________________________________________________________________________

**Comment by vsd1** [comment]
Same here, the Microsoft AL Language extension version is the latest v7.1.441584

**Comment by anzwdev** [comment]
Is it the only broken functionality? Can you see fields if you create a page using "New AL File Wizard"? Is AL Outline panel populated when you open AL file or is it empty?

**Comment by anzwdev** [comment]
I can replicate the problem, I am working on the fix

**Comment by anzwdev** [comment]
I've fixed the problem with page extension objects and released a new version of the extension.

**Comment by NKarolak** [comment]
I am using v3.0.3, and it does not work for me on pages (not tested on page extensions).

**Comment by meckerlen** [comment]
Hi, in case, for me it works well with v3.0.3. with v7.1.453917 for al language.
***@***.***D740EB.6027EB00]

Martial Eckerlen

**Comment by NKarolak** [comment]
That's the very same AL Language version I am also using ...weird.

**Comment by anzwdev** [comment]
Hi Natalie

When it has stopped working for you? Was it working last week?

**Comment by NKarolak** [comment]
Hi Andrzej,
no it didn't work last week, but I cannot tell when exactly it stopped working.
When I realized it didn't work, I found this issue and waited.

**Comment by vsd1** [comment]
> I've fixed the problem with page extension objects and released a new version of the extension.

I have just tested and can confirm the newly updated version v3.0.3. works now for both Page and PageExt objects.
Tested for AL language v7.1.453917.

Thanks, Andrzej

**Comment by anzwdev** [comment]
Hi @vsd1, I am happy that it works for you.

@NKarolak, I have some ideas why it might be broken in some cases, I am working on it

**Comment by anzwdev** [comment]
Hi @NKarolak

I've released a new version of the extension with a few small bugfixes. I've also switched from .net Framework 4.8 to .net 5 on Windows. Could you check if it works for you after these changes?

**Comment by NKarolak** [comment]
Dzięki Andrzej,
I will try out on Monday!

**Comment by NKarolak** [comment]
I can confirm it works again :-)

**Comment by meckerlen** [comment]
Same for me.
Best.

Martial Eckerlen


____________________________________________________________________________
