### ISSUE TITLE
Symbols browser not working: Objects not showing in package files when object of type Profile is added

### ISSUE THREAD

**Issue by mhenricus** [anzwdev/al-code-outline#234]
Weird issue when an object type Profile is added to the repo. 
See: https://github.com/microsoft/AL/issues/6589

**Comment by jmadrigalTCN** [comment]
Yes indeed, nor Sort utilities, Extract to procedure, etc.

I hope Andrzej solve it soon. It's a real pain in the a** ;-)

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've fixed it and released a new version of the extension.

**Comment by mhenricus** [comment]
👍
