### ISSUE TITLE
Table lookup

### ISSUE THREAD

**Issue by gnaaktgeboren** [anzwdev/al-code-outline#235]
In all the wizards that have a table lookup are not working anymore.
The wizards all say No Tables Found.

Reinstalling the extension had no effect.
This problem started today.

![2021-04-28_14-47-28](https://user-images.githubusercontent.com/3738183/116406243-be53ed80-a830-11eb-95b4-728668db30e1.png)

**Comment by anzwdev** [comment]
I've released a new version of the extension, problem should be fixed now.

**Comment by gnaaktgeboren** [comment]
Hi,

I don’t see the update yet in de Visual Studio market place.



Met vriendelijke groet/Kind regards,

***@***.***D74000.7079B100]
Gert-Jan Naaktgeboren

Astronaut 28
3824 MJ Amersfoort
The Netherlands
T    +31 (0) 859-022 985
F    +31 (0) 859-022 986
E    ***@***.******@***.***>
W  www.dssbv.nl<http://www.dssbv.nl/>
Member of Dynamic Retail Group BV

P Please consider the environment before printing this e-mail

Disclaimer:
Aan dit bericht kunnen geen rechten worden ontleend. Het bericht is alleen bestemd voor de geadresseerde. Indien dit bericht niet voor u is bestemd, verzoeken wij u dit onmiddellijk aan ons te melden en de inhoud van het bericht te vernietigen.
This message shall not constitute any obligations. This message is intended solely for the addressee. If you have received this message in error, please inform us immediately and delete its contents.

**Comment by pavelichenco** [comment]
Please also check issue #239. 
Because when in a Table Extension object there is a modify field (for example to add OnAfterValidate trigger to standard BC field), the wizard also shows No Tables Found.

**Comment by anzwdev** [comment]
Hi. I've fixed the issue #239 and also released new version (3.0.4) of the extension.
