### ISSUE TITLE
New File Wizard - Source Table: No Tables Found

### ISSUE THREAD

**Issue by pavelichenco** [anzwdev/al-code-outline#239]
Whenever a Table Extension Object has a field modify in it, the Wizard shows "No Tables Found" in the Source Table property.
Is it possible for you to fix this?

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've fixed it and released a new version of the extension.

**Comment by pavelichenco** [comment]
Thanks, works perfectly now!
