### ISSUE TITLE
Run in Web Client on Symbols browser

### ISSUE THREAD

**Issue by misacrni** [anzwdev/al-code-outline#240]
If you want to run table from symbols browser, it omits the Server Instance parameter from launch.Json. So server connection fails...

![image](https://user-images.githubusercontent.com/40364353/118112848-d8233200-b3e5-11eb-916a-907cad9fb47f.png)

**Comment by anzwdev** [comment]
Thank you for reporting your issue. It was a small bug, I've fixed it and released a new version of the extension.
