### ISSUE TITLE
Can not see any objects in app

### ISSUE THREAD

**Issue by RicardasKersulis** [anzwdev/al-code-outline#242]
Hi, Andrzej. Thanks for great tool! 
For some reason I can not see any objects in app (ALL apps - Microsoft and custom apps)
![empy_AL Object Browser](https://user-images.githubusercontent.com/77924918/118686804-427c0e00-b7fc-11eb-9eb9-c23be9044cec.png)
Symbols downloaded, app is compiled and published. All other functions seems to be working apart from this one.
I ma just wondering if there is any setup in VS Code or your extension, which might force to behavior in this way? Tried to reinstall Visual Studio Code and AZ AL Dev Tools/AL Code. Same behavior.
I am using VS Code 1.56.2. OS Windows_NT x64 10.0.19041
AZ AL Dev Tools/AL Code Outline v3.0.4

**Comment by anzwdev** [comment]
Hi
Thank you for reporting this issue, I am looking at it. You can temporary install previous version and use it until I find the source of the problem.

**Comment by anzwdev** [comment]
Hi

Do you still have this issue? I am not able to replicate it. If it still does not work for you, could you run "AZ AL Dev Tools: Open AZ AL Dev Tools log file" command from VS Code Command Palette and let me know if you have any errors there?

**Comment by RicardasKersulis** [comment]
Hi, Andrzej. I had this issue when developing from my local machine against cloud BC. Unfortunately can not test it anymore, as I have finished it. But I can confirm that everything is fine when working against on Prem database now. I will update if I get this issue again. Thanks for investigating it!

**Comment by anzwdev** [comment]
I've released a new version of the extension, it should work now
