### ISSUE TITLE
Add ToolTip not working correct if ' is used

### ISSUE THREAD

**Issue by Duffy77** [anzwdev/al-code-outline#244]
Hi and thank you for your great Tool.
For Translations we are working with the Comment Section and the XLIFF Tool.
So i have changed the following Property 
`"alOutline.pageFieldToolTip": "Specifies the value of the %1 field.', Comment = 'en-US=Specifies the value of the %1 field.|de-DE=Gibt den Wert des Feldes %1 an.",`

The expected behaviour should be
`ToolTip = 'Specifies the value of the code field.', Comment = 'en-US=Specifies the value of the code field.|de-DE=Gibt den Wert des Feldes code an.';`

But the closing pairs from ' are added, so the result is
`ToolTip = 'Specifies the value of the code field.'', Comment = ''en-US=Specifies the value of the code field.|de-DE=Gibt den Wert des Feldes code an.';`

I have tried to change the editor settings for closing quotes, but it only helped in the editor window and not in your function.

Thanks for your help.

**Comment by anzwdev** [comment]
Hi

Than you for reporting your issue. I've redesigned this functionality and released a new version of the extension. When ToolTips are created, field captions and field captions comments are now treated separately. There are 2 vs code settings now:
`alOutline.pageFieldToolTip` - this pattern is used to create "Label" part of the ToolTip
`alOutline.pageFieldToolTipComment` - this pattern is used to create "Label Comment" part of the ToolTip

In both these patterns these placeholders can be used:
%1 and %Caption% for table field caption
%Caption.Comment% for table field caption comment

Default values are:
- `alOutline.pageFieldToolTip: "Specifies the value of the %1 field"`
- `alOutline.pageFieldToolTipComment: "%Caption.Comment%"`
With these default settings, created ToolTip will containg table field caption text only and if there is a comment in table field caption, it will be copied to ToolTip comment.
