### ISSUE TITLE
Error during Build : al-lang-proxy\tempalfile.al(1,10)

### ISSUE THREAD

**Issue by misacrni** [anzwdev/al-code-outline#245]
when object from base app is open in Visual studio code, and you run Build command of your project, you get Error for file missing.
This only happens when we view Object with this extension. 
![image](https://user-images.githubusercontent.com/40364353/120296109-15cdf900-c2c8-11eb-972a-b6e6ae93f709.png)

Please check why is this happening.

**Comment by anzwdev** [comment]
I've released a new version of the extension. It uses a different method of opening object definitions so you should not see this error message anymore.
