### ISSUE TITLE
'Show Action Images' does not work in a multi-root workspace

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#246]
When working in a multi root workspace (/app and /test), the 'Show Action Images' does not work.
When opening one of the folders (/app) instead of the workspace, 'Show Action Images' does work.

![Images2](https://user-images.githubusercontent.com/25268332/120470557-f3a9a900-c3a3-11eb-8ef8-320441891bae.gif)

**Comment by anzwdev** [comment]
Hi

Thank you for reporting your issue. I've redesigned this functionality and released a new version of the extension.
