### ISSUE TITLE
Exclude specific object from codeActionsOnSave : sortVariables / sortProperties 

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#247]
In some cases, we're forced to **copy** code / objects from related extensions (e.g. Business Central reports, Continia codeunits, ...) to our own extensions. Part of the release process is making sure copied objects are reviewed against the newest version of the original object. This can easily be done by comparing the files.

However, we've the codeActionsOnSave active on all our repos / workspaces, thus making one small modification to this object automatically reorders the properties / variables, making it way more difficult to compare the objects.

Would it be possible to mark an object to be excluded from the codeActionsOnSave ?

- Some kind of #pragma directive in the object itself?
- Putting them in a separate subfolder (/Copied)?
- Maybe listing them in a settings.json array
- https://stackoverflow.com/questions/54243641/vscode-codeactionsonsave-ignore-specific-file

**Comment by anzwdev** [comment]
Hi. That's a good idea, I'll add it. settings.json seems to be the best place to keep list of these files/folders.

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extension with this new functionality. There is a new `codeActionsOnSaveIgnoreFiles` setting, it is an array of vscode patters of files that should be ignored when OnSave code actions are run. To make it work, the pattern should always start with `**/`, so if you want to exclude files from **OldFiles** folder, the pattern should be `**/OldFiles/*.al`
