### ISSUE TITLE
Idea: Reuse tooltip from other pages

### ISSUE THREAD

**Issue by dannoe** [anzwdev/al-code-outline#249]
It would be awesome if we could run a code action on field level and it would try to search and add an existing tooltip from another page. (maybe even the base app?) If there are multiple pages with different tooltips an selection would be great.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this idea. I've released a new version of the extension, it will now reuse first already define tooltip for each field in wizards and in "Add tooltips" commands. This behaviour can be disabled by switching `alOutline.doNotReuseToolTipsFromOtherPages` setting to true. It is also possible to limit searching for existing tooltips to only some of the dependencies/current project by listing them in `alOutline.reuseToolTipsFromDependencies` setting. It is an array of string where each entry should be defined as <dependency publisher> + <space> + '-' + <space> + <dependency name>.

There are 2 new commands that you can use to refresh tooltips values in the current project/editor from dependencies:
- `Refresh ToolTips from Dependencies in the Active Editor`
- `Refresh ToolTips from Dependencies in the Active Project`

There is also a code action available on first line of each page field and on ToolTip property: `Reuse ToolTip from other Pages (AZ AL Dev Tools)`. When you run it it will allow you to select tooltip for the list of all already defined values for this field.
