### ISSUE TITLE
Incorrect sorting of objects in AL Object Browser

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#25]
Hi @anzwdev,

Since version 1.0.0, the objects in the AL Object Browser are not sorted correctly:

![example-bug](https://user-images.githubusercontent.com/7383241/56658532-20564700-669b-11e9-9ac6-e84946b392c9.png)

This appears to be a bug introduced with the refactoring of the extension.

**Comment by anzwdev** [comment]
I've added missing sorting function to the AL Object Browser. Fix has been published with the new version of the extension. Thank you for reporting it.
