### ISSUE TITLE
ToolTip is added when ToolTipML is already set

### ISSUE THREAD

**Issue by wbrakowski** [anzwdev/al-code-outline#250]
Hey Andrzej,

first of all: the adding of tool tips is an awesome feature, I recently used it a lot.

What I noticed today: When you work with CaptionML in a project, the tooltip is being added although there is already a ToolTipML specified. Of course it is always better to just work with translation files, but maybe you want to have a look at that. If not, also fine for me.

![image](https://user-images.githubusercontent.com/53928639/121647898-31d75480-ca97-11eb-9cd5-2068cb6108a9.png)

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this issue. I've released a new version of the extension, it won't create Caption or ToolTip if CaptionML or ToolTipML property exists.
