### ISSUE TITLE
sortVariables / sortProperties with // comments results in invalid objects

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#252]
In some cases, we add // at the end of the variable definition / property, on the same line. If I remember well, in previous versions of the extensions, the auto format (with the sortVariables / sortProperties settings enabled) resulted in moving the comment to another line, adding it to the list of variables / properties. (not really wanted behavior, we'd like to keep the comment to the property / variable it belongs too)

Before:
- Customer : record Customer; // A customer record

- PageType = Card; // A card page

After
- Customer : record Customer; 
  // A customer record

- PageType = Card; 
  // A card page

![image](https://user-images.githubusercontent.com/25268332/122004404-a6223880-cdb4-11eb-8caa-760fb7ed9282.png)

However, we found another more blocking issue, where the // at the end of the line absorbes other variable definitions / properties, resulting in compilation errors.

Here's some screenshots of invalid formatted documents:

![image](https://user-images.githubusercontent.com/25268332/122003551-863e4500-cdb3-11eb-8465-ffde397477bc.png)

![image](https://user-images.githubusercontent.com/25268332/122003560-89393580-cdb3-11eb-83d9-d9c8963c0b8e.png)

![image](https://user-images.githubusercontent.com/25268332/122003571-8c342600-cdb3-11eb-98ab-4a6ad2d3f6f4.png)

**Comment by anzwdev** [comment]
Than you for reporting this issue. I've fixed it and released a new version of the extension.
