### ISSUE TITLE
Copy entries from "Project Symbols"

### ISSUE THREAD

**Issue by jensW81** [anzwdev/al-code-outline#253]
When I open "Project Symbols" then I would like to copy the entries from the tabs "Tables", "Pages" etc.
But I don't see any possibility to copy the values from there to for example an Excel file.
Is there a trick to do so or is this feature missing?

Here what I mean (of course when there are any records containing ;-))
![image](https://user-images.githubusercontent.com/38862589/122088085-b9112900-ce05-11eb-9800-be88636e794d.png)

**Comment by anzwdev** [comment]
Hi

You can select multiple or all records, right click on one of them and use "Copy Selected" menu item from the context menu.

**Comment by jensW81** [comment]
I did already before but context menu does not contain copy. I installed the latest version from extension market 3.0.6

![image](https://user-images.githubusercontent.com/38862589/122168300-69217900-ce7c-11eb-8184-d4d5a6962c02.png)

**Comment by jensW81** [comment]
I just installed the latest visual code update and now the menu entry to copy is displayed.
![image](https://user-images.githubusercontent.com/38862589/122172072-b30c5e00-ce80-11eb-8153-d8e9965488b9.png)
