### ISSUE TITLE
[Question] Best approach to make multiple changes to a AL file

### ISSUE THREAD

**Issue by ricardopaiva** [anzwdev/al-code-outline#255]
Hi Andrzej,

I'm working on a new extension and I'm looking at your extension and also at al-codeactions extension by DavidFeldhoff.
I'm struggling the make more than one update at once on the same file, on different places.
As an example, I want to add the layout and the global vars section.

I'm using the FullSyntaxTree component to retrieve the full syntax tree for the current opened page.

`let fullSyntaxTreeResponse: ToolsGetFullSyntaxTreeResponse | undefined = await azalDevTools.toolsLangServerClient.getFullSyntaxTree(toolsGetFullSyntaxTreeRequest, true);`

Then I need to get the position where the text will be inserted and for that I use a method that David created on his extension:
`
    public static createVSCodeRange(textRange: any): Range {
        let vscodeRange: Range = new Range(textRange.start.line, textRange.start.character, textRange.end.line, textRange.end.character);
        return vscodeRange;
    }
`

So to get the position, I have something like this.
`let positionToAdd = new Position(TextRangeExt.createVSCodeRange(objRefNode.fullSpan).end.line + 1, 0);`

Then I add the layout snippet using the WorkspaceEdit.

`        let workspaceEdit = new WorkspaceEdit();
        workspaceEdit.insert(document.uri, positionToAdd, textToInsert);
        await workspace.applyEdit(workspaceEdit);
`

Then I want to insert the GlobalVars section and for that, once again, I need to get the position where the text should be added. If I use the same method, since the SyntaxTree is no longer updated because in the meanwhile I added the layout section to the document, the position retrieved will not be ok.
So what I'm doing is to call the getFullSyntaxTree again, to update the SyntaxTree with the changed document and get the updated node.

This is working but there must be a better way to do it and to avoid having to refresh the syntax tree everything a change is made to the document.
Once again, if I also want to add an actions section after the GlobalVars section, for example, I need to make sure that I refresh the SyntaxTree again (and again and again).

Is this the way to go? Should I be using other component instead of the FullSyntaxTree for this purpose?

Thanks for all the help you can provide me. Please let me know if I didn't make myself clear or if you need some more code samples.

Thanks in advance.

**Comment by anzwdev** [comment]
Hi

If you have all information that you need at the beginning of your function, then you can try to add multiple edit actions to your workspaceEdit and invoke workspace.applyEdit only once at the end.

I've added FullSyntaxTree functionality to the extension for David to help him analyze and modify code, but it is not always easy as this approach has some limitations.

**Comment by ricardopaiva** [comment]
Thanks for your reply. I really appreciate it!
Unfortunately, I need to add code pieces on different places of the page extension.

A good alternative could be to add the code in reverse order.
For example, start by adding the global vars section in the bottom, then the triggers above, then the actions and finally the layout section on the top.
If I do that, then the position where I want to add code is not affected by the code already added in the bottom, so I don't need to rebuild the syntax tree every time a change is made to the document.

Not sure if I made myself clear.
I'll think about it.
Otherwise refreshing the syntax tree on every document update is not that bad :p

**Comment by anzwdev** [comment]
Have you tried to use single WorkspaceEdit? I might be wrong as I no longer use use this approach in my extension, but I think that if you use singe edit to apply multiple changes, then it can adjust positions of next changes if the previous one modifies text at the front of them.

```javascript
let workspaceEdit = new WorkspaceEdit(); 
workspaceEdit.insert(document.uri, positionToAdd1, textToInsert1); 
workspaceEdit.insert(document.uri, positionToAdd2, textToInsert2); 
await workspace.applyEdit(workspaceEdit);
```

**Comment by ricardopaiva** [comment]
I've tried that and it worked.
I just need to get the positions where I want to insert each different piece of code and then do all the inserts at once and apply those.
VSCode will dynamically update each position based on the inserts being done.
Once I apply, if I need to insert some code, I'll have to refresh the syntax tree because the document structure is no longer updated, so that I can calculate the right position to add the code but that's perfectly fine and understandable.

Thanks for your reply. It was really helpful. I'll continue exploring yours' and David's extension and the available VSCode commands.

**Comment by ricardopaiva** [comment]
Andrzej,

Like you said, you've just added FullSyntaxTree functionality to the extension for David to help him analyze and modify code.
Instead of using the FullSyntaxTree, which alternatives should I consider? Using the AZSymbolInformation? Basically I want to use it to search for information, to check if some method/trigger or some variable already exists or needs to be created.
As far as I can see, the AZSymbolInformation class has a lot of methods to collect and find symbols.

**Comment by anzwdev** [comment]
AZSymbolInformation is a simplified structure build from SyntaxTree and it ends at procedures header level. You can use it to get information about procedure parameters or local variables, but not about the al code inside. That's why FullSyntaxTree has been created. It contains all syntax tree nodes. If you want to modify source code inside procedures or triggers, you need to use FullSyntaxTree, if you don't need to go so deep into the object structure, AZSymbolInformation should be enough.

**Comment by ricardopaiva** [comment]
Thanks Andrzej.

I'm currently using FullSyntaxTree and everything is fine so far so i think I'm definitely stick to it.

Your extension is amazing and David also made an amazing job extending it with some useful classes to handle entities and code.
