### ISSUE TITLE
Suggestion: Tooltip generation from field's description

### ISSUE THREAD

**Issue by mjmatthiesen** [anzwdev/al-code-outline#256]
I saw #249 and that reminded me of a potentially easy way to implement this. AFAIK, it would only work for internal fields.

I have this table:

```
table 50000 "Some Data"
{
    Caption = 'Data';

    fields
    {
        field(1; "Data"; Text[250])
        {
            Caption = 'Data Data';
            Description = 'This data is an example.';
        }
    }
}
```

Now when I make the page and insert fields, it would be great if it read that description and added it as a tooltip. This may not be something that everyone wants, but it would be useful, especially if fields may end up on multiple pages. I can read the description of a field if I have the app installed with show my code true, but not sure on those where it isn't true. Maybe this is too far out there to begin with.

This would be a useful code action / setting for me, but I'm not sure how others feel about it.

**Comment by anzwdev** [comment]
Hi

Thank you for the idea. I agree, not everybody will want it, as people are using field descriptions for different purposes, so it has to be a separate command.

**Comment by anzwdev** [comment]
I've implemented your idea and released new version of the extension.
I've added a new setting - "alOutline.useTableFieldDescriptionAsToolTip". If you set it to true, "Add ToolTips" commands and page wizard will use Description property from table field as tooltip source. If description is empty, field caption and tooltip template will be used.

**Comment by mjmatthiesen** [comment]
Thanks! Gave it a quick test and it worked great!
