### ISSUE TITLE
Issue with Field Name Area for API page

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#257]
I automatically created new API pages and had one Field with the name "Area".

This resulted in an error since area isn't a valid page field name.

Maybe this can solved by surrounding area with quotations. 

Wrong:
```al
field(area; Rec."Area")
{
    Caption = 'Area';
}
```

Right:
```al
field("area"; Rec."Area")
{
    Caption = 'Area';
}
```

Related: https://github.com/anzwdev/al-code-outline/issues/228

**Comment by pri-kise** [comment]
Something related:

The Query-Control names of Query with QueryType=API; should be lowercase.
![image](https://user-images.githubusercontent.com/56249171/123644145-654f0880-d825-11eb-852d-770466eee90f.png)

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've fixed it and released a new version of the extension.
