### ISSUE TITLE
Add DataPerCompany to AL Table File Wizard

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#266]
It would be nice to have the `DataPerCompany` property as a field in the AL Table File Wizard, considering this is a field that significantly impacts how the tables are generated in SQL, so it would be better to have this set _explicitly_ for all table objects.

**Comment by anzwdev** [comment]
Hi Rob

Thank you for your suggestion. I've added this field to the wizard and released a new version of the extension.

**Comment by rvanbekkum** [comment]
Great! 😊
