### ISSUE TITLE
Name Filter in 'TreeView' Object Browser filters on Type + Name

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#27]
Hi @anzwdev,

I noticed that the Name filter uses the **Type + Name** to filter on rather than just the **Name** of the objects.
For example, if you filter on `Item*` you won't get results, but if you filter on `Table Item*` then you do get results.
Could you look into this?

**Comment by anzwdev** [comment]
Filter was applied to full description instead of object name. I've fixed it and uploaded new version of the extension to the marketplace.
