### ISSUE TITLE
Integrate object wizards with AL Object ID Ninja

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#276]

**Comment by fvet** [comment]
Any chance on supporting this in a next release? Thx!

**Comment by anzwdev** [comment]
Yes, I will focus on this task first

**Comment by anzwdev** [comment]
Solution is almost ready. It requires "AL Object ID Ninja" to expose reservation API to other vs code extensions. I've created a new pull request with proposed solution in the AL Object ID Ninja repository, we have to wait for it to be accepted or modified and released.

**Comment by anzwdev** [comment]
It is my mistake, I forgot to remove it from the changelog before the release. It is not ready yet. I've added support for other "id providers", but "AL Object ID Ninja" provider implementation still needs pull request to AL Object ID Ninja repository to be approved and merged.

**Comment by SBiernat** [comment]
Hey @anzwdev,
i have set the setting ""alOutline.idReservationProvider": "ALObjectIdNinja",".
The integration seems to work well. But unfortunately not for TableExtensions. There i have no Field for the Id Provider.

**Comment by anzwdev** [comment]
Hi @SBiernat 

Thank you for reporting the issue. Yes, there is a bug, I am calling async function without await. Fix will be ready in the next release.
