### ISSUE TITLE
<ObjectType> placeholder for camel-cased folder names.

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#28]
Hi @anzwdev,

With recent updates in the extension, we noticed that function `getPatternGeneratedRelativeFilePath`/`getObjectTypeFromSymbolInfo` in file `fileBuilder.ts` now returns a _lowercase_ object type name, rather than a camel-case object type name like it used to in previous versions of the extension.
This seems to be due to the name now coming from the CRS extension.

We are using the `<ObjectType>` placeholder for the file paths that new extensions are generated in:
![image](https://user-images.githubusercontent.com/7383241/57609664-9bf73580-756f-11e9-8bf4-cb27a9d09412.png)
But with the recent change, this gives us some issues (i.e., the file is generated in the correct folder, because Windows treats the path case-insensitive, but we get errors/warnings from VSCode that the file already exists in both the lower-cased and camel-cased folder).

I can understand you want to keep the `<ObjectType>` in line with the CRS extension, but maybe you could introduce an additional placeholder that will return the type name in camel-case (e.g. `<ObjectTypeCC>`)?

**Comment by anzwdev** [comment]
I am going to switch <ObjectType> to use camel-case names and add <ObjectTypeLC> to use lowercase version.

**Comment by anzwdev** [comment]
Modification has been added to the extension and published to the Visual Studio Marketplace.

**Comment by rvanbekkum** [comment]
Thank you for the quick fix!
