### ISSUE TITLE
AZ AL Dev Tools: Fix Identifiers and Keywords Case in the Active Project does not fix area(...) casing

### ISSUE THREAD

**Issue by ernestasjuska** [anzwdev/al-code-outline#280]
Hi,

AZ AL Dev Tools: Fix Identifiers and Keywords Case in the Active Project does not fix `area(...)` casing.

This applies to other places where `area(...)` syntax is used: action areas and using `addfirst(...)`, `addlast(...)` that incorrectly (IMO) suggest lowercase.

This

```al
page 50100 "My Page"
{
    layout
    {
        area(content)
        {
        }
    }
}
```

does not become

```al
page 50100 "My Page"
{
    layout
    {
        area(Content)
        {
        }
    }
}
```

AL language extension suggests the correct casing:
![image](https://user-images.githubusercontent.com/53167314/134676786-11a9df2c-c184-48a5-b6b6-2f7ac701d323.png)

and also incorrect casing :)
![image](https://user-images.githubusercontent.com/53167314/134677287-56e6941a-8919-477d-85be-03b237995f00.png)

Thanks.

**Comment by anzwdev** [comment]
Thank you for reporting this bug. I've fixed it and released a new version of the extension. It will fix case of the area name inside "area" keyword in page layout and actions sections. 

You saw "content" suggested by vscode for addfirst/addlast sections, because compilers gets control names from the page you are extending and you had "content" there.

**Comment by ernestasjuska** [comment]
I see. I didn't realize the area names used in page are treated like regular control names.

In that case it should only change casing in page layout/action areas. Most of standard pages have lowercase areas because that is how Txt2al tool generated them.

Personally, I would like to see area casing changed to CamelCase only for custom pages and then custom page extensions if they are in the same workspace. In all other cases it should just use whatever completion VS Code gives.
Or just use lowercase areas everywhere for consistency, because having `area(content)` in some places, but `area(Content)` in others is pretty weird.

Thanks.
