### ISSUE TITLE
AZ AL Dev Tools: Fix Identifiers and Keywords Case in the Active Project incorrectly renames dotnet type definitions

### ISSUE THREAD

**Issue by ernestasjuska** [anzwdev/al-code-outline#282]
Hi,

AZ AL Dev Tools: Fix Identifiers and Keywords Case in the Active Project incorrectly renames dotnet type definitions.

This

```al
dotnet
{
    assembly(mscorlib)
    {
        type("System.Convert"; Convert)
        {
        }
    }
}
```

becomes

```al
dotnet
{
    assembly(mscorlib)
    {
        type(Convert; Convert)
        {
        }
    }
}
```

Similar to #278.

Thanks.

**Comment by anzwdev** [comment]
Thank you for reporting this problem. I've fixed it and released a new version of the extension.
