### ISSUE TITLE
Show object name length/character count in AL Object File Wizards

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#285]
Hi @anzwdev,
It would be nice to get a character count (length) indicator for object names in the AL Object File Wizards, considering we still need to adhere to the (small) 30 character name limit. 🙈

Here is an example of how this could look like:

![character_count_example](https://user-images.githubusercontent.com/7383241/136354033-4ead9065-4070-45c7-845c-c90e88a6f754.png)

**Comment by anzwdev** [comment]
Hi @rvanbekkum

Thank you for your suggestion. I've added character counter and also change the max length of text box content to 30 characters for all objects where object name cannot be longer. New version of the extension is available in the Visual Studio Marketplace.
