### ISSUE TITLE
fixCodeCopUnusedVariablesOnSave (fix AA0137 warnings)

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#287]
While refactoring, we very often receive the CodeCop [AA0137](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0137) warning for unused variables. Solution to fix is simple : remove the variable.

It would be nice if this could be included in the codeActionsOnSave, through a new setting fixCodeCopUnusedVariablesOnSave 
 (similar to fixCodeCopMissingParenthesesOnSave).

So when saving an al file, any references to unused variables could be auto solved.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this idea. I want to investigate first if I can make it work without waiting for CodeCop to report warnings. I am also not sure if running it on save is a good idea. Some developers like to save files in the middle of typing, if they do it when they create procedure header with local variables, but before they start populating procedure body, they will lose part of the code.

**Comment by DavidFeldhoff** [comment]
For now, my solution is that you can execute a command which removes all unused variables (it compiles the solution to generate the code cops and removes the variables then)
![image](https://user-images.githubusercontent.com/53570297/138232419-a380ad10-e0ca-41e2-bee4-faae8c3ef16a.png)
![image](https://user-images.githubusercontent.com/53570297/138232484-8bf95914-cb88-4130-8abf-1e406882c601.png)

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extension with two new commands that don't need code analyzers to remove unused variables from the file opened in the editor or all files in the project:
- `Remove Unused Variables from the Active Editor`
- `Remove Unused Variables from the Active Project`
These commands need to compile whole solution to collect information about all symbols in the project, so it can take a few seconds to run them.

**Comment by anzwdev** [comment]
I've just released another version of the extension with these 2 new commands that can add missing parentheses without using CodeCop:
- `Add Missing Parentheses to the Active Editor`
- `Add Missing Parentheses to the Active Project`
They work the same way as "Remove Unused Variables" commands - they need to compile whole solution to get information about all symbols.
