### ISSUE TITLE
Add Object Captions to Active Project (exclude API pages)

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#289]
For API pages, we always set the EntityCaption / EntitySetCaption, but not the page captions.

BC standard API pages don't have the Caption property set either.

![image](https://user-images.githubusercontent.com/25268332/137763009-0841299d-e940-4e59-a296-190ed9eff947.png)

Running "Add Object Captions to Active Project" wrongfully adds the Caption property. Would be good if it can be excluded by default (without a setting).

![image](https://user-images.githubusercontent.com/25268332/137763593-825c813f-a786-4490-b3d6-bea18a277a59.png)

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this issue. I've fixed it and released a new version of the extension.
