### ISSUE TITLE
Bug with generating objects from AL Object Browser without selecting row

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#29]
Hi @anzwdev,

We ran into the following issue:
If you apply a filter in the AL Object Browser (e.g., set ID filter to 27), and then right-click the row without first selecting it, then trying to run one of the object builders won't give you any result.
Here is also a screenshot of the situation in which this happens (i.e., the row is not selected, but if you press "New Page Extension" now, you won't get a new object):

![image](https://user-images.githubusercontent.com/7383241/57610388-052b7880-7571-11e9-8036-d285a4ee5894.png)

If you first select the row, then the new object will be generated as expected.

**Comment by anzwdev** [comment]
I've modified Object Browser code to add object on which right click was invoked to list of selected objects. It should solve your issue, but it is still not the best solution as it should clear previous selection if ctrl key is not pressed during right click. This is just quick fix, list view version of Object Browser needs much more work to add better selection and keyboard navigation.
