### ISSUE TITLE
Add Application Areas to labels

### ISSUE THREAD

**Issue by gretanorv** [anzwdev/al-code-outline#290]
Runing 'Add Application Areas to the active project' does not add ApplicationArea to labels. Would be good to have it:

![image](https://user-images.githubusercontent.com/48092156/138691111-9d57cae6-3c34-4e56-beb8-c868221ea69f.png)

**Comment by anzwdev** [comment]
Hi

Thank you for reporting your issue. I've fixed it and released a new version of the extension.
