### ISSUE TITLE
Sorting code-actions as commands for current file and active project

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#293]
Hi @anzwdev,
It would be nice to have the sorting code-actions (for procedures, variables, properties, fields, ...) as a command or multiple commands.
This would make it easier to apply them. 😊

**Comment by anzwdev** [comment]
Hi @rvanbekkum

That's a good idea, i'll do it.

**Comment by rvanbekkum** [comment]
Great! 😊 Could I file one last request? 😅 Would it be possible to add commands that runs _all_ sorting commands for the active project or the active editor?

Thank you for adding the commands! 😁

**Comment by anzwdev** [comment]
Yes, it will be possible to run all these commands together with other file/project commands, it already has been request in issue #295
