### ISSUE TITLE
Error adding Parentheses to Active Project

### ISSUE THREAD

**Issue by GreatScott000** [anzwdev/al-code-outline#294]
I am getting this error when adding parentheses to the whole project.  It worked for 67 of about 650 files and then stopped.
![image](https://user-images.githubusercontent.com/4333956/141969359-38de79d6-7568-4e57-9edd-680553759b30.png)

I am willing to believe it is formatting problem in an object file but I have no idea which one .  Is there an order it processes the files?  
Can you log the current file being processed?  If I knew what file/object was the problem that would be a big help.

We are converting a NAV 2016 project that was poorly done and has some real issues, some objects were converted manually by juniors and maybe not correctly.  Also there are a few NAV acceptable syntaxes that AL does not like.  The ones we have run into a number of times is no trailing semi-colon ";" on the last line inside of a procedure or repeat until loop.

> 2021-11-16 10:29:33.420 [ERROR] tid:5 in 'LogError' C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\AnZwDev.VSCodeLangServer\Protocol\MessageProtocol\AbstractMessageHandler.cs: line 30
>     Error: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.InvocationExpressionSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.IdentifierNameSyntax'.
>    at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitPageField(PageFieldSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 375
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 166
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 139
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitPageGroup(PageGroupSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 401
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 166
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 139
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitPageArea(PageAreaSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 471
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 166
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 139
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitPageLayout(PageLayoutSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 356
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitPage(PageSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 341
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitListElement[TNode](TNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 166
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxRewriter.cs:line 139
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxRewriter.VisitObjectCompilationUnit(ObjectCompilationUnitSyntax node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SyntaxRewriter.Generated.cs:line 22
>        at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxVisitor`1.Visit(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxVisitor.cs:line 33
>        at AnZwDev.ALTools.WorkspaceCommands.AddParenthesesWorkspaceCommand.ProcessFile(SyntaxTree syntaxTree, SemanticModel semanticModel, ALProject project, Range range, Dictionary`2 parameters) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\WorkspaceCommands\AddParenthesesWorkspaceCommand.cs:line 30
>        at AnZwDev.ALTools.WorkspaceCommands.SemanticModelWorkspaceCommand.ProcessFiles(List`1 syntaxTrees, Compilation compilation, ALProject project, Dictionary`2 parameters) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\WorkspaceCommands\SemanticModelWorkspaceCommand.cs:line 134
>        at AnZwDev.ALTools.WorkspaceCommands.SemanticModelWorkspaceCommand.Run(String sourceCode, String path, Range range, Dictionary`2 parameters) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\WorkspaceCommands\SemanticModelWorkspaceCommand.cs:line 44
>        at AnZwDev.ALTools.WorkspaceCommands.WorkspaceCommandsManager.RunCommand(String commandName, String sourceCode, String path, Range range, Dictionary`2 parameters) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools\WorkspaceCommands\WorkspaceCommandsManager.cs:line 67
>        at AnZwDev.ALTools.Server.Handlers.WorkspaceCommandRequestHandler.HandleMessage(WorkspaceCommandRequest parameters, RequestContext`1 context) in C:\Projects\GitHub\az-al-dev-tools-server\AZALDevToolsServer\Shared.AnZwDev.ALTools.Server\Handlers\WorkspaceCommandRequestHandler.cs:line 30
>

**Comment by anzwdev** [comment]
Hi.

Thank you for reporting the problem. I'll modify error handling to include processed file in the log. I am using standard .net System.IO.Directory.GetFiles method that returns all files with subfolder, unfortunately it does not order files, so I am not able to tell you how to find the file, but logged call stack suggests that the problem was caused by one of page fields in your files.

**Comment by GreatScott000** [comment]
Thank you!

**Comment by anzwdev** [comment]
I've released a new version, both error messages and log file contain name of processed file now. It should help you find on which file the command crashes. Please let me know if you find which line of code is breaking my command. My solution replaces nodes in the syntax tree and it looks like your case is a special one and requires to modify also the parent of the node.

**Comment by anzwdev** [comment]
Thank you for finding it, I am working on the fix now.

**Comment by anzwdev** [comment]
Thank you for your help. I've fixed the problem and released a new version of the extension.

**Comment by GreatScott000** [comment]
This looks good, thanks.
