### ISSUE TITLE
Investigate if it is possible to run workspace commands before staging/commiting changes

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#295]
Idea from Twitter from Frédéric Vercaemst:

>Is there any way in VSCode to run a set of these commands (only for 'modified' files) just before staging / committing? This way, all devs apply the same rules (and will not forget) and have them auto-applied for all 'modified' files. ('Active Project' contains too much files)

It needs investigation to decide if it is possible and if running commands before commit makes sense. At this moment I can see a few problems:
- some people might commit outside of Visual Studio Code
- if we run commands before commit, vs code will be uploading not tested code to the source control server

**Comment by fvet** [comment]
Having a separate 'Apply all rules for modified files´ vscode command would be great.

Dev would be in charge to run it once before commiting or staging.

'All rules´ could be an array in settings.json that includes fixing parentheses, fix keywords casing, order variables, order properties, remove last empty line, remove unused vars, format document, ...

´modified files´ should be the commited / staged files only, to keep the number of files to proces low. Chosing ´entire project´ would slow down process on large apps (5000 files)

**Comment by fvet** [comment]
Havent seen the idea from dkatson till now 😀

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extension which contains this modification. There are 3 new commands availabe in vs code:
- `Run Code Cleanup on the Active Editor`
- `Run Code Cleanup on the Active Project`
- `Run Code Cleanup on Uncommited Files in the Active Project`

Third one will use "git" command to detect modified, uncommited files and run code cleanup only on these files. It means that git command line tools should be available in the system. If they are not there, it won't work.

There is also a new `alOutline.codeCleanupActions` setting to specify which commands should be run during cleanup. It is an array of strings and can contain these values:
- "RemoveWithStatements",
- "AddApplicationAreas",
- "AddToolTips",
- "RefreshToolTips",
- "AddTableFieldCaptions",
- "LockRemovedFieldCaptions",
- "AddPageFieldCaptions",
- "AddObjectCaptions",
- "FixKeywordsCase",
- "FixIdentifiersCase",
- "ConvertObjectIdsToNames",
- "AddMissingParentheses",
- "AddDataClassifications",
- "RemoveUnusedVariables",
- "SortPermissions",
- "SortPermissionSetList",
- "SortProcedures",
- "SortProperties",
- "SortReportColumns",
- "SortTableFields",
- "SortVariables",
- "RemoveBeginEnd",
- "FormatDocument",
- "TrimTrailingWhitespace"

**Comment by fvet** [comment]
Looks very nice, thanks a lot! 
Will give it a try soon.

PS: Discovered small typo.

_Runnung > Running_ 

![image](https://user-images.githubusercontent.com/25268332/148041701-9c9fb115-452c-4004-935b-2cd8b83d3e28.png)
