### ISSUE TITLE
Codeunit Wizard does not copy temporary flags

### ISSUE THREAD

**Issue by cosmolange** [anzwdev/al-code-outline#296]
Hi, 

Yesterday I used the Codeunit Wizard to create a codeunit that implements an interface.
![2021-11-18_11h45_35](https://user-images.githubusercontent.com/94607795/142402463-11ea8279-41c5-494e-82a2-681e8d1f19e4.png)

In the interface exists a function "GetSnLotTxt".
![2021-11-18_11h50_23](https://user-images.githubusercontent.com/94607795/142402761-6418a07a-ac7c-4c92-9297-a9c79a4ed8f6.png)

The codeunit wizard creates this procedure also in my codeunit, but then 'temporary' flag gets lost.
This leads to the error AL0582 'Test Codeunit' does not implement the interface member 'CCS RS ISalesOrderImplementations.GetSnLotTxt'.

![2021-11-18_11h48_11](https://user-images.githubusercontent.com/94607795/142402947-2a0a0238-1032-4011-a0e0-9c9600c47b02.png)

**Comment by anzwdev** [comment]
Thank you for reporting your issue. I've released a new version of the extension, this problem should be fixed now.
