### ISSUE TITLE
Parenthesis added when not required, causes compile error

### ISSUE THREAD

**Issue by GreatScott000** [anzwdev/al-code-outline#298]
This is probably a left over from old NAV, C/AL days.  There were a few functions that you could "assign" a value to (e.g. FilterGroup, PageNo) and the add parentheses command adds parenthesis to the assignment (left) side of the statement.  FilterGroup seems to work correctly, PageNo does not.  Yes I know it is deprecated but, I have a lot of reports I am converting that use this and this action causing an error is annoying.

```
trigger OnAfterGetRecord()
            begin
                CurrReport.PageNo := 1;
            end;
```
becomes
```
trigger OnAfterGetRecord()
            begin
                CurrReport.PageNo() := 1;
            end;
```
which causes a compile error.

**Comment by anzwdev** [comment]
Hi

Thank youy for reporting this problem. I've fixed the extension and released a new version.

**Comment by GreatScott000** [comment]
Looks good, thanks.
