### ISSUE TITLE
Idea: Fix begin..end (AA0005) warnings in project/editor

### ISSUE THREAD

**Issue by dannoe** [anzwdev/al-code-outline#300]
It would be awesome if we could get a command to fix this issue in the active project/editor:

https://docs.microsoft.com/de-at/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0005
AA0005
Only use BEGIN..END to enclose compound statements.

**Comment by anzwdev** [comment]
It can be done, I just need to think how to do it and how far I should go. I usualy don't use begin/end with a single statement, but I prefer to leave it for more complex scenarios where I have "if" with "else" inside another "if".

**Comment by dannoe** [comment]
We used it heavily in c/al, so our codebase is covered with begin-ends with single statements.

Is there a guide on how to start developing on your extension? I already tried to start on my own and cloned this and the server repo, but I couldn't figure out how and which dlls to reference in the server project and connect the vsc extension with the .net server. To be honest, however, I have also not invested much time. A developing guide or quickstart could motivate more people to add some pull requests 😉

**Comment by anzwdev** [comment]
Hi

A quickstart developing guide is a good idea, I will try to prepare something.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this idea. I've released a new version of the extension, it contains 2 new actions that you can use to remove begin..end around single statements:
- `Remove Begin..End around Single Statements from the Active Editor`
- `Remove Begin..End around Single Statements from the Active Project`

**Comment by dannoe** [comment]
Thats awesome! Thanks for the quick implementation of this and #249 
I will test both features soon!

**Comment by dannoe** [comment]
I just used the command for the whole project and got only 2 missing semicolons.

You can reproduce the missing semicolon with the following code:

```al
codeunit 5153297 "TEST Codeunit"
{
    trigger OnRun()
    var
        MyRequest: Codeunit "MyMyRequest";
        MyLibrary: Codeunit "MyLibrary";
        Duration: Decimal;
        Weight: Decimal;
        DurationText: Text;
        WeightText: Text;
    begin
        if MyRequest.FindNode('DURATION', DurationText) then begin
            MyLibrary.EvaluateDecimal(Duration, DurationText)
        end;

        if MyRequest.FindNode('WEIGHT', WeightText) then begin
            MyLibrary.EvaluateDecimal(Weight, WeightText);
        end;
    end;

}
```
