### ISSUE TITLE
PermissionSet wizard - PermissionSet name length cannot be longer than 20 characters

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#301]
Change max length of name field, add Caption property to the wizard

**Comment by rvanbekkum** [comment]
Was just thinking about this once again, but just noticed you already logged this yourself. 😊

Also logged this as an idea for a code analyzer rule: https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/101
It might not be that difficult to implement, so I might do that myself when I have some spare time to do that.

Maybe you could also set a maximum length for the Caption? (i.e., 30 characters) Perhaps even add the Caption property with `, MaxLength = 30`. 😁

**Comment by anzwdev** [comment]
New version of extension has been released. It will not allow to create permissionsets with names longer than 20 characters and captions longer than 30.
