### ISSUE TITLE
[Feature Request] AutoSort Permissions onSave

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#303]
I really like the code action to sort the permissions in the new format.
Right now there is no setting to auto-sort the permission, or have I missed some setting for this action?

**Comment by anzwdev** [comment]
You can use "SortPermissions" and "SortPermissionSetList" values with "alOutline.codeActionsOnSave" setting.

**Comment by pri-kise** [comment]
Ah thanks, my fault. I could have pressed Ctrl+Space inside the settings.json.
