### ISSUE TITLE
Add MaxLength/Locked property to Caption when Permission Set is created

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#306]
Hi @anzwdev,
It might be nice to add `MaxLength = 30` (_or_ `Locked = true`) to the `Caption` property when Permission Set objects are created with the file wizard.
This is to ensure that the caption never exceeds 30 characters, also not in its potential translations.

**Comment by anzwdev** [comment]
Hi

Thank you for the idea. I've added MaxLength property to the caption label, but I am not sure if I should add Locked one. I've checked captions of Microsoft permission sets and they are not locked.
