### ISSUE TITLE
Allow the Syntax Visualizer sash to be moved further

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#307]
![Syntax Visualizer Sash](https://user-images.githubusercontent.com/1273387/147401049-0702fa82-111c-4b66-93a7-71556edab3d2.gif)

The sash (=splitter) that separates the Syntax Tree and the Properties subpanes can only be moved by a few pixels, making it harder to view all the relevant information.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this issue. I've fixed it and released a new version of the extension.
