### ISSUE TITLE
If possible, only show context menu items when relevant

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#308]
<img width="701" alt="UncommonSense AL Utils2021-12-28 at 06 45 33" src="https://user-images.githubusercontent.com/1273387/147532437-7842405a-509a-4bc6-b4f0-031e84c383ab.png">

It would be cleaner/less confusing if the `New AL File Wizard` menu item would only show up in AL projects, not in e.g. C# projects. Thank you for considering my suggestion!

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this issue. Extension now will display this menu item only if it has been activated. It will be activated when current folder contains app.json or al file is edited. It will also be activated when "AL Outline" panel is visible and expanded, so there is still a posibility that menu item will be available for other project types, but unfortunately that's all that I can do. To avoid it, you can hide "AL Outline" panel in your VS Code.
