### ISSUE TITLE
Code action "Add multiple fields": Don't always surround with quotes

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#31]
Hi @anzwdev,

First off, I think the _Code action_ "Add multiple fields" is a very useful addition.
There is one thing with it that I don't like, which is the following:

It always surrounds the control name and source expr. with quotes `"`, even when not necessary. For our own table fields we always use names that don't contain any 'weird' characters (i.e., only those in set [A-Za-z0-9_]), so we never add quotes for those.
![image](https://user-images.githubusercontent.com/7383241/58326438-1c018300-7e2d-11e9-8bc3-1c7d94a084af.png)
Is there something that you could change in this?

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

I agree with you, it will look better without quotes, I will fix it.

**Comment by anzwdev** [comment]
I've fixed it and uploaded new version of the extension to the Visual Studio Marketplace
