### ISSUE TITLE
SortProperties fails in case of extra semicolon

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#310]
Given the sample file below ...

```
table 2060355 "NVT My Tabel"
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "Code"; Code[50])
        {
            DataClassification = CustomerContent;
            Caption = 'Code', Locked = true;
            ;
            Access = Internal;
        }
    }

    keys
    {
        key(Key1; Code)
        {
            Clustered = true;
        }
    }
}
```

... which seems to contain an extra semicolon in the property list.

```
Caption = 'Code', Locked = true;
            ;
```

The app packages without any AL compiler issues, but running the **SortProperties** command on this file fails with error below:

![image](https://user-images.githubusercontent.com/25268332/148045979-474db760-3630-446e-a3f2-9f390621e3cd.png)

**Expected resolution**
Ideally the extra semicolon should be removed when sorting properties.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this issue, I've fixed it and released a new version of the extension.
