### ISSUE TITLE
RemoveUnusedVariables - Specify default parameters

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#311]
To ease / automate the new **'Run Code Cleanup'** command, we want to remove as much doubt from the developer, by storing all required input in the settings.json file. When **RemoveUnusedVariables**  is used, we still get an option list to select the variables to remove. If possible, we'd like to store the choice in a setting, so the user does not need to (de)select the options.

![image](https://user-images.githubusercontent.com/25268332/148046884-841c0959-d3ee-4ba6-b974-91b2f7248a9b.png)

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this problem. I've changed the logic in the extension, you can now specify settings for the commands that are run by the code cleanup in the settings. If they are provided, code cleanup will no longer ask for these parameters, but if you run each of these comand separately, you will still be asked for them. You can use these settings:

* `alOutline.defaultAppArea`: default application area
* `alOutline.defaultDataClassification`: default DataClassification value
* `alOutline.defaultAddPageFieldCaptionsSettings` default settings for the AddPageFieldCaption command when run by the Code Cleanup, these properties can be set:
  * `setActionsCaptions`: set action captions
  * `setActionGroupsCaptions`: set action groups captions
  * `setGroupsCaptions`: set groups captions
  * `setPartsCaptions`: set parts captions
  * `setFieldsCaptions`: set fields captions
  * `setLabelsCaptions`: set labels captions
* `alOutline.defaultRemoveUnusedVariablesSettings`: default settings for the RemoveUnusedVariables command when run by the Code Cleanup, these properties can be set:
  * `removeGlobalVariables`: remove global variables
  * `removeLocalVariables`: remove local variables
  * `removeLocalMethodParameters`: remove local methods parameters
* `alOutline.reuseToolTipsFromDependencies`: reuse tooltips only defined in these dependencies, if empty, all dependencies will be used. Each entry should be defined as "dependency publisher" + "space" + "-" + "space" + "dependency name". You can also use "*" to use all dependencies and make sure that code cleanup won't ask for these values.

**Comment by fvet** [comment]
Works like a charm, thanks a lot!
