### ISSUE TITLE
[Question] Run Code Cleanup - Folder settings vs workspace settings

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#312]
Most of our repo's consist of 2 folders : `App` and `Src`, containing the parent app and it's test app.
These folders are grouped via a **workspace** file, containing some common settings.

However, sometimes the developer does not open the workspace and immediately opens the `App` folder instead.

This makes it difficult to decide on which level settings are to be stored. Whenever possible, we try to add the settings on **folder** level (.vscode\settings.json) to avoid maintaining similar settings twice / on workspace level.

In the below case, no settings had been added on workspace level, but **only** on the `App` folder level. (we are less strict on the `Test` app) When opening the **workspace** and running **'Run Code Cleanup'**, the action fails, due to missing settings on workspace level. Is it required to store settings at both levels, or can the command look to the **folder** level if no settings are found on **workspace** level?

![image](https://user-images.githubusercontent.com/25268332/148049164-a10ff0f5-d958-41b8-b6c0-1bc364ed1960.png)

![image](https://user-images.githubusercontent.com/25268332/148049232-e7bf5cb9-27b7-4e00-ab32-f07d32223970.png)

**Comment by anzwdev** [comment]
My extension uses vs code configuration api functions with current file or workspace folder path, so it should take the values from settings.json in .vscode folder. I've updated the extension manifest json file to make sure that all settings scope is "resource", I hope that it will help you.
