### ISSUE TITLE
Action Images Browser: Tiles

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#314]
Hi @anzwdev,
Not a high prio, but might be nice for completeness: Support for the Tile images that can be added via `cuegroup` actions:

![image](https://user-images.githubusercontent.com/7383241/148415702-f8ddc539-0de8-42d0-9aa7-82624fd0d7da.png)

Currently, these do not show up in the Action Images Browser.

**Comment by anzwdev** [comment]
Hi @rvanbekkum

Thank you for reporting this idea. I've added 3 new commands and released a new version of the extension:
- "AZ AL Dev Tools: Show CueGroup Action Images"
- "AZ AL Dev Tools: Show CueGroup Fields Images"
- "AZ AL Dev Tools: Show Role Center Action Images"
