### ISSUE TITLE
AZ AL Dev Tools: Fix Identifiers and Keywords Case in the Active Project unquotes identifiers in code that look like keywords

### ISSUE THREAD

**Issue by ernestasjuska** [anzwdev/al-code-outline#318]
Hi,

AZ AL Dev Tools: Fix Identifiers and Keywords Case in the Active Project unquotes identifiers in code that look like keywords.

This

```al
codeunit 50100 "Example In"
{
    local procedure Example1() Result: Enum "My Enum"
    begin
        Result := "My Enum"::"In";
    end;

    local procedure Example2() Result: Code[10]
    var
        MyTable: Record "My Table";
    begin
        Result := MyTable."In";
    end;

    local procedure Example3() Result: Integer
    begin
        Result := "In"();
    end;

    local procedure In(): Integer
    begin
    end;
}
```

becomes

```al
codeunit 50100 "Example In"
{
    local procedure Example1() Result: Enum "My Enum"
    begin
        Result := "My Enum"::In; // casing correct but AL language parser expects "in" expression (Value in [...])
    end;

    local procedure Example2() Result: Code[10]
    var
        MyTable: Record "My Table";
    begin
        Result := MyTable.In; // casing correct but AL language parser expects "in" expression (Value in [...])
    end;

    local procedure Example3() Result: Integer
    begin
        Result := In(); // casing correct but AL language parser expects "in" expression (Value in [...])
    end;

    local procedure In(): Integer
    begin
    end;
}
```

I also tried this with "then" and "for" keywords and got similar results.

The identifiers in declarations don't need to be quoted - so procedure name In works fine in most cases (procedure name Procedure must be quoted, but Local does not).

I think it should not unquote anything that looks like a keyword but it should still update casing.

Thanks.

-----

Code for examples:

```al
enum 50100 "My Enum"
{
    value(1; In)
    {
    }
    value(2; Then)
    {
    }
    value(3; For)
    {
    }
}

table 50100 "My Table"
{
    fields
    {
        field(1; In; Code[10])
        {
        }
        field(2; Then; Code[10])
        {
        }
        field(3; For; Code[10])
        {
        }
    }
}
```

Images:

![image](https://user-images.githubusercontent.com/53167314/149763849-a5bea62a-c198-40ab-939b-12fd7c6d583d.png)
![image](https://user-images.githubusercontent.com/53167314/149763896-e073cd9b-04eb-4d01-a287-ceeefee09337.png)
![image](https://user-images.githubusercontent.com/53167314/149763970-06ef1e56-f563-4eb6-856f-be53799f90e0.png)

**Comment by epernst** [comment]
Not sure if its related, but it seems that since that last week or so, that this function is not doing anything anymore.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this issue. I've released a new version of the extension, it should leave quotes around identifiers that look like keywords inside code.

**Comment by anzwdev** [comment]
Hi @JavierFuentes 

Thank you for reporting this problem. It has also been reported in the issue #338. I've fixed it, update will be included in the next extension release.

**Comment by JavierFuentes** [comment]
What if a configuration were added that indicated words or text strings that should NOT be modified and should be SKIPPED with this automatic action?

In this way, all those words or text strings would be systematically omitted by this action and each of us could find the configuration that best fits what we need in each project...

**Comment by anzwdev** [comment]
I am not sure if another setting is a good idea, it will only make it more complex. There are just 2 problems here with identifiers that look like keywords and are not inside quotes:
- they are displayed using incorrect color in vs code 
- in some cases al parser has problems with parsing code
So it seems that the best option here will be to leave quotes for this type of identifiers.

I've implemented this logic in the extension and released a new version.

**Comment by ernestasjuska** [comment]
It works now. Thanks. 👍
