### ISSUE TITLE
[Enhancement] Show Code Analyzer Rules: Select all by default

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#321]
Hi @anzwdev,
I think it would be better to have all code analyzers selected by default. Is that something you agree with or is there any reason you are not enabling all with the command by default?

![image](https://user-images.githubusercontent.com/7383241/150318616-c3f7659d-f189-4622-9e8f-1a570ad0ff87.png)

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

My idea was to select these analyzers that developers selected in "al.codeAnalyzers" settings so by default they only see the list of warnings that can be reported for their current project. I am not sure if it is the right idea, I believe that trhe default behaviour should be the one that is used the most. If developers are using this function usually to check which warnings are active in the current project, I would leave it as it it, but if in most of the cases they are going there to check which other warnings from other inactive code analyzers would be good to enable, then I can make all of these analyzers selected by default.

How are you using this viewer?

**Comment by rvanbekkum** [comment]
I think if it is intended to show only the rules for the active code analyzers, then that is not what it currently does, and I think "Compiler" should be included then as well.

Typically, I do not really care about what is active for the current project, considering this view also doesn't 'do' anything that concerns the project, e.g., use the rulesets that might change severity.
I typically use it to look up rules, view their default severity and maybe even create a rule for them (although that is rare, because the severity of the rules will be made final by the same ruleset.json used for all our build pipelines 😊).
I would opt for enabling everything when opening the view, because I think that would be the most convenient for everyone (search and find all rules that are _*available*_), and when you want to restrict your search you can still change the filtering when you need to.

With that in mind, it might even be nice to have support for searching in custom code analyzers (e.g. the BcLinterCop). But that's yet another feature request. 😅

**Comment by anzwdev** [comment]
OK, I will turn all of them on by default. Custom analyzers support has already been there, but it was expecting full path instead of "${analyzerFolder}" placeholder. I've fixed that, it will be included in the next release.

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extension, it now selects all code analyzers, it can alo show diagnostics from custom code analyzers when they are specified using "${analyzerFolder}....." in the settings.
