### ISSUE TITLE
Use command with preLaunchTask

### ISSUE THREAD

**Issue by deadmouse** [anzwdev/al-code-outline#323]
I am trying to run command _Run Code Cleanup on the Active Project_ before publishing from VSCode and an error appears saying:

_One or more of actions failed: Remove With: error - Object reference not set to an instance of an object., Fix Identifiers Case: error - Object reference not set to an instance of an object., Add Parentheses: error - Object reference not set to an instance of an object., Remove Unused Variables: error - Object reference not set to an instance of an object.,_ 

This is my **tasks.json**:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "BeforePublishing",
            "command": "${command:azALDevTools.RunEditorCodeCleanup}",
        }
    ]
}
```

Can this be implemented?

**Comment by anzwdev** [comment]
Hi

There are 2 problems here:
1. As I can see you are running command that changes current editor only, you should be using "azALDevTools.RunWorkspaceCodeCleanup" instead on "azALDevTools.RunEditorCodeCleanup"
2. There was a bug in the commands processing current documents and it was crashing when they were run for non-al documents. You probably had "tasks.json" opened when you were running the task and it was trying to transform that json. I've fixed it and it will be included in the next release.

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extension, it will no longer crash when code transformation command is run against unsupported file.
