### ISSUE TITLE
Sort variables not working with Labels and add a new way of exclude entire files of automations

### ISSUE THREAD

**Issue by JavierFuentes** [anzwdev/al-code-outline#325]
Hi,
I've noticed that when I use `"alOutline.codeCleanupActions": [ "SortVariables" ]` all seems to work ok, **except with Labels**...

As an example, I have made a custom copy of the standard Report "Combine Shipments"...

First of all, 
**I would like to have a way of exclude some files (like this that is a copy of standard with a few custom changes for my project) of `Run Code Cleanup on the Active Project` action...** 

¿Adding a pragma at the first line of the file or something like that could be a solution?

The reason is that it will be more easy to compare my custom version with future standard changes if I don't apply automatic changes.

The wrong result in automatic reordering with Labels is this:

```al
        NoOfskippedShiment: Integer;
        Text001Lbl: Label 'Introduzca la fecha del documento.';
        Text000Lbl: Label 'Introduzca la fecha de registro.';
        Text010Lbl: Label 'Los albaranes ahora están procesados y el número de facturas creadas es %1.', Comment = '%1=-';
        Text011Lbl: Label 'Los albaranes ahora están procesados y el número de facturas creadas es %1.\%2 Los albaranes y clientes que no cumplen las condiciones no se han procesado.', Comment = '%1-Nº de facturas,%2-Nº de albaranes';
        Text005Lbl: Label 'Nº Albarán    #3##########', Comment = '%3=-';
        Text003Lbl: Label 'Nº Cliente    #1##########\', Comment = '%1=-';
        Text008Lbl: Label 'No hay nada que procesar.';
        Text004Lbl: Label 'Nº Pedido     #2##########\', Comment = '%2=-';
        NotAllInvoicesCreatedMsg: Label 'No se crearon todas las facturas. No se creó un total de %1 facturas.', Comment = '%1=-';
        Text007Lbl: Label 'No se registraron todas las facturas. No se registró un total de %1 facturas.', Comment = '%1=-';
        Text002Lbl: Label 'Procesando albaranes...\\';
```

The expected reordering result should be this:

```al
        NoOfskippedShiment: Integer;
        NotAllInvoicesCreatedMsg: Label 'No se crearon todas las facturas. No se creó un total de %1 facturas.', Comment = '%1=-';
        Text000Lbl: Label 'Introduzca la fecha de registro.';
        Text001Lbl: Label 'Introduzca la fecha del documento.';
        Text002Lbl: Label 'Procesando albaranes...\\';
        Text003Lbl: Label 'Nº Cliente    #1##########\', Comment = '%1=-';
        Text004Lbl: Label 'Nº Pedido     #2##########\', Comment = '%2=-';
        Text005Lbl: Label 'Nº Albarán    #3##########', Comment = '%3=-';
        Text007Lbl: Label 'No se registraron todas las facturas. No se registró un total de %1 facturas.', Comment = '%1=-';
        Text008Lbl: Label 'No hay nada que procesar.';
        Text010Lbl: Label 'Los albaranes ahora están procesados y el número de facturas creadas es %1.', Comment = '%1=-';
        Text011Lbl: Label 'Los albaranes ahora están procesados y el número de facturas creadas es %1.\%2 Los albaranes y clientes que no cumplen las condiciones no se han procesado.', Comment = '%1-Nº de facturas,%2-Nº de albaranes';
```

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this issue. I've decided to split it into 2 to be able to track separately labels sorting bug and code cleanup command enhancements.

I've fixed the label sorting bug, it will be included in the next release.

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extensions, both your issues are fixed/implemented. Labels sorting bug should be fixed, you can also specify list of files/file name patterns that should be ignored by project/uncommited files code transformation commands by adding them to the `alOutline.codeTransformationIgnoreFiles` setting.

**Comment by JavierFuentes** [comment]
Thanks a lot, @anzwdev ,
I'm looking forward to trying it.
