### ISSUE TITLE
Avoid add automatic Caption when a table field has a dynamic CaptionClass defined

### ISSUE THREAD

**Issue by JavierFuentes** [anzwdev/al-code-outline#326]
I have some table fields in my project that have **dynamic CaptionClass** defined.

When I "Run Code Cleanup on the Active Project" the tool adds a Caption to this fields needlessly.

**Comment by anzwdev** [comment]
Hi

If you check standard BC objects, you will see that Microsoft is adding captions to all fields, even these with dynamic captions and my "add captions" commands are doing the same. You shold also remember, that there are places in the system, where dynamic captions don't work. All solutions that allow users to select source table and fields for some calculations/reporting/integrations by showing them list of fields from Fields table don't show dynamic captions. You can check it by opening "Fields Lookup" page

![FieldsLookup](https://user-images.githubusercontent.com/24944969/153665430-0d0e0ec1-780f-4f85-9827-03da556f37e4.png)

or by running this code:

```pascal
procedure ShowFieldCaptions()
var
    Fld: Record Field;
    GLEntry: Record "G/L Entry";
    RecRef: RecordRef;
    FldRef: FieldRef;
begin
    RecRef.Open(DATABASE::"G/L Entry");
    FldRef := RecRef.Field(GLEntry.FieldNo("Global Dimension 1 Code"));
    Fld.Get(Database::"G/L Entry", GLEntry.FieldNo("Global Dimension 1 Code"));
    Message(
        'Caption from record: ' + GLEntry.FieldCaption("Global Dimension 1 Code") + '\' +
        'Caption from field table: ' + Fld."Field Caption" + '\' +
        'Caption from FieldRef: ' + FldRef.Caption);
end;
```

![FieldCaptionTests](https://user-images.githubusercontent.com/24944969/153665456-00afa127-25bf-471c-9878-697a2d59b096.png)

**Comment by JavierFuentes** [comment]
OK, you're right... 

I had only taken into account the warnings of the Cops that stop showing when you have already defined the CaptionClass.
