### ISSUE TITLE
Use different icons in AL Outline panel

### ISSUE THREAD

**Issue by JavierFuentes** [anzwdev/al-code-outline#327]
Would it be possible to differentiate the following with different icons?

- procedures: global VS local VS internal VS protected

- variables: global VS protected

- fields in tables/tableExt: editable VS non-editable, enabled VS non-enabled

- fields in pages/reports, etc: visible VS non-visible, editable VS non-editable, enabled VS non-enabled

**Comment by anzwdev** [comment]
I've added a few more icons to the panel, I hope that it will work better for you now. 
- procedures: global VS local VS internal VS protected
- variables: global VS protected
- fields in tables/tableExt: enabled VS non-enabled

I haven't implemented different icons for page fields as it would require running more logic to access source table information and I am afraid that it could have negative impact on performance.

Field editable/non-editable icons are also not, I need to do a few experiments to check if it is possible to mix enabled/disabled/obsolete information with editable/non-editable in a way that the icon which is already very small, is till readable.
