### ISSUE TITLE
Allow to exclude some of the files from workspace code transformation commands (moved from #325)

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#330]
This was originally part of the issue #325, but I've decided to move it it here as the original one contained 2 requests where one was a bug and the second one an enhancement. That's the original request from @JavierFuentes:

>I would like to have a way of exclude some files (like this that is a copy of standard with a few custom changes for my project) of Run Code Cleanup on the Active Project action...

**Comment by anzwdev** [comment]
I've released a new version of the extension, it is now possible to define list of files/file name patterns to exclude from code tranformation commands when they are run against whole project or uncommitted files. To do it, these patterns have to be entered into `alOutline.codeTransformationIgnoreFiles` setting.

**Comment by JavierFuentes** [comment]
Thanks a lot,
I'm looking forward to trying it...

Just to tell you that initially I was thinking of a #pragma type statement at the beginning of each file individually that omits all that file from both manual and automatic execution for the entire project...

For the AL compiler we can put this at the beginning of a specific file (any copy of the standard that doesn't allow its own rules) to disable ALL Cops:
```c#
#pragma warning disable
```

In our case, it could have been a syntax like something like this:
```Perl
/* #pragma alOutline.codeTransformation disable */
```

But I understand that this solution would be more intrusive.

**Comment by anzwdev** [comment]
Yes, solution with "pragma" comment would be more intrusinve. It would also be a problem for people that copy filtes into the solution from other source, don't want to change them all and want to refresh them from the source when it is needed.

Keeping these rules in the settings seems to be a good option as you can always store them in the settings.json file in the .vscode folder in your project.

**Comment by DavidFeldhoff** [comment]
> I've released a new version of the extension, it is now possible to define list of files/file name patterns to exclude from code tranformation commands when they are run against whole project or uncommitted files. To do it, these patterns have to be entered into `alOutline.codeTransformationIgnoreFiles` setting.

Hi Andrzej, do we have to specify each file or are we also allowed to use wildcards (e.g. to specify a whole folder) in that new setting?
