### ISSUE TITLE
No Tooltips for ShowCaption = false

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#332]
I really often use the feature to add tooltips to the page, but in my opinion no tooltips should be added to field controls with the property `ShowCaption = false`.
As far as I can see, the tooltip wouldn't be shown anyway.

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've just checked and you are correct, missing property (AA0218) code analyzer warning is not generated if ShowCaption property of a page control is set to false.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it will no longer create tooltips if ShowCaption property of the field is set to false
