### ISSUE TITLE
Fix Identifiers not working anymore?

### ISSUE THREAD

**Issue by epernst** [anzwdev/al-code-outline#335]
As of the last couple of months I have had problems getting the Fix Identifiers to work.
Fixing keywords works fine, but taking this code:

```
    BEGIN
        CurrencyExchangeRate.RESET();
        CurrencyExchangeRate.SETRANGE("Currency Code", CUrrencyCODE);
        CurrencyExchangeRate.SETRANGE("Starting Date", 0D, Date);
        IF NOT CurrencyExchangeRate.FINDLAST() THEN
            CLEAR(CurrencyExchangeRate);

        EXIT(CurrencyExchangeRate."Starting Date");
    END;

```
 becomes
```
    begin
        CurrencyExchangeRate.RESET();
        CurrencyExchangeRate.SETRANGE("Currency Code", CurrencyCode);
        CurrencyExchangeRate.SETRANGE("Starting Date", 0D, Date);
        if not CurrencyExchangeRate.FINDLAST() then
            CLEAR(CurrencyExchangeRate);

        exit(CurrencyExchangeRate."Starting Date");
    end;

```

I'm on v.3.0.27 - AL 8.3.570094 (runtime target 3.2)

**Comment by anzwdev** [comment]
Hi 

I tried to run "Fix Identifiers and Keywords Case in the Active Editor" command on a file with your code and it worked without any problems for me. Do you still have this issue? If it does not work, could you run "Open AZ AL Dev Tools log file" command and check if you can see any errors?

**Comment by epernst** [comment]
Yes, still have the problem. The log file is empty (except for some older unrelated issues). 

It's not just me who has this problem, all the other developers in my team also have it. So is it because we are on v. 14.29?
Does it work for you with target=3.2 in app.json?

**Comment by epernst** [comment]
Have the same problem with a BC version 15 (target=4.0) app. :(

**Comment by epernst** [comment]
Don't know what you have done, but with the latest version (3.0.34) we no longer have this issue! 
Everything (that I know of) now works perfectly!👍
