### ISSUE TITLE
Not able to find simbols using `packageCachePath` setting

### ISSUE THREAD

**Issue by vody** [anzwdev/al-code-outline#336]
When we are trying to use an object wizard in a multi-app workspace created as by a [Microsoft guide](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-multiroot-workspaces), we need to move `.alpackages` folder to an AL project folder as an object wizard cannot find reference symbols.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this problem. It has already been reported in the issue #305, I will be fixing it soon.

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've fixed and and released a new version of the extension.
