### ISSUE TITLE
"resourceExposurePolicy" is not interpreted properly

### ISSUE THREAD

**Issue by aobsgit** [anzwdev/al-code-outline#337]
Hi.

When browsing objects trough an .app file in .alpackages floder, there is an error that "ShowMyCode" is not set, which in our case is correct since we use resourceExposurePolicy, as ShowMyCode is obsoleted.

Thank you

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've fixed and and released a new version of the extension.
