### ISSUE TITLE
Fix Identifiers and Keywords leads to uncompilable report

### ISSUE THREAD

**Issue by dschulzeOS** [anzwdev/al-code-outline#338]
I used the following command.
![image](https://user-images.githubusercontent.com/99893942/154641454-14d74272-93fe-4063-a427-31b61b0c538e.png)

It has corrected a lot of carelessness errors in an incredible number of places. Thanks for that.

However, on one report of my project it leads to uncompilability.

Another developer in our project called fields of a table code and sorting. (Please don't tell me that you shouldn't use these keywords. ;) )

Anyway, your command corrects the whole thing (correct at first sight) as follows:

![image](https://user-images.githubusercontent.com/99893942/154642192-5973e5e7-5623-4278-a040-1f96d17f110f.png)

Now i am getting the following AL error:
![image](https://user-images.githubusercontent.com/99893942/154642332-0d34e843-b99f-4cbf-bb50-a029032a0085.png)

Is it not allowed to remove the " here for some reason?
If yes, then the tool should not remove them.

If it is a bug on my side, I am happy to receive hints.
For now, I have corrected back the "unnecessary" ".

**Comment by anzwdev** [comment]
Thank you for reporting this problem. I've modified and released a new version of the extension. It no longer removes quotes around identifiers that look like keywords.

**Comment by dschulzeOS** [comment]
Thanks, that's great to hear. Keep it up.
