### ISSUE TITLE
Fix Identifiers and Keywords fails with the latest release

### ISSUE THREAD

**Issue by ChrisKappe** [anzwdev/al-code-outline#344]
Since today I get the following error:

Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReferenceSpecification> Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.ProjectManifest.GetAllReferences()'.

![image](https://user-images.githubusercontent.com/72206383/155679856-de5c3abd-e2e3-460c-b432-9a44a605b953.png)

**Comment by ChrisKappe** [comment]
I investigated a little bit further. Seems this is similar to #331 .
Only difference is, that I still run the v8.xx version.

Could fix it for now. With AL v8.3.570094 it works. In AL v8.4.586670 it is broken

**Comment by lvanvugt** [comment]
@ChrisKappe thanx for the workaround. Saved my day as I was running into the same.

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've recompiled and released a new version of the extension, problem should be solved now.
