### ISSUE TITLE
"Add all extension objects permissions" - Skip tables with ObsoleteState = Removed?

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#345]
Hi @anzwdev,

Do you think it would make sense for code action "Add all extension objects permissions" to skip table objects with `ObsoleteState = Removed`?

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

Yes, it makes sense, I'll add it

**Comment by anzwdev** [comment]
Hi

I've released a new version, removed tables will no longer be added to the list or permnissions.
