### ISSUE TITLE
[Suggestion] Cleanup empty lines/sections

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#347]
I really love the various cleanup rules that improve the code reading and enforce uniform code layout. However, during code review, we often find ourselves doing some minor cleanup of redundant code, that could be automated by some additional 'Cleanup Actions'

----

- [ ] 1. Remove duplicate empty lines

In case a new line is followed by another new line, all extra new lines (except the first) could be removed / truncated. (see lines between field1 / field2)

Exception: if the new line is followed by a section end ( `{` or `end`) on could argue to remove the new line completely. (see lines within field2 section)

**BAD CODE**
```

        field(1; "Primary Key"; Code[10])
        {
            Caption = 'Primary Key';
            DataClassification = CustomerContent;
            NotBlank = false;
        }



        field(2; "Base URL"; Text[250])
        {
            Caption = 'Base URL', comment = 'NLB="Basis URL",FRB="URL Base"';
            DataClassification = CustomerContent;


        }
```
GOOD CODE

```
        field(1; "Primary Key"; Code[10])
        {
            Caption = 'Primary Key';
            DataClassification = CustomerContent;
            NotBlank = false;
        }

        field(2; "Base URL"; Text[250])
        {
            Caption = 'Base URL', comment = 'NLB="Basis URL",FRB="URL Base"';
            DataClassification = CustomerContent;
        }
```

Also remove empty lines between end of section markers ( `}` )

**BAD CODE**
```
            }

        }

    }
```

**GOODCODE**
```
            }
        }
    }
```

Also see https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/174

---

- [ ] 2. Remove empty sections

By making use of various snippets, we are often left with 'empty' sections. These sections can be completely removed (as long as they contain no childs / code).

With sections, I refer to `fields`, `keys`, `fieldsgroups`, `layout`, `actions` ... (carrying no identifier)

**BAD CODE**
 
Table

```
    fields
    {
        
    }

    keys{    }

    fieldgroups
    {}
```

Page

```
    layout
    {
        
    }

    actions
    {
        
    }
```

**GOOD CODE**

```
```

**Comment by jwikman** [comment]
I really like this idea @fvet! But I would actually not want any empty lines at all between two fields... 


So I would prefer this
```
        field(1; "Primary Key"; Code[10])
        {
            Caption = 'Primary Key';
            DataClassification = CustomerContent;
            NotBlank = false;
        }



        field(2; "Base URL"; Text[250])
        {
            Caption = 'Base URL', comment = 'NLB="Basis URL",FRB="URL Base"';
            DataClassification = CustomerContent;


        }
```
to be this
```
        field(1; "Primary Key"; Code[10])
        {
            Caption = 'Primary Key';
            DataClassification = CustomerContent;
            NotBlank = false;
        }
        field(2; "Base URL"; Text[250])
        {
            Caption = 'Base URL', comment = 'NLB="Basis URL",FRB="URL Base"';
            DataClassification = CustomerContent;
        }
```

But maybe that is just me..? 
Maybe this is the challenge with these kind of features, a lot of this code cleaning is a matter of preferences...

I'm using [Prettier](https://prettier.io/) when working with MarkDown and TypeScript and really like the cleanness that it produces - maybe someone should give it a go and create an [AL Plugin for Prettier](https://prettier.io/docs/en/plugins.html)? 😁

**Comment by fvet** [comment]
@jwikman I in fact am in favour to remove the extra lines between the fields as well. Didn't want to go in detail on that part yet, since in some other cases (e.g. between procedures, regions, code, ...) I want to keep the empty line.

**BAD CODE**

```
   #region Unit Calculator
    internal procedure ShowUnitCalculator()
    begin
        Codeline1;
        Codeline2;


        Codeline3;
        Codeline4;

    end;


    internal procedure ShowUnitCalculator2()
    begin
    end;
    #endregion


    #region Unit Class
    internal procedure CreateItemUnitOfMeasureFromUnitClass()
    begin
    end;
    #endregion
```

**GOOD CODE**

```
    #region Unit Calculator
    internal procedure ShowUnitCalculator()
    begin
        Codeline1;
        Codeline2;

        Codeline3;
        Codeline4;
    end;

    internal procedure ShowUnitCalculator2()
    begin
    end;
    #endregion

    #region Unit Class
    internal procedure CreateItemUnitOfMeasureFromUnitClass()
    begin
    end;
    #endregion
```

**Comment by anzwdev** [comment]
That's a good idea, I'll add it.

**Comment by anzwdev** [comment]
I've released a new version of the extension, there are 2 new sets of commands that you can use:
- "Remove Empty Lines from the Active Editor"
- "Remove Empty Lines from the Active Project"
and
- "Remove Empty Sections from the Active Editor"
- "Remove Empty Sections from the Active Project"

You can also use these commands with code cleanup using these 2 new additional "alOutline.codeCleanupActions" setting values:
- "RemoveEmptyLines", 
- "RemoveEmptySections"

**Comment by fvet** [comment]
Will implement this right away. 
Thanks for adding this new feature!

**Comment by mjmatthiesen** [comment]
Old issue I know, but is it possible to call these from OnSave the way props etc can be sorted?
