### ISSUE TITLE
Sort the Record variables by VarName, not by TableName

### ISSUE THREAD

**Issue by JavierFuentes** [anzwdev/al-code-outline#352]
Hi,
nowadays, the sorting order of type Record variables seems to be setted by its TableName.

When you use prefixes for custom tables and you apply the MS naming conventions, the resulting order is not the expected.

You can see this example:
![image](https://user-images.githubusercontent.com/5801847/160610717-2223ada2-edd7-4c89-ab2c-1a2aaef3ca7e.png)

(I've not tested this issue with variables of other Object types like Pages, Reports, etc)

I hope you can fix this use case.

**Comment by guidorobben** [comment]
Hi, There is code rule that makes the order mandatory. https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0021

I also would like a change to the order of the Field properties on Pages. The tool now adds the Tooltip first and then the ApplicationArea. But we add the in A..Z order. Is it possible to change this or add an setting for this?

**Comment by JavierFuentes** [comment]
Hi @guidorobben ,
I think there is no written rule for **the order within** a variable Type:

> The order is: Record, Report, Codeunit, XmlPort, Page, Query, Notification, BigText, DateFormula, RecordId, RecordRef, FieldRef, and FilterPageBuilder. The rest of the variables are not sorted.

This tool sorts all `simple variable types` alphabetically... I just expect the same with `complex variable types`, which is also valid when using prefixes to name objects (but not variables) to keep CodeCops happy.

**Comment by anzwdev** [comment]
Currently when variables are sorted by type, whole type name including object name is used. I will add a setting to turn it off and use only objec type name for complex types.

@guidorobben, you can use "Sort properties" command to sort properties in the current editor or in all files in the project. You can also add "sortProperties" to the "alOutline.codeActionsOnSave" setting to run sorting when you save the file.

**Comment by anzwdev** [comment]
I've released a new version of the extension, you can now user "alOutline.variablesSortMode" setting to decide how do you want to sort variables. There are two options:
- "fullTypeName" - whole data type including object name is used (i.e. "Record Vendor")
- "mainTypeNameOnly"- only main part of the type will be user (i.e. "Record")

The default value is "fullTypeName" so it works the same way as before this change has been added.

**Comment by JavierFuentes** [comment]
Hi @anzwdev ,
seems this new feature works whith the action "Run Code Cleanup in the Active Project" and with "Run Code Cleanup in the Active Project" action but it doesn't work when you are simply Saving a file after modification or creation...

My `settings.json` file has this settings now:
```json
{
    "editor.formatOnSave": false,
    "editor.codeActionsOnSave": {
        "source.fixAll": false
    },

    "alOutline.docCommentsType": "none",
    "alOutline.enableCodeCopFixes": false,
    "alOutline.fixCodeCopMissingParenthesesOnSave": true,
    "alOutline.useTableFieldDescriptionAsToolTip": true,
    "alOutline.addToolTipsToPageFields": true,
    "alOutline.pageFieldToolTip": "Especifica el valor del campo %1.",
    "alOutline.pageActionToolTip": "Ejecuta la acción %1.",
    "alOutline.defaultDataClassification": "CustomerContent",
    "alOutline.defaultAppArea": "All",
    "alOutline.defaultListUsageCategory": "Lists",
    "alOutline.fieldsSelectionOrder": "selection order",
    "alOutline.fixCaseRemovesQuotesFromDataTypeIdentifiers": false,
    "alOutline.variablesSortMode": "mainTypeNameOnly",
    "alOutline.codeActionsOnSave" : [
        "SortProperties",
        "SortVariables",
        "SortPermissions",
        "SortPermissionSetList",
    ],
    "alOutline.codeCleanupActions": [
        "AddApplicationAreas",
        "AddDataClassifications",
        "AddMissingParentheses",
        "AddObjectCaptions",
        "AddTableFieldCaptions",
        "AddToolTips",
        "ConvertObjectIdsToNames",
        "FixKeywordsCase",
        "FixIdentifiersCase",
        "SortTableFields",
        "SortProperties",
        "SortVariables",
        "SortPermissions",
        "SortPermissionSetList",
        "FormatDocument",
        "TrimTrailingWhitespace",
    ]
}
```

As you can see `SortVariables` setting is activated for both actions...

Is this a Bug or can you help me to fix this settings?

**Comment by anzwdev** [comment]
Hi

Thank you for reporting your issue. I've fixed it and released a new version of the extension.
