### ISSUE TITLE
Go to definition (project file or server definition) does not work if object name contains a slash `/`

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#355]
Hi @anzwdev,

Found a small bug wit Go to definition:

If the object name contains a slash (`/`), e.g., `G/L Account`, the `Go to definition (project file or server definition)` command fails:

![image](https://user-images.githubusercontent.com/7383241/162445906-9c3d36c5-9b68-45fd-970e-a60da62901d7.png)

**Comment by domingosbarreto** [comment]
Just in time. I was going to report this now ☺️.
Not only slashes `/` but also parenthesis `(` or `)`.
![image](https://user-images.githubusercontent.com/83361918/162447284-cc59bda6-5059-413c-bb1a-a5359d119acd.png)
![image](https://user-images.githubusercontent.com/83361918/162447481-cc77d113-ac5b-41ef-ad08-487714575570.png)

**Comment by anzwdev** [comment]
I've fixed the issue and released a new version of the extension.

**Comment by rvanbekkum** [comment]
Nice. It seems to work now! 😁
