### ISSUE TITLE
Find duplicate code only in active workspace folder

### ISSUE THREAD

**Issue by jwikman** [anzwdev/al-code-outline#356]
The "Duplicate code" feature is very interesting!

But I would like the option to run this command on only the files in the current workspace folder.

Scenario:
I have a workspace with two root folders, `App` and `TestApp`
I want to check if there are any duplicate code inside only the `App` folder. It's not that uncommon that we need to duplicate code from the main app to the TestApp (or other folders), for different reasons.

I would also like to be able to run it as it is now, checking all files in all workspace root folders, but first I would like to check each folder to solve them separately.

**Comment by anzwdev** [comment]
I've released a new version of the extension. If current project has more than 1 workspace folder, `Find duplicate code` command will allow developer to select one of them or all.

**Comment by jwikman** [comment]
@anzwdev thanks, that was a great approach. It seems to work perfect! 👍
