### ISSUE TITLE
how to set refresh tree panel when i save code?

### ISSUE THREAD

**Issue by chenbimo** [anzwdev/al-code-outline#357]
It is always refresh tree panel when i input char.I want refresh when i save code.

**Comment by anzwdev** [comment]
Hi @chenbimo

Currently it is not possible, but I was thinking about this whole area long time ago and had some ideas about some changes. Unfortunately it is not so simple, there are more things happening in the background. Code is analyzed in the background not only for the panel, but also for other areas like code actions. There are also other vs code extensions created by other people that are using the result of this code analysis, so I have to be very careful with any changes. I've assigned "enhancement" label to this issue as I have some ideas about some improvements in this area.

**Comment by chenbimo** [comment]
okey，very thanks for your work!
