### ISSUE TITLE
Exclude API pages from "AddToolTips" ?

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#360]
On project level, I've the "AddToolTips" setting configured as "alOutline.codeCleanupActions"
When running the Cleanup for the active Project, all pages are processed and missing tooltips are added.

However, this is applied to API pages as well, which - to our opinion - do not require Tooltips (similar to how the APIv2 from the Base App is built and similar to the Wizard for API pages, where tooltips are not added either).

**Comment by anzwdev** [comment]
Thank you for reporting it, I'll modify the extension.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting your issue. I've fixed it and released a new version of the extension.
