### ISSUE TITLE
XmlPorts - Generate headers

### ISSUE THREAD

**Issue by 4dimit** [anzwdev/al-code-outline#363]
I've been wondering if it would be possible to somehow generate the headers for a CSV (`VariableText`)

So, we have our `fieldelement`s
```
fieldelement(DocumentType; SalesHeader."Document Type")
{
}
```

would it be possible to somehow generate a separate `tableelement` containing the headers and pre-assign them like the values below

```
textelement(DocumentTypeTitle)
{
    trigger OnBeforePassVariable()
    begin
        DocumentTypeTitle := SalesHeader.FieldCaption(SalesHeader."Document Type");
    end;
}
```
Currently doing a lot of Copy/Paste creating exports for Vendor, Customer, Sales Header/Line, tables that have a lot of fields.
Would save a ton hours of work :-)

**Comment by anzwdev** [comment]
Thank you for the idea. I've added a new `Generate column headers for CSV export` code action which is available on XmlPort header and XmlPort tableelement when XmlPort format is set to "VariableText".
