### ISSUE TITLE
Convert Object Ids to Names does not work for profile

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#365]
I tried to use the command `Convert Object Ids to Names` in a profile, but it reports that there is nothing to change.

My Example:
```al
profile "PROJECT MANAGER"
{
    Caption = 'Project Manager';
    ProfileDescription = 'Project Manager';
    RoleCenter = 9015;
}
```

**Comment by anzwdev** [comment]
Thank you for reporting this bug. I've fixed it and released a new version of the extension.
