### ISSUE TITLE
[Idea] Sort Page Customizations on Save

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#366]
Similar to the Save Action to Sort the Permissions I would love it, when my page customations are sorted on save of  a profile.

**Comment by anzwdev** [comment]
Thank you for your suggestion. I've added a new `SortCustomizations` option to the `alOutline.codeActionsOnSave` setting and 2 new commands:
* "Sort Customizations Property in the Active Editor"
* "Sort Customizations Property in the Active Project"
