### ISSUE TITLE
[Bug] Parentheses are added to field names with reserved keywords

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#367]
In the Base app, a 'format' field exists in the 'VAT Registration No. Format' table. When using this field (e.g. in a validate / setrange / ... statement and running the 'cleanup' commandlet, all field references are affixed with parentheses, which makes code no longer compile.

![image](https://user-images.githubusercontent.com/25268332/172322422-fd2a63de-e546-4c03-9a89-5b3c986ad17c.png)

**Comment by anzwdev** [comment]
I was trying to replicate your issue, but it works without any problems for me. Do you still have this issue? Can you replicate it if you run "Add Missing Parentheses to the Active Editor" command? What do you have in your "alOutline.codeCleanupActions" setting?

**Comment by fvet** [comment]
@anzwdev I've retested the Cleanup action and this issue does no longer occur in the latest version.
