### ISSUE TITLE
[Bug] New AL File Wizard - UsageCategory 'None' not respected

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#369]
When creating a new AL file (page) via the wizard and selecting 'None' as Usage Category ...

![image](https://user-images.githubusercontent.com/25268332/172798147-33a0264b-ca14-468d-8454-9538abb92fe1.png)

... the property 'Usagecategory = None' is not added to the resulting AL file.

![image](https://user-images.githubusercontent.com/25268332/172798296-7a8a20ab-630e-4221-947d-1b426fa1b8e8.png)

**Comment by PaulFurlet** [comment]
Is not UsageCategory=None; the default value? Thus no need to specify it.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-usagecategory-property#remarks

**Comment by DavidFeldhoff** [comment]
Well, there's a UI cop rule that creates a warning if you not explicitly set the UsageCategory, so I can understand the request ✌️

**Comment by fvet** [comment]
> Well, there's a UI cop rule that creates a warning if you not explicitly set the UsageCategory, so I can understand the request ✌️

Indeed, we´ve the UI cop enabled.

**Comment by anzwdev** [comment]
Hi. Thanks for reporting it. It makes sense, I'll add it.

**Comment by anzwdev** [comment]
New version of the extension with the fix has been released.
