### ISSUE TITLE
Add multiple fields between existing fields

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#37]
This request has been posted on twitter by @sbineshji
"Add multiple fields" action adds selected fields at the beginning of group, repeater or data item element. It would be nice to be able to add them at the current cursor position if it is placed between already added fields.

**Comment by sbinesh** [comment]
Good Idea, it's save developer's time

**Comment by anzwdev** [comment]
I've modified the extension to allow to run "add multiple fields" from report and query columns and from page fields. In that case new elements will be added below that field/column. Update has been uploaded to the Visual Studio Marketplace.
There is one important thing to remember - Visual Studio Code allows to invoke code action if cursor is on a code element, but it is not possible to do it from spaces between elements. It means that it is not possible to have 2 page fields with empty line between them and invoke "add multiple fields" from that empty line.
