### ISSUE TITLE
Autofix AA0231 ("Do not use the StrSubstNo or string concatenation as a parameter in the Error method")?

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#371]
Would this CodeCop error be auto-fixable (either in the active editor or the entire project - like the other fixes)? Removing the call to `StrSubstNo()` seems straightforward enough; perhaps the scenario in which `Error()` is called with a concatenated string is more risky?

**Comment by anzwdev** [comment]
Yes, you are right, it does not look complex. I'll add it.

**Comment by anzwdev** [comment]
I've released it in the previous release of the extension and forgot to change the task status. I'm sorry for that.
