### ISSUE TITLE
AL File Wizard - Default settings for API pages

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#374]
Would it make sense to add 2 default settings in the project settings to store the `Default API Publisher` and `Default API Group`?
When creating a new API page via the AL File Wizard, the wizard can then propose both values from the project settings.

This eliminates the DEV to review / verify these settings if already applied on project level.

![image](https://user-images.githubusercontent.com/25268332/175947024-7ab39a01-2d6f-49c9-98ec-5d763960ef36.png)

**Comment by anzwdev** [comment]
I've released a new version of the extension with these 3 new settings:
* `alOutline.defaultApiPublisher`: Default Api Publisher value for the page wizard
* `alOutline.defaultApiGroup`: Default Api Group value for the page wizard
* `alOutline.defaultApiVersion`: Default Api Version value for the page wizard
