### ISSUE TITLE
Add multiple fields to XMLPort

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#375]
When using the 'Add multiple fields' on a page object, the list of available fields is filtered to those fields that have not yet been added to the page (= great) This makes it easy to add new fields only.

When applying the same action  'Add multiple fields' on a XMLPort object, the list of available fields shows ALL fields. This makes it more difficult to verify which fields have not yet been included in the XMLPort. Would be nice if the same approach as for pages could be applied and only show those fields which are not yet part of the tableelement.

![image](https://user-images.githubusercontent.com/25268332/176621689-42e38e6a-95af-43ae-b4d1-d2f83f6775f7.png)

**Comment by anzwdev** [comment]
Thank you for reporting this bug. I've fixed it and released a new version of the extension.
