### ISSUE TITLE
Add multiple fields: sort field properties alphabetically

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#376]
When I invoke "Add multiple fields" for a page, then the ApplicationArea is always listed at the end:
```
field(SystemId; Rec.SystemId)
{
    ToolTip = 'Specifies the value of the SystemId field.';
    ApplicationArea = All;
}
```
Can you please insert it alphabetically ordered?

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this problem. I've fixed it and released a new version of the extension.
