### ISSUE TITLE
API Pages : useTableFieldCaptionsInApiFields > locked = true

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#377]
When setting `useTableFieldCaptionsInApiFields` to false, a `locked = true` is added to the API field captions, avoiding the fields from being translated.

When setting `useTableFieldCaptionsInApiFields` to **true**, the Field Caption from the Table are being added, but don't get the `locked = true`. We'd like to avoid any fields on API pages from being translated and would also prefer to add `locked = true` in case field captions from the table would be used. 

Would that make sense adding `locked = true` as a default - irrespective the `useTableFieldCaptionsInApiFields` setting - or maybe support this through a new setting?

For us, API pages are more a way of exchanging data for reporting ..., rather then something used to build a UI on top, without the need for captions.

**Comment by fvet** [comment]
Giving this a second thought, we are considering of **not** adding any captions at all in our API pages.

I'd be in favor of having a setting instead that would prevent captions from being added to API objects via the 'Add Multiple Fields' or the 'New AL File Wizard'.

Required result:

![image](https://user-images.githubusercontent.com/25268332/177503946-286cc611-b7e9-4d7b-ac28-ec8c1edfff51.png)

**Comment by anzwdev** [comment]
I've added a new `alOutline.createApiFieldsCaptions` setting with default value set to true. If you want to disable captions functionality set it to false.
