### ISSUE TITLE
API Pages : API field name suggestions for 'number' fields (number instead of no)

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#378]
Looking into the standard BC API's, all `no`, `lineNo`, `documentNo`, `entryNo` ... fields have received another (better) field name (`number`, `lineNumber`, `documentNumber`, `entryNumber`, ...) on API pages.

`No` as a API field name is not really clear, `number` is. 

Would it be possible when adding fields to **API** pages, to replace field names ending on `no` (or fields containing ` No.`) by `number` instead?

**Comment by anzwdev** [comment]
Thank you for the idea. I've added a new `"alOutline.apiFieldNamesConversion"` setting that you can use to define regular expressions and replacement texts fro api field names. Here is an example for "<anything> No." and "No." replacement:

``` json
    "alOutline.apiFieldNamesConversion": [
        {
            "searchRegExp": "^no$",
            "newValue": "number"
        },
        {
            "searchRegExp": "No$",
            "newValue": "Number"
        }
    ]
```
