### ISSUE TITLE
Add Missing Parenthesis to Active Editor

### ISSUE THREAD

**Issue by tscottjendev** [anzwdev/al-code-outline#379]
I can't seem to get this work.  See attached video.

It just never finds anything to fix.

https://user-images.githubusercontent.com/102963427/177493187-12959ee9-d459-4e2d-a9fd-a57dcc95179e.mp4

**Comment by tscottjendev** [comment]
AL Toolbox has a similar problem https://github.com/BartPermentier/al-toolbox/issues/77

**Comment by anzwdev** [comment]
Do you still have this issue? I tried to replicate this problem with the latest version, but everything works fine in my case.

**Comment by tscottjendev** [comment]
Sorry, I've been away.  I will test again and see if I can reproduce.

**Comment by tscottjendev** [comment]
Seems to be working today.  Close it and I will report again if I find it.
