### ISSUE TITLE
Finish button on the object wizard not always works for some users

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#38]
This issue has been posted on twitter by 2 different developers, it requires more investigation.

**Comment by anzwdev** [comment]
I've added 2 small changes/fixes to improve wizards UI:
- css style for disabled buttons was missing
- 'Finish' button is always active now. Before this change, pressing 'Next' and then 'Back' was disabling it on the first page of all wizards

**Comment by pri-kise** [comment]
I can confirm that the finish button doesn't work for me always, too.
On my attempts of creating objects the following pattern occured:

- When i started the wizard with right click on the file browser and select then an object, everything works fine.
- If i start the wizard with opening the command-pallete (ctrl+shift+p), the finish button doesn't create a file.

**Comment by anzwdev** [comment]
Thank you for reporting it. This functionality has been designed to be always run from the file browser context menu as it needs to know where to save the file, but I can see that it makes sense to run it from the command palette and save file in the root folder of the project or use crs reorganize settings to find target directory. I will take a look at it.

**Comment by anzwdev** [comment]
I've modified the extension and uploaded it to visual studio marketplace. It is now possible to run file wizards directly from command palette. If "on save file action" in CRS AL Language Extension is set to Reorganize, file will be saved in the same folder, where crs extension would move it.
