### ISSUE TITLE
AL Outline panel support Region Directive in AL (New Feature Request)

### ISSUE THREAD

**Issue by louagej** [anzwdev/al-code-outline#380]
Hi,

Could support of regions be added to the AL Outline?

Source: [Region Directive in AL](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-region)

Assume we have this codeunit:

```al
codeunit 50000 MyCodeunit
{
    #region My ugly functions - let's not look at this
    procedure UglyCode()
    begin
        // No one should look at this
    end;

    procedure UglyCode2()
    begin
        // No one should look at this too
    end;
    #endregion

    #region My Beautiful code - let's look at this
    procedure BeautifulCode()
    begin
        // Someone should look at this
    end;

    procedure BeautifulCode2()
    begin
        // Someone should look at this too
    end;
    #endregion
}
```

For `MyCodeunit`, this is what I get in the AL Outline window:

![image](https://user-images.githubusercontent.com/7229592/177985056-ef08d576-f9b4-4131-81e5-2b849f3d33be.png)

For `MyCodeunit`, this is what it could look like in the AL Outline window:

![image](https://user-images.githubusercontent.com/7229592/177985683-529bc4ac-d683-4af7-9532-15c2f37d7b78.png)

**Comment by anzwdev** [comment]
Thank you for the idea, I've added it to the extension and released a new version
