### ISSUE TITLE
[Feature suggestion] BC21 - Field ApplicationArea defaults to page value

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#387]
With the new upcoming feature in BC 21 which allows pages control to default to the page ApplicationArea, I think some refactoring / enhancements could be added to AZ AL Dev Tools (valid for app with a runtime 10 or higher)

https://docs.microsoft.com/en-us/dynamics365-release-plan/2022wave2/smb/dynamics365-business-central/field-applicationarea-defaults-page-value

---

- [ ] New AL File Wizard

When creating a new page via the wizard, you can specify the Application Area. As a result, the wizard adds the ApplicationArea property to both the page and the page controls. Starting from runtime 10, it would be nice if we could avoid the ApplicationArea  being automatically added to the page controls. (if needed, maybe foresee `'ApplicationArea' : Mandatory, Optional` setting?)

---

- [ ] Add Multiple Fields

When adding fields to a page using the 'Add Multiple Fields' action, all added fields receive the default ApplicationArea property . Starting from runtime 10, it would be nice if we could avoid the ApplicationArea  being automatically added to the page controls. (if needed, maybe foresee `'ApplicationArea' : Mandatory, Optional` setting?)

---

- [ ] Add Application Areas

- ?? Review how the command 'Add Application Areas' should behave. If the new 'ApplicationArea' setting is set to Optional, the command should not fix missing ApplicationArea occurences on page controls.

- Pages **without** ApplicationArea (= those that currently have **no UsageCategory**) might need to receive the Default App Area. This would ease the rule described in (**) 

---

- [ ] **(NEW)** Remove (redundant) Application Areas

It would be nice if we could have a new Code Cleanup action (for the Active Editor, Active Project and as option in the `"alOutline.codeCleanupActions"`), so we can **remove** any **redundant** ApplicationArea properties (for page controls).

The action should cover following scenarios:

- If a page has an ApplicationArea, then the ApplicationArea property can be removed on all (request) page controls with an ApplicationArea property with the **SAME** value as the page value. Controls having a different ApplicationArea value should not be changed.
- (**) If a page has **no** ApplicationArea (= those that currently have no UsageCategory) and all page controls have the same ApplicationArea property, then fill the ApplicationArea property of the page. (and evaluate the first rule again, so that the ApplicationArea on page controls gets removed). 

- Also review for request pages on reports.

End result we'd like to achieve would be 

![image](https://user-images.githubusercontent.com/25268332/181451476-42c5832e-2872-4e10-a97b-5d3daabc88f0.png)
---

_Current related settings_

![image](https://user-images.githubusercontent.com/25268332/181447506-576fe11d-7c9b-4340-9531-8f51ea69f6b7.png)

**Comment by anzwdev** [comment]
I've released a new version, there is a new "alOutline.appAreaMode" setting, you can use "inheritFromMainObject" or "addToAllControls". Default value is "inheritFromMainObject", but when runtime version of the extension is lower than 10.0, "addToAllControls" will be used. Wizards and "add multiple fields" commands are using this setting now. There is also 2 new commands to remove redundant application areas:
- "azALDevTools.RemoveEditorRedundantAppAreas",
- "azALDevTools.RemoveProjectRedundantAppAreas",

**Comment by fvet** [comment]
Will give it a test soon, thanks a lot for this new feature !
