### ISSUE TITLE
[Feature Request] Minimum variable sort mode for AA0021

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#388]
Hi Andrzej,

could you maybe implement a third variable sort mode that would only sort data types correctly, but keep the previous order within the same data type? 
Only that option would be the exact fix for [AA0021](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0021). I'd like to keep the existing hierarchies within a data type, especially for record variables.

**Comment by anzwdev** [comment]
Hi Natalie

Yes, I will add it

**Comment by NKarolak** [comment]
Great, thank you 😊

**Comment by anzwdev** [comment]
Functionality is ready, there is new "alOutline.variablesSortMode" setting, you can use one of these values there
"fullTypeName", "mainTypeNameOnly", "fullTypeNameKeepVariableNameOrder", "mainTypeNameOnlyKeepVariableNameOrder"
Last 2 options won't change the order if data types are the same

I've just realized that option value tooltips are incorrect in the settings, I'll fix it it the next release.

**Comment by NKarolak** [comment]
Thanks!

However, the command now does not work anymore for me, no matter which setting:
![image](https://user-images.githubusercontent.com/34504100/190974892-d4e9b56e-06e0-4abf-9cd4-c0286e90fbd3.png)
It would do nothing. Reloading the window did not help. v3.0.36

Any ideas ...?

**Comment by anzwdev** [comment]
How your variable declaration looks like? Can you see any errors if you run "Open AZ AL Dev Tools log file" command?

**Comment by NKarolak** [comment]
Good news: the code action works again for me. I assume it was activated by the last minor VS Code update, which did not increase the VS Code version number (still shown as 1.71.2). Weird. However, sorry for the inconvenience, and thanks for the new options :-)
