### ISSUE TITLE
"Add Missing Parentheses": Skip variables with the same name as a record function.

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#389]
Let's say you have a public table procedure called "IsWhatever", which returns a boolean.
You want to use that on a **page** of the same table, for setting "Visible". Since you are not directly allowed to use
`Visible = Rec.IsWhatever();`
you create a global page variable named "IsWhatever" and set it on `OnAfterGetCurrRecord`:
`IsWhatever := Rec.IsWhatever();`
Now you can use
`Visible = IsWhatever;`

In that case, "Add Missing Parentheses" will add parentheses to all occurrences of the IsWhatever boolean variable - which leads to an error:

> Member 'IsWhatever' cannot be used like a method [AL0127](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al127)

(Of course, I am aware that I can simply rename the boolean variable to e.g. IsWhateverVisible.)

Edit: furthermore, "Remove Unused Variables" will delete such boolean variables 😮

**Comment by anzwdev** [comment]
It looks like a bug, I need to investigate why wrong symbol type is detected by my command.

**Comment by anzwdev** [comment]
The command is compiling code and uses compiled model to check if identifier is a procedure or variable. Are you sure that your code compiles? I am not able to use page variable with the same name as record function, because compiler thinks that it is record method.
![image](https://user-images.githubusercontent.com/24944969/192111673-2f3252a7-4ff8-47c1-9e83-d7718a1ccdc3.png)

**Comment by NKarolak** [comment]
My code is even on AppSource.
It looks like the NoImplicitWith feature is not active in your app.json?

**Comment by anzwdev** [comment]
That explains why it was working differently for me. Fix will be ready in the next release.

**Comment by anzwdev** [comment]
Thank you for helping me replicate this issue. I've released a new version, it should work now.
