### ISSUE TITLE
Code Clean-up: Remove Empty Triggers

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#392]
It would be great to have a clean-up action that automatically removes empty triggers, i.e. triggers without local variables or statements.

**Comment by DavidFeldhoff** [comment]
Just want to highlight this one:
https://twitter.com/ajkauffmann/status/1504593102371237889
and this one
https://community.dynamics.com/business/f/dynamics-365-business-central-forum/418899/onaftergetcurrrecord-vs-onaftergetrecord-vs-factboxes-ui-update

It seems they sometimes have sense

**Comment by anzwdev** [comment]
New pair of editor/project "Remove Empty Triggers" commands is ready. You can choose to remove empty triggers and/or event subscribers and also decide to keep them if they have just comments inside. There is also a new default setting for this command to be able to run it in code cleanupo without asking for parameters, here is an example:
``` json
"alOutline.defaultRemoveEmptyTriggersSettings": {
 "removeTriggers": true,
 "removeSubscribers": true,
 "ignoreComments": true
}
```
To run it in code cleanup command, just add "RemoveEmptyTriggers" to "alOutline.codeCleanupActions" setting
