### ISSUE TITLE
Code Clean-up: FlowFields

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#393]
It would be great to have a clean-up action (either a new one, or as part of an existing one) that removes the DataClassification property from FlowFields (and FlowFilter fields?) and adds `Editable=false` to FlowFields, unless `Editable=true` is already present. After all, editability only makes sense for CalcFormula method Sum, and even then, only in a fraction of cases. If the developer consciously and explicitly specified `Editable=true`, the extension should not change that, but in all other FlowField cases, add `Editable=false`.

Thank you for considering my suggestion.

**Comment by fvet** [comment]
Small tip, BC LinterCop contains a rule to warn on the editable property. 

https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0001

Not a cleanup, but definitely usefull.

**Comment by anzwdev** [comment]
I've released a new version, there are 3 changes:
   - new editor and project "Make FlowFields Read-Only..." commands
   - new "MakeFlowFieldsReadOnly" option for Code Clean-up
   - Existing "Add DataClassification" commands remove property from FlowField and FlowFilter table fields
