### ISSUE TITLE
alOutline.codeCleanupActions: tooltips appear to be "off-by-one"

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#394]
The "tooltip" for RemoveEmptySections is actually the tooltip for RemoveStrSubstNoFromError etc.

https://user-images.githubusercontent.com/1273387/189830380-cfaac49a-3bba-49c8-9721-c90426dfc73d.mp4

**Comment by anzwdev** [comment]
Thank you for reporting this bug. I've released a new version, it should be fixed now.
