### ISSUE TITLE
[BUG] RemoveEmptyTriggers conflicts with regions

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#397]
The new RemoveEmptyTriggers (#392) results in invalid files.

![image](https://user-images.githubusercontent.com/25268332/191020047-2e24582a-b72f-4453-b7b1-8ceb3fb8ece8.png)

In case an empty procedure (embedded within region markers) is removed, the start #region directive is removed, leaving an orphaned #endregion directive. You can test with below code.

```
#region OnUpgradePerDatabase
    trigger OnUpgradePerDatabase()
    begin
    end;
    #endregion OnUpgradePerDatabase
```

**Comment by anzwdev** [comment]
I've released a new version, this issue should be fixed now
