### ISSUE TITLE
Add semicolon to end of the new completion provider

### ISSUE THREAD

**Issue by nickgoddard777** [anzwdev/al-code-outline#398]
Hi Andrzej,

Thank you for such a brilliant tool.

I have started using the new Completion Provider you showed at Tech Days.  I have it set to VariableNamesWithType.  Would it be possible to add a semicolon to the end of the returned string?

Thanks Again

Nick G

**Comment by anzwdev** [comment]
Yes, it seems to be a good idea to add it to the variables created inside VAR section, but I am not sure if it should be added to the parameters.

**Comment by anzwdev** [comment]
I've released a new version, semicolon will be added to variable declaration but won'b be added to parameters or return variable.
