### ISSUE TITLE
"Remove empty sections" appears to ignore empty actions section in page extensions (and possibly also in pages?)

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#402]
I can't seem to get it to remove my empty actions section. I'm using version v3.0.37.

**Comment by anzwdev** [comment]
I've released a new version, it now supports a few more section types - action groups, page field groups and empty actions. There is also a new `alOutline.defaultRemoveEmptySectionsSettings` setting that you can use in code cleanup to enable/disable removing these 3 new groups or enable/disable treating sections with just commens as empty.
