### ISSUE TITLE
Lowercase for reserved keywords

### ISSUE THREAD

**Issue by bdgjope** [anzwdev/al-code-outline#403]
Hi
I have seen that VS Code has started to complain that lowercase needs to be used for all reserved keywords (AA0241). Your autogenerated code does not seem to follow this rule. I have not seen any setting for this either. Is this something you can change?
Thanks in advance

**Comment by guidorobben** [comment]
https://github.com/microsoft/AL/issues/7156 Seems like an error on MS side.

**Comment by anzwdev** [comment]
Yes, it looks like MS bug, we have to wait until it is fixed.
