### ISSUE TITLE
[Bug] RemoveProjectRedundantAppAreas - Exclude page/report extensions (AS0062 error)

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#404]
When using the new `RemoveProjectRedundantAppAreas` setting or the 'Remove Redundant AppAreas ...' commands, **page/report extensions** should be excluded.

Apparently, the new ApplicationArea approach only applies to pages/reports and not to page/report extensions.

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0062

![image](https://user-images.githubusercontent.com/25268332/194489774-38d7be31-189d-48d7-9f4d-27d69e879ba0.png)

Running the 'Remove Redundant AppAreas ...' results in lots of AS0062 errors, on page extensions that no longer contain the ApplicationArea ...

![image](https://user-images.githubusercontent.com/25268332/194489538-28d188ec-afe9-40e1-b8fc-dd0ca85aa620.png)

**Comment by anzwdev** [comment]
Thank you for reporting this bug. I've released a new version, it should work now.
