### ISSUE TITLE
[BUG] Variable completion provider runs in invalid places (as return value for triggers?)

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#406]
I would have expected the new variable completion provider to only work in the context of a var section, for function parameter or return values (for procedures, not for triggers).

In below scenario, the code completion is annoying, since i'd like to complete the trigger definition with a begin / end, but apparently the completion provider (wrongfully) detects this as a return value for the trigger?

![Trigger](https://user-images.githubusercontent.com/25268332/195270068-45e07ac3-0654-491e-a72c-613e0d2d3a20.gif)

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've fixed it and released a new version. Completion provider will no longer suggers trigger or event subscribers parameters or return types.
