### ISSUE TITLE
[CodeCompletion] Ignore Pre- and Suffixes in variable names

### ISSUE THREAD

**Issue by christianbraeunlich** [anzwdev/al-code-outline#407]
Hi Andrzej,
first of all: thank you for your wonderful extension!

The recently released feature **CodeCompletion** / `alOutline.completionProviders` has now become one of my favourite.

Which leads to the question: Can we ignore certain prefixes/suffixes for the variable name?

Example:

**Given**

```al
codeunit 90000 "ACO Library Management OTTER"
```

**Before**
```al
var
    ACOLibraryManagementOTTER: Codeunit "ACO Library Management OTTER";
```
**After**
```al
var
    LibraryManagement: Codeunit "ACO Library Management OTTER";
```

**Comment by anzwdev** [comment]
Hi

There are 2 options:
- you can add them to AppSourceCop.json file to the mandatoryAffixes, mandatoryPrefix or mandatorySuffix property
- you can use `alOutline.additionalMandatoryAffixesPatterns` setting - it is an array of string patterns, you can use "?" as "any character"

**Comment by christianbraeunlich** [comment]
Works perfectly - thanks for the quick reply! 🦦
