### ISSUE TITLE
Variable completion suggests non-accessible objects

### ISSUE THREAD

**Issue by ajkauffmann** [anzwdev/al-code-outline#408]
The variable completion includes objects that are not accessible.

![image](https://user-images.githubusercontent.com/19155831/195973024-40f9f613-624c-401f-80c2-324e14dc3228.png)

Codeunit "Base64 Convert Impl." has property Access = Internal.
AL can manage this. It would be nice if the variable completion could filter these out as well.

![image](https://user-images.githubusercontent.com/19155831/195973079-0ca04156-9d3e-49dc-9722-400feaa7a354.png)

Of course this is for dependent apps only! The internal objects should still be there if the object is in the same app.

**Comment by anzwdev** [comment]
Thank you for reporting this bug. I've released a new version, these data types should no longer be visible.
