### ISSUE TITLE
Search in Object browser is case sensitive

### ISSUE THREAD

**Issue by damse60** [anzwdev/al-code-outline#410]
It would be prefered if search for objects in the Object browser was not case sensitive.

**Comment by rvanbekkum** [comment]
You can prepend a `@` to your filter string for a case-insensitive search. The object browser adheres to the same filtering syntax as the BC/NAV client(s).

**Comment by rvanbekkum** [comment]
Noticed you are about to change the implementation so that a case-sensitive search is no longer possible?

**Comment by anzwdev** [comment]
Yes. Object names are not case sensitive in AL so it seems to be a good idea to remove case-sensitive filtering from the object browser.
