### ISSUE TITLE
Cleanup removes instructions from wizard pages

### ISSUE THREAD

**Issue by dsaveyn** [anzwdev/al-code-outline#411]
When using the cleanup to remove empty sections/triggers, instructions are also removed from wizard pages: 

For example, when performing a cleanup on page 1804 "Approval Workflow Setup Wizard" in de MS Base App, the following occurs:

![CleanupIssue](https://user-images.githubusercontent.com/92365904/196205109-cfc6ccaf-940b-4019-9629-0c5cc77157f3.gif)

Settings:
`
{
    "alOutline.codeCleanupActions": [
        "RemoveEmptySections",
        "RemoveEmptyTriggers"
    ]
}
`

This behavior is kind of dangerous especially in combination with wizard pages.

**Comment by rvanbekkum** [comment]
It also removes (1) "`cuegroup` controls with actions only" and (2) "`group` controls with the `InstructionalText` property but without any sub-controls" from pages.

**Comment by fvet** [comment]
@anzwdev  Any timing on when v3.0.40 is planned to be released?

**Comment by anzwdev** [comment]
I want to do release these changes this weekend

**Comment by anzwdev** [comment]
Thank you for reporting this problem. I've removed option to remove empty groups and released a new version of the extension.
