### ISSUE TITLE
[Request] add permissions to current object

### ISSUE THREAD

**Issue by guidorobben** [anzwdev/al-code-outline#412]
When building a method codeunit,I add the permissions needed to the object. something like this.

codeunit 90000 "Update Price List Meth PTE"
{
    Permissions =
        tabledata Item = R,
        tabledata "Price List Header" = R,
        tabledata "Price List Line" = RMI;
}

Is it possible to create a function that scans the object and adds the proper tabledata to the permission property?

**Comment by anzwdev** [comment]
Thank you for the idea. I've released it in the latest extension version.
