### ISSUE TITLE
Warning and/or code action for setting NotBlank=true for primary key fields

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#413]
Thanks for considering my suggestion!

**Comment by fvet** [comment]
BCLinterCop has a warning already.
https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0013

See also https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/63

**Comment by jhoek** [comment]
> BCLinterCop has a warning already. https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0013
> 
> See also [StefanMaron/BusinessCentral.LinterCop#63](https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/63)

Ah, excellent, I did not know that, thanks! Does BCLinterCop also have a way to resolve the warning, in the current editor/in the entire project?

**Comment by fvet** [comment]
No, only warnings. It's dangerous to auto resolve by setting notblank to **true**, since for certain singleton tables / setup tables, you  would set notblank to **false** instead. So I think each object needs to get reviewed individually instead of auto fixing.

**Comment by jhoek** [comment]
Developers could (should?) always communicate their intent to allow blank PK values by manually setting NotBlank to false instead. By making it explicit, the developer demonstrates that she consciously and intentionally wanted to allow blank values. So LinterCop or AL-Code-Outline should only warn/take action if NotBlank is entirely absent?

**Comment by fvet** [comment]
True, we indeed make the `NotBlank` for single code/text field PK tables **explicit**. 
Another (less favorable) option is to **pragma** the warnings, to indicate that you've consciously reviewed the warning.

See documentation of the rule
_...
There are exceptions for this, on setup tables, for example. In those cases you can either use a pragma to suppress the warning or 
you can set NotBlank = false. Then the warning will not show up for this field._

**Comment by jhoek** [comment]
Exactly that! Great minds think alike. ;-) 

OK, since LinterCop has this warning, and fixing things application-wide is rather dangerous, I think I'll close this issue? Thanks again for taking the time to discuss this with me.
