### ISSUE TITLE
Action for adding missing DataCaptionFields property and/of DropDown field group (in Active Editor/Active Project)

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#414]
- If neither is present, populate both with the primary key fields + description fields.
- If either is present, use it to populate the other. 

Not sure how you should recognise description fields, but heuristics could be a combination of:
- based on name: look for Description/Description 2 or Name/Name 2
- based on type: look for text fields whose length is between 30 and 100
- based on index: the criteria above should match fields that appear "early" in the table, e.g. in the first 10-15 fields

P.S.: I realise this may be more "fuzzy" than most other things in the extension... ;-)

**Comment by anzwdev** [comment]
Thank you for a great idea. I am just not sure if populating one of these properties with the list of fields from the other one is a good idea. I would prefer to have a longer list for the DropDown to help users select the correct record (i.e. No., Name, all "Address" fields) while DataCaptionFields should be shorter to fit on the screen (i.e. No., Name).

I will create 2 separate commands with separate settings to specify list of field names/patterns to be used. Each of these commands will use primary key fields first and then use these settings to find other fields. I don't want to implement too complex logic here to avoid a lot of new issues where people will be asking to explain why some fields have been added/have not been added or to add some additional, complex rules.

**Comment by jhoek** [comment]
Agreed about the fundamental difference between the two properties, I just didn't want to make things too difficult. ;-) Thanks again for considering my suggestion!

**Comment by anzwdev** [comment]
New functionality has been released at the beginning of January, there are "Current Editor"/"Project" pairs of commands adding missing DataCaptionFIelds and DropDown Field Groups: "Add Table DataCaptionFields to ..." and "Add DropDown Field Groups to ..."
