### ISSUE TITLE
[Bug] RemoveProjectRedundantAppAreas - Exclude report requestpages (AS0062 error)

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#416]
Note
_This seems more like an error in BC / AL, where the requestpage does not inherit the ApplicationArea from it's parent report._

However, when running the RemoveProjectRedundantAppAreas command, the ApplicationArea is stripped from the requestpage controls, resulting in AS0062 errors.

**Before**

![image](https://user-images.githubusercontent.com/25268332/198299739-750f98cb-52e4-4ce5-abc2-1f6acd5a0f42.png)

![image](https://user-images.githubusercontent.com/25268332/198299841-63243839-dcca-4f99-80e5-c905168e842d.png)

**After**  (RemoveProjectRedundantAppAreas)

![image](https://user-images.githubusercontent.com/25268332/198299913-10839a91-d4c5-45d9-8bec-0ff0db2c4b8e.png)

**Comment by anzwdev** [comment]
Thank you for reporting this problem. I've fixed it and released a new version of the extension.

**Comment by fvet** [comment]
Thanks a lot!👍
