### ISSUE TITLE
Add Page Controls Captions: Skip for ShowCaption = false

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#418]
Please (add at least a setting to) ignore any elements with `ShowCaption = false;` when running command `Add Page Controls Captions`.

When adding caption properties, please add the property in alphabetical order.
Maybe it would make sense to not add them for repeater groups on lists and worksheets.

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've implemented the change and released a new version of the extension.

**Comment by NKarolak** [comment]
Thanks a lot :-)
