### ISSUE TITLE
Filtering in "Action Images" window

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#42]
When you open the "Action Images" window using command `AZ AL Dev Tools: Show Action Images` you get to see all images you can use for page actions.
It would be useful to also be able to filter/search for images based on provided search terms.
Perhaps this could reuse the filtering implementation that is also used for filtering on object names in the AL Object Browser?

**Comment by anzwdev** [comment]
That's a good idea, I'll do it. Your filter parser, that you've added in your pull request is really great. Thank you for that.

**Comment by anzwdev** [comment]
New version of the extension has been uploaded to the Visual Studio Marketplace. I've added filtering, keyboard navigation and context menu to the action images browser. You can now invoke these 3 commands from the context menu on images in the browser:
 - Copy name - copies image name to the clipboard
 - Copy as action - generates page action element and copies it to the clipboard
 - Copy as promoted action - generates promoted page action element and copies it to the clipboard

**Comment by rvanbekkum** [comment]
Great! The new commands that can be invoked via the context menu might be useful as well. :)
