### ISSUE TITLE
FowFilters aren't added to API Pages

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#421]
When I create a Page fo type of API and add all fields, then FlowFilters aren't added.

Is this on purpose?

Regarding on thread on yammer, then FlowFilters have to be added to Api Pages to be able to set filters on these fields.
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1598169126846464&search_origin=global&scoring=linear1Y-prankie-group-private-higher&match=any-exact&search_sort=relevance&page=1&search=flowfilter%20api

Additionally if I want to add these FlowFilters afterwards via code actions, but I can't select them there either

**Comment by anzwdev** [comment]
FlowFilters are not available to avoid problems when users add all available fields with one click to the objects. I'll modify the extension to show them for API pages, but I need to modify UI first, so field type is visible in wizards and "add fields" code actions.
