### ISSUE TITLE
Procedure Sorting Criteria

### ISSUE THREAD

**Issue by ChrisSteuten** [anzwdev/al-code-outline#422]
Currently it seems that procedures are only sorted by their name on code cleanup. It would be great to be able to adjust this so it sorts by access modifier prior to the name.

**Comment by rvanbekkum** [comment]
I believe it already does that, right? First public, then internal and then local, for example.

**Comment by anzwdev** [comment]
There was an issue with internal and protected procedures sorting - they were treated as local. I've added support for these 2 types, the new order will be public, internal, protected and local now. New version of the extension with this change is ready.
