### ISSUE TITLE
"Nothing to change"

### ISSUE THREAD

**Issue by micalley** [anzwdev/al-code-outline#423]
Hello,

I am unable to run VSCode in local administrator mode due to security restrictions.

When I run the AL Code Outline extension (For example Sort properties) I get a message saying "Nothing to change".  If i run the program at home as local administrator it works fine. 

I have made sure that the workspace is trusted and I have tried setting 

    "extensions.supportUntrustedWorkspaces": {
        "rvanbekkum.xliff-sync": {
            "supported": true
        },
        "waldo.crs-al-language-extension": {
            "supported": true,
        },        
        "andrzejzwierzchowski.al-code-outline": {
            "supported": true
        },
    },

This does not help.

I have also tried installing vscode both as a local user and as a local admin on my work PC. AL Code Outline only works when I _run_ VSCode as local admin.

Can you guide me on how to fix this?

If i look into the developer console. I always get this warning when I try to run "Sort Properties ..."

**event.ts:39 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:39
_event._event @ event.ts:750
(anonymous) @ event.ts:124
onFirstListenerAdd @ event.ts:184
_event._event @ event.ts:750
B @ listWidget.ts:624
createMouseController @ listWidget.ts:1409
Q @ listWidget.ts:1393
H @ listService.ts:249
_createInstance @ instantiationService.ts:120
createInstance @ instantiationService.ts:86
createNotificationsList @ notificationsList.ts:84
show @ notificationsList.ts:57
doAddToast @ notificationsToasts.ts:206
(anonymous) @ notificationsToasts.ts:153
execute @ dom.ts:163
Dt @ dom.ts:203
event.ts:39 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:39
_event._event @ event.ts:750
(anonymous) @ event.ts:124
onFirstListenerAdd @ event.ts:184
_event._event @ event.ts:750
B @ listWidget.ts:624
createMouseController @ listWidget.ts:1409
Q @ listWidget.ts:1393
H @ listService.ts:249
_createInstance @ instantiationService.ts:120
createInstance @ instantiationService.ts:86
createNotificationsList @ notificationsList.ts:84
show @ notificationsList.ts:57
doAddToast @ notificationsToasts.ts:206
(anonymous) @ notificationsToasts.ts:153
execute @ dom.ts:163
Dt @ dom.ts:203**

Thank you in advance.

**Comment by anzwdev** [comment]
Could you try to run "Open AZ AL Dev Tools log file" command in your VS Code? It should open error log file. Can it open it? Are there any errors in the log?

**Comment by mralley** [comment]
Hello Andrzej,

Thank you so much for looking my question. I really enjoy your app and miss being able to use it.

When I run "Open AZ AL Dev Tools log file"  I get this message.

cannot open file:///c%3A/Users/ma20/.vscode/extensions/andrzejzwierzchowski.al-code-outline-3.0.40/bin/netcore/win32/log.txt. Detail: Unable to read file 'c:\Users\ma20\.vscode\extensions\andrzejzwierzchowski.al-code-outline-3.0.40\bin\netcore\win32\log.txt' (Error: Unable to resolve nonexistent file 'c:\Users\ma20\.vscode\extensions\andrzejzwierzchowski.al-code-outline-3.0.40\bin\netcore\win32\log.txt')


I have looked in the directory and the log file does not exist.

Med venlig hilsen/Kind Regards,
Michael Alley
________________________________
Fra: Andrzej Zwierzchowski ***@***.***>
Sendt: 30. november 2022 23:18
Til: anzwdev/al-code-outline ***@***.***>
Cc: Michael ***@***.***>; Author ***@***.***>
Emne: Re: [anzwdev/al-code-outline] "Nothing to change" (Issue #423)


Could you try to run "Open AZ AL Dev Tools log file" command in your VS Code? It should open error log file. Can it open it? Are there any errors in the log?

**Comment by mralley** [comment]
PS.

For your information I have also disabled all apps except

AL Language
AZ AL Dev Tools
waldo CRS AL Language extension



Med venlig hilsen/Kind Regards,
Michael Alley
________________________________
Fra: Andrzej Zwierzchowski ***@***.***>
Sendt: 30. november 2022 23:18
Til: anzwdev/al-code-outline ***@***.***>
Cc: Michael ***@***.***>; Author ***@***.***>
Emne: Re: [anzwdev/al-code-outline] "Nothing to change" (Issue #423)


Could you try to run "Open AZ AL Dev Tools log file" command in your VS Code? It should open error log file. Can it open it? Are there any errors in the log?

**Comment by micalley** [comment]
Hello Andrzej,

I have found the reason for the problem. The IT director has an unapproved program from running scripts installed in the user folder. I was unaware of this security measure.
