### ISSUE TITLE
[Suggestion] Variable Completion including double quotes

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#425]
I quit often navigate to other objects (e.g. Base Application) to find some inspiration. When I find the object / code part I'd like to use, I can now easily copy the **variable name** and use variable completion to get the data type/name (if the variable in the source object was properly named).

However, sometimes I've no variable and just copy the **data type name** (e.g. `"Assemble-to-Order Link"`, `"Sales Document Type"`, ...)

It would be nice if I could paste this double quoted name into the var section (or as function parameter) and hit Ctrl+space to trigger the variable code completion. This could strip the input text from double quotes (and remove any special chars) and suggest the proper data type / name.

![CompletionProvider2](https://user-images.githubusercontent.com/25268332/205246489-39e76a29-825d-40e2-a50f-3c3018e58c63.gif)

**Comment by anzwdev** [comment]
Thank you for the suggestin, fix will be ready in the next release of the extension.
