### ISSUE TITLE
[Suggestion] RemoveRedundantDataClassification

### ISSUE THREAD

**Issue by jwikman** [anzwdev/al-code-outline#432]
I love the RemoveRedundantAppAreas cleanup feature.

But I would suggest a similar functionality for the `DataClassification` property! 

So if run the new cleanup, it adds `DataClassification = [setting alOutline.defaultDataClassification]` at the top level of all objects that is missing a `DataClassification`. And then it removes all redundant `DataClassification` from the fields in that object.

**Comment by JavierFuentes** [comment]
@anzwdev ,
any news about this new feature?

**Comment by anzwdev** [comment]
I am in the middle of working on it, it will be available in the next release

**Comment by anzwdev** [comment]
Thank you for the suggestion, I've implemented and released it a few days ago.

**Comment by jwikman** [comment]
Thanks @anzwdev,
I just gave this a spin - but noticed that it removed `DataClassification` on Table Extension fields as well... And since there are no `DataClassification` property on the Table Extension object level, there is no default value to fall back to -> rule [AS0016](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0016) kicks in   (Field with name '[FieldName]' must use the DataClassification property and its value should be different from ToBeClassified.).

So, can you please omit table extension with this feature? 🙂
