### ISSUE TITLE
[Suggestion] Syntax tokens in the Document Syntax Visualizer

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#440]
Although I appreciate the decision not to clutter the Document Syntax Visualizer with all of the syntax tokens, I would sometimes like to be able to view the tokens' properties as well. Perhaps you could add a toolbar button to the visualizer pane that toggles the inclusion of the tokens in the treeview? 

Thank you for considering my suggestion!

**Comment by anzwdev** [comment]
Thank you for the idea. I've released a new version of the extension, you can now switch between "child nodes tree view" and "class tree view" in the Syntax Visualizer. First one shows old tree, based on ChildNodes list from each SyntaxNode. Second, new view builds tree using SyntaxNode properties that have Token, SyntaxNode and IEnumerable<SyntaxNode> (list of nodes) type.
