### ISSUE TITLE
codeCleanupAction AddPageFieldCaptions adds Caption to SplitButton

### ISSUE THREAD

**Issue by ChrisBlankDe** [anzwdev/al-code-outline#442]
The AddPageFieldCaptions CleanUp Action adds Captions to Split Buttons.
these captions are unnecessary as they do not appear on the ui.

```AL
group(Group_Process1)
{
    ShowAs = SplitButton;
    Caption = 'Group_Process1'; //automaticly added
    actionref(Post_Promoted; Post)
    {
    }
    actionref(CheckDocument_Promoted; CheckDocument)
    {
    }
}

```

**Comment by anzwdev** [comment]
Thank you for reporting the problem. I've checked the Microsoft documentation and it looks like it is still recommended to populate this property:
```
Any tooltip, caption, or image property set on a group, isn't rendered,
if the group is defined as a split button.  It's still a best practice to set 
these properties, because they're used, if the group is rendered as a regular 
group, for example, on mobile clients.
```

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-showas-property
