### ISSUE TITLE
codeCleanupAction AddApplicationAreas adds Application Area to API Pages

### ISSUE THREAD

**Issue by ChrisBlankDe** [anzwdev/al-code-outline#443]
the codeCleanupAction AddApplicationAreas adds sets the ApplicationArea property to api pages. this is redundant because the property is not evaluated by bc.

See also [alguidelines](https://alguidelines.dev/docs/bestpractices/api-page/#field-properties):

> The property ApplicationArea does not play a role in API pages, so it can be skipped.

can we disable the add on api pages?

```AL
page 5487901 "PTE Document Types"
{
    PageType = API;
    // ...
    ApplicationArea = PTE;  //automaticly added

    layout
    {
        // ...
    }
}
```

**Comment by anzwdev** [comment]
Than you for reporting the issue. I've fixed the problem and released in the latest release
