### ISSUE TITLE
[EXTERNAL] Blocker Issue | Object definition not available 

### ISSUE THREAD

**Issue by DivyaniKhandelwal** [anzwdev/al-code-outline#452]
HI there,
 
We are unable to look at the Object definition due to which I am unable to proceed. I have the following extensions installed.
 
![image](https://user-images.githubusercontent.com/127892418/225116904-40bb2a90-fc70-4772-ae9e-9b441063e37e.png)

Issue Replication steps:
1.	Select an Object.
2.	Right click and click on Go to definition. Please see highlighted error below: “Object definition is not available”. The below screenshot is showing the objects in AZ AL Dev Tools extension. If we disable this extension and use AL Object designer; we can see the code (you are already aware we cant see all objects though in this case).
![image](https://user-images.githubusercontent.com/127892418/225117072-97893b62-28d7-45e5-b046-bf97944dc882.png)
3.	Note we can see the symbols by performing a right click on an object and selecting Open Symbol in New Tab. However unable to see AL Code.
![image](https://user-images.githubusercontent.com/127892418/225117154-27c16728-9ba0-409b-bc49-51155fa1cd06.png)

**Comment by anzwdev** [comment]
Thank you for reporting the problem. Fix has been released in the latest version
