### ISSUE TITLE
[Feature Request] New code cleanup action - One Statement Per Line 

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#453]
I try to adopt the 'One Statement Per Line' guideline (https://alguidelines.dev/docs/bestpractices/one-statement-per-line/) but notice that other developers from the team are not adopting this pattern, especially for conditions followed by an exit or error statement.

**Bad code**

`if OppEntry.Find('-') then exit;  `

**Good code**

```
if OppEntry.Find('-') then   
        exit;  
```

Would it be possible for AL AZ Dev Tools to add an extra 'Code Cleanup' action that detects invalid cases (maybe in first phase only lines followed by an exit / error statement) and auto format the code following the best practice (split code on 2 lines)?

**Comment by NKarolak** [comment]
The new rule splits
`end else`
into
```
end
else
```

Is that intended? I don't see these as two statements to be separated, because _after_ the else, there should be the line break?

**Comment by anzwdev** [comment]
That's a bug, it will be fixed in the next release

**Comment by NKarolak** [comment]
Thank you :-)

**Comment by fvet** [comment]
Just to be sure, the same is also wrongfully applied to 'end else **begin**' constructs.

![image](https://github.com/anzwdev/al-code-outline/assets/25268332/9f2da647-eafe-495c-8139-8a95bc73de18)


`The end else pair should always appear on the same line.`

Source : https://alguidelines.dev/docs/bestpractices/end-else-pair/

**Comment by fvet** [comment]
I've discovered another scenario in which an empty line is added

Before

```
codeunit 71096618 "ESCA Send FTP Request Queue"
{
    Access = Public;

    // This codeunit can be scheduled in a job queue to periodically send any scheduled FTP requests

    #region OnRun
    trigger OnRun()
    var
        FTPRequest: Record "ESCA FTP Request";
        FTPRequestMgt: Codeunit "ESCA FTP Request Mgt.";
        ModulePermission: Codeunit "ESCA Module Permission";
    begin
        if not ModulePermission.TestModuleActiveWithError("ESCA Module"::Connect) then
            exit;

        FTPRequest.Reset();
        FTPRequest.SetRange(Status, "ESCA Request Status"::"In Queue");
        if FTPRequest.FindSet(true) then
            repeat
                FTPRequestMgt.SendFTPRequest(FTPRequest);
                Commit(); // Once the FTP request has been sent, consider this part of the transaction as completed, to ensure the request does not get sent twice
            until FTPRequest.Next() = 0;
    end;
    #endregion OnRun
}
```

After (One Statement Per Line) - extra empty line is added after the commit;

```
codeunit 71096618 "ESCA Send FTP Request Queue"
{
    Access = Public;

    // This codeunit can be scheduled in a job queue to periodically send any scheduled FTP requests

    #region OnRun
    trigger OnRun()
    var
        FTPRequest: Record "ESCA FTP Request";
        FTPRequestMgt: Codeunit "ESCA FTP Request Mgt.";
        ModulePermission: Codeunit "ESCA Module Permission";
    begin
        if not ModulePermission.TestModuleActiveWithError("ESCA Module"::Connect) then
            exit;

        FTPRequest.Reset();
        FTPRequest.SetRange(Status, "ESCA Request Status"::"In Queue");
        if FTPRequest.FindSet(true) then
            repeat
                FTPRequestMgt.SendFTPRequest(FTPRequest);
                Commit(); // Once the FTP request has been sent, consider this part of the transaction as completed, to ensure the request does not get sent twice

            until FTPRequest.Next() = 0;
    end;
    #endregion OnRun
}
```

**Comment by anzwdev** [comment]
Thank you for finding these problems. I've released a new version of the extension that should fix all these issues.
