### ISSUE TITLE
Error applying bulk "with" removing: "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by JalmarazMartn** [anzwdev/al-code-outline#457]
Good morning and thank you for your great work!!!

When I use the command "azALDevTools.RemoveProjectWithStatements" I get the message "Object reference not set to an instance of an object". Please try to fix it, because I love this feature!!!!

Ask me if I can give you further information.

**Comment by JalmarazMartn** [comment]
My workmates get the same error.

**Comment by ricardonunesevosoft** [comment]
I have the same issue, and it was working fine few days ago

**Comment by JalmarazMartn** [comment]
We tested it this week and it works fine. Thank you.
