### ISSUE TITLE
Filter option for Symbols Browser/Outline

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#46]
Hi @anzwdev,

Would it be possible to add a filter option to the symbol tree in the AL Object Browser?
![selected_object_symbols](https://user-images.githubusercontent.com/7383241/64118147-52895b00-cd97-11e9-9b4a-bd7cbc5f1719.png)

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

Thank you for posting your idea. I am working on that tree control now, so I'll include filter functionality in my plan.

**Comment by anzwdev** [comment]
I'vre released a new version of the extension with the filter available in the AL Object Browser and on the new Symbols Tree View that you suggested 2 weeks ago. There is just one filter field that filters tree elements by the text displayed on them.
