### ISSUE TITLE
Please, don't Remove Empty Lines before table-fields { ... } block

### ISSUE THREAD

**Issue by JavierFuentes** [anzwdev/al-code-outline#460]
Seems, our empty (separator) line before this keyword and after table properties is always removed...

```js
table 50000 "My Table"
{
    Caption = 'My Table';
    DataClassification = CustomerContent;
    /* this empty line is removed on clean-up, please keep it */
    fields
    {
    ...
    }
}
```

**Comment by anzwdev** [comment]
Do you have any example when it happens? Does it always happen or is it removed when missing data classification property is added?

**Comment by anzwdev** [comment]
I've found that empty line was removed by add missing data classification, it will be fixed in the next release.

**Comment by JavierFuentes** [comment]
Perfect... 
thank you very much @anzwdev.

**Comment by anzwdev** [comment]
Fix has been released in the latest version

**Comment by JavierFuentes** [comment]
Hello again @anzwdev,
I'm afraid the same thing happens in **Queries** after "run automatic code cleanup on the active project".

![image](https://github.com/anzwdev/al-code-outline/assets/5801847/ffca407a-e1c4-40ff-bfd0-c9f70e679d65)

Could you fix it please?
