### ISSUE TITLE
Unable to resolve resource

### ISSUE THREAD

**Issue by TheDenSter** [anzwdev/al-code-outline#464]
I think it's related to the AL Outline extension but I'm not sure, so just close this issue if it is not related to this extension. 

For all of my BC v22 apps, I am getting this message is reported in the problems window. Is there a setting that I don't have to fix this?

[{
	"resource": "/c:/Users/Administrator/Documents/AL/<folder of the app>/app.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'aloutlinesyntax://json/appJsonSyntax.json': Unable to load schema from 'aloutlinesyntax://json/appJsonSyntax.json': cannot open aloutlinesyntax://json/appJsonSyntax.json. Detail: Unable to resolve resource aloutlinesyntax://json/appJsonSyntax.json.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]

**Comment by anzwdev** [comment]
Are you using the latest version of the Microsoft AL Extension? Do you have any custom code analyzers? I am generationg additional part of "app.json" json schema definition that defines list of available code analyzer rules to be able to see information about rules defined in "suppressWarnings" property when you hover your mouse over them. This definition is generated dynamically from all available code analyzers (Microsoft + any custom) by the "aloutlinesyntax" file provider. Maybe this discovery crashes in your environment. Do you see any errors when you run "Open AZ AL Dev Tools log file" command?

**Comment by anzwdev** [comment]
I've just found that it can sometimes happen when vscode workspace contains multiple folders. A fix will be available in the next version.

**Comment by anzwdev** [comment]
Fix has been released in the latest version

**Comment by TheDenSter** [comment]
Thanks! I don't see the issue anymore
