### ISSUE TITLE
[Bug] AL Object Wizard failure - Could not register service worker

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#468]
I'm facing below error when trying to create new AL objects via the wizard. Thought it could be linked to AL Object Ninja as objectidprovider, but changing the objectidprovider to the default value fails too.

_Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.._

![Wizard](https://user-images.githubusercontent.com/25268332/236853752-ffb07535-2836-465d-86f3-b692e2ebe5ba.gif)

```
Version: 1.78.0 (system setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

**Comment by anzwdev** [comment]
Hi

I am trying to replicate the issue, but I am not able to do it. Are other webviews working - i.e. can you click on any *.app file and see list of objects inside? Have you tried to clear VS Code cache? Have you tried to install insiders version of VS Code with all your extensions and test it there?

**Comment by fvet** [comment]
@anzwdev  As I didn't encounter the issue anymore, I'll archive this one
