### ISSUE TITLE
Add "DataClassification" as table property to the "New Table Wizard" and add "ApplicationArea" as page property to the "New Page Wizard"

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#470]
Hi @anzwdev,

It would be nice if the "New Table Wizard" would get a "Data Classification" property at the top and the "New Page Wizard" would get an "Application Area" property at the top of the wizard.

The `DataClassification` property can be defined on the table level and then does not need to be specified at the table field level, if it is the same value. With this you can avoid redundancy (this is also a rule in the BC Linter Cop).

Similarly, starting from runtime 10.0, the `ApplicationArea` property can be defined on the page level and then does not need to be specified at the page control level, if it is the same value. With this you can avoid redundancy (this is actually not a rule in BC Linter Cop (yet?), but we have implemented a simple check for this in an internal code analyzer 😅).

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

ApplicationArea is already available on the page wizard page, I've added DataClassification to the table wizard, it will be available in the next release of the extension.
