### ISSUE TITLE
format for the alOutline.codeActionsOnSaveIgnoreFiles setting

### ISSUE THREAD

**Issue by tscottjendev** [anzwdev/al-code-outline#471]
What is the correct format for the `alOutline.codeActionsOnSaveIgnoreFiles` setting?  I have this
```
    "alOutline.codeActionsOnSaveIgnoreFiles": [
        "*.report.al",
        "C:\\Repos\\Jendev\\JI-InternalSystem-NEW\\Legacy - Reports\\src\\Report\\JIRPTReleaseNotesHTML.Report.al"
    ]
```
but the `codeActionsOnSave` still sorts the procedures.  I have some ForNAV reports and the sort is mixing my procedures with the auto-generated ForNAV procedures so when I redesign the report ForNAV is over-writing the auto generated section and I lose my procedures.  This didn't used to be a problem because ForNAV puts `#pragma` statements in the top of the report and this used to cause the `SortProcedures` option did not work on objects with `#pragma` in it; now it seems to.  This is fine but I need to stop it for my ForNAV reports and I can't find the right settings to do that.

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this problem, I need to investigate it.

**Comment by anzwdev** [comment]
Hi

This setting expects list of relative VS Code glob patterns. 
1. "*.report.al" will only match files in the root of your project. For files from all folders, you need to use "**/*.report.al". 
2. Your second example contains full path, to make it work, it needs to be relative - "src\\Report\\JIRPTReleaseNotesHTML.Report.al"
