### ISSUE TITLE
[CodeCompletion] Do not Ignore Prefix in variable names

### ISSUE THREAD

**Issue by Thyme1** [anzwdev/al-code-outline#472]
Hi,
In this question (https://github.com/anzwdev/al-code-outline/issues/407), You said that if a mandatory prefix is in AppSourceCop.json, then it won't be autocompleted. What do I do if I want the mandatory prefix in AppSourceCop.json and still want to be able to autocomplete the variable name with the prefix?

**Comment by anzwdev** [comment]
Hi

Currently it is not possible to turn it off, I will need to create a setting that can do that.

**Comment by anzwdev** [comment]
I've added a new `alOutline.keepVariableNamesCompletionAffixes` setting, the default value is false, change it to true if you want to keep your affixes.
