### ISSUE TITLE
Bug in AZ AL Dev Tools: Remove 'with'

### ISSUE THREAD

**Issue by TomArink** [anzwdev/al-code-outline#475]
Hi,

I believe there is a bug in the Remove 'with' command in the AZ AL Dev Tools. Maybe this is solved yet, but I didn't find it.
My Originaly code was:

    local procedure UpdateItem()
    var
        Item: Record Item;
    begin
        with Item do begin
            "No." := Code;
            Description := Description;
            "Base Unit of Measure" := "Unit of Measure Code";
            Modify();
        end;
    end;

The function is in a custom Page, running on a custom table.

After using AZ AL Tools: Remove 'with' usage from the active editor, the result is as follows:

    local procedure UpdateItem()
    var
        Item: Record Item;
    begin
        Item."No." := Rec.Code;
        Item.Description := Item.Description;
        Item."Base Unit of Measure" := Rec."Unit of Measure Code";
        Item.Modify();
    end;

This look OK at first, but the second line: Item.Description := Item.Description; should be Item.Description := **Rec.**Description;

Is this a known issue? And if not, can it be resolved?
Thanks in forward.

Best regards,
Tom Arink - Faect BV

**Comment by anzwdev** [comment]
Hi

The result is correct, It is inside "with", so all references to "Description" are using Item variable fields. Third line is converted to Rec."Unit of Measure Code", because Item does not have this field.
