### ISSUE TITLE
[Suggestion] Add multiple fields on Record variable

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#48]
In C/AL I often copied a large set of fields from the Table Designer, did some Excel magic and got my code for lots of fields. In AL, I've not yet found a way to easily select a set of fields and insert them all at once.

Would it be possible to enable the 'Add multiple fields' code action on Record variables (or a WITH Rec statement) and add the fields at once in code (same way the fields are added on list pages, ...)

![image](https://user-images.githubusercontent.com/25268332/64613284-0e6d0a80-d3d6-11e9-9302-0b8be996db1e.png)

**Comment by anzwdev** [comment]
Thank you for your suggestion, that's a good idea. I'll check how complicated it would be to implement this functionality.

**Comment by fvet** [comment]
Above can be achieved quit easily with various VS Code options, including  Intellisense, multi select of field from source table, ...
Also Github CoPilot does a good job in proposing field names in the meanwhile.

So the past years, I didn't really miss the lack of the requested 'add multiple fields' feature.
