### ISSUE TITLE
Code cleanup removes compiler directives partly

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#482]
Removing unused variables messes up compiler directives.

In my page object, I have a long list of protected vars, whereas `ItemReferenceVisible` is currently unused:
```
        OverReceiptAllowed: Boolean;
#if not CLEAN40
#pragma warning disable AA0137
        ItemReferenceVisible: Boolean;
#pragma warning restore AA0137
#endif
        ExtendedPriceEnabled: Boolean;
```

Running the code cleanup, it will not only remove `ItemReferenceVisible`, but also half of the compiler directives, which leaves the object in a not compilable state:

```
        OverReceiptAllowed: Boolean;
#pragma warning restore AA0137
#endif
        ExtendedPriceEnabled: Boolean;
```

I'd suggest that the code cleanup should not even touch code areas enclosed with compiler directives.

**Comment by fvet** [comment]
@anzwdev  Not sure if this is (partially) related, but when removing unused variables (that have a pragma directive) a check is to be added if the variable is part of the '**protected** var' section. In that case, variables should not be removed, as it results in an AppSourceCop error (considered a breaking change)

![image](https://github.com/anzwdev/al-code-outline/assets/25268332/e420e98d-bd74-4b2a-aabb-c04a9d5cf17b)

**Comment by anzwdev** [comment]
Thank you @fvet for the additional comment. Looks like I need to add directives parsing to the logic.

**Comment by anzwdev** [comment]
Thank you for reporting the issue and comments. I've fixed it and included in the latest release.
