### ISSUE TITLE
FYI, BC24 Issues

### ISSUE THREAD

**Issue by JeremyVyska** [anzwdev/al-code-outline#485]
I think the new v24 Preview image breaks a variety of things.

When I open the App to look at the objects, the only objects visible aren't reorganized/have no namespaces.

This affects additional areas, like adding fields from an object to a Page/Report.  

I figure you'd find this quickly, but wanted to help spot the coming incompability.   (I am using the preview vsix for AL 12)

**Comment by anzwdev** [comment]
Thanks for creating the issue. Each new release of BC requires some fixes and recompilation of the extension, but this one might cause more issues as it adds namespaces, so I probably should start looking at it much earlier than ususal.

**Comment by JavierFuentes** [comment]
Same issue here with BC23-preview objects!

I hope you can fix it soon...

**Comment by anzwdev** [comment]
Microsoft has released BC23 version of the AL Language extension, so I've added a few fixes, recompiled and released a new version of the extension ready to work with that version of the compiler.
