### ISSUE TITLE
Command to collapse empty brackets into a single line

### ISSUE THREAD

**Issue by anzwdev** [anzwdev/al-code-outline#493]
Request from Twitter

**Comment by rvanbekkum** [comment]
It did do its job though nonetheless. I think it's just in the final notification that it would like to show.

**Comment by anzwdev** [comment]
Yes, it is the part that collects results when run for multiple files. It will be fixed in the next release.

**Comment by anzwdev** [comment]
A new release is available, the issue should be fixed now.
