### ISSUE TITLE
[Feature] Trim Spaces In Enum Captions/Values

### ISSUE THREAD

**Issue by mjmatthiesen** [anzwdev/al-code-outline#495]
I use the file wiz extensively. When creating enums, I am often copy pasting from the orig design doc, in that, the captions/values with have leading spaces. The wiz then copies these. It would be great if a trim could be performed. It's just a nice little extra.

Thanks

![image](https://github.com/anzwdev/al-code-outline/assets/16603906/27749736-6f72-40d8-be8c-1be0818794cd)

**Comment by rvanbekkum** [comment]
Indeed 99 out of 100 times I don't want leading nor trailing spaces (neither in the name nor the caption), so trimming all members would be great.

**Comment by anzwdev** [comment]
Thank you for the suggestion. I've implemented it and included in the last release.
