### ISSUE TITLE
Project Symbols- and Document Symbols Tree do not show field nos.

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#50]
Hi @anzwdev,
First off, **amazing** work on the Document Symbols Tree feature, very useful! 👍 
I noticed that the symbol tree in the Project Symbols window (for objects from the current app) and Document Symbols window (for objects from the current app but also from dependencies) does not show the field nos.
Is there something you can do about this?

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

I'm glad you like the new symbols tree. I'll take a look at the missing field numbers and try to solve this issue.

**Comment by anzwdev** [comment]
Hi Rob

I've fixed the issue in the language server and released a new version of the extension. Thank you for letting me know about this problem.
