### ISSUE TITLE
[Bug] Empty section is removed 

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#504]
I'm running a code cleanup with following actions

```
"alOutline.codeCleanupActions": [
        "AddMissingParentheses",
        "AddObjectCaptions",
        "AddTableFieldCaptions",
        "AddToolTips",
        "AddPageFieldCaptions",
        "ConvertObjectIdsToNames",
        "FixIdentifiersCase",
        "FixKeywordsCase",
        "FormatDocument",
        "LockRemovedFieldCaptions",
        "RemoveBeginEnd",
        "RemoveUnusedVariables",
        "RemoveWithStatements",
        "SortPermissions",
        "SortPermissionSetList",
        "SortProperties",
        "SortVariables",
        "TrimTrailingWhitespace",
        "RemoveEmptyLines",
        "RemoveEmptySections",
        "RemoveEmptyTriggers",
        "RemoveRedundantAppAreas",
        "RemoveStrSubstNoFromError",
        "CollapseEmptyBrackets",
        "OneStatementPerLine", 
        "MakeFlowFieldsReadOnly", 
        "RemoveRedundantDataClassification",
        "AddEnumValuesCaptions"        
    ],
```

(or just use 'Remove Empty Sections' commandlet)

There seems to be an empty actions group (actions have been moved to other groups) that cannot be removed due to AppSourceCop...

![image](https://github.com/anzwdev/al-code-outline/assets/25268332/e47897f7-ccb2-4b80-87d9-64c21a119642)

Adding Obsolete properties does not solve the issue.

![image](https://github.com/anzwdev/al-code-outline/assets/25268332/c3e20d60-790f-4e51-91e5-0e090ba500e2)

Only way to avoid deletion of the group is adding some comments properties inside.

![image](https://github.com/anzwdev/al-code-outline/assets/25268332/3f9f8941-1179-4b4b-8a38-b0ebc8ed91f8)

Is adding comments the better way to solve, or should the rule be finetuned?

PS: Adding normal comments (not properties) removes the section as well...

![image](https://github.com/anzwdev/al-code-outline/assets/25268332/4fe852a1-41dc-4799-bdac-0c39f19818d0)

**Comment by anzwdev** [comment]
Thak you for reporting the issue. I've released a fix in the latest version of the extension (3.0.54).
