### ISSUE TITLE
Code Analyzers: most AppSourceCop rules appear twice

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#514]
Hi Andrzej,

when you `Show Code Analyzers Rules`, then most AppSourceCop rules appear twice:
![image](https://github.com/anzwdev/al-code-outline/assets/34504100/483902b7-c7e7-4554-bbbd-1c628d166519)

**Comment by anzwdev** [comment]
Thank you for reporting the problem. I've fixed it and released a new version.

**Comment by NKarolak** [comment]
Thanks a lot, confirmed :-)
