### ISSUE TITLE
Empty path name is not legal error for Fix Identifiers and Keywords Case in the Active Project command

### ISSUE THREAD

**Issue by RadoArvay** [anzwdev/al-code-outline#515]
I am getting _Empty path name is not legal. (Parameter 'path')_ error when I run _Fix Identifiers and Keywords Case in the Active Project_ command.
The project is multiroot workspace. I do not know any other details.
Does not work with a current version v3.0.54.
It works with a previous version v3.0.53.

**Comment by tillrouvier** [comment]
I am getting the same error with version v3.0.54 when I run the "Remove 'with' usage from the Active Project" function.
Seems to be working for me on version v3.0.53.
