### ISSUE TITLE
Add permissions functionality seems to be broken.

### ISSUE THREAD

**Issue by guidorobben** [anzwdev/al-code-outline#516]
When running the Add permissions to all tables it doesnt give me any results anymore.

![image](https://github.com/anzwdev/al-code-outline/assets/11609736/8b9d98b0-7a36-4698-bfc0-a4541d39533f)

**Comment by anzwdev** [comment]
Thank you for reporting the problem. I've fixed it and released a new version.

**Comment by guidorobben** [comment]
I works again!
