### ISSUE TITLE
Apply Default API settings when creating an api query

### ISSUE THREAD

**Issue by jorispoppe** [anzwdev/al-code-outline#521]
I have set default API settings in my json file.
```
 "alOutline.defaultApiGroup": "MyGroup",
 "alOutline.defaultApiPublisher": "MyPublisher",
 "alOutline.defaultApiVersion": "v2.0",
```

When i create a page of type API with the wizard, the defaults are set as expected.
But they are not set when I create a query of type API with the wizard.

Can the defaults also be applied when creating queries of type API??

PS:
I'm not an expert on Typescript but i think you can just add the following code in the alQueryWizard.ts:
```
wizardData.apiPublisher = StringHelper.defaultIfEmpty(config.get<string>('defaultApiPublisher'), wizardData.apiPublisher);
wizardData.apiGroup = StringHelper.defaultIfEmpty(config.get<string>('defaultApiGroup'), wizardData.apiGroup);
wizardData.apiVersion = StringHelper.defaultIfEmpty(config.get<string>('defaultApiVersion'), wizardData.apiVersion);
```
after the line:
```
wizardData.objectName = '';
```
similar to the alPageWizard.ts code.

**Comment by anzwdev** [comment]
Thank you for reporting this missing functionality. It has been implemented in the latest release.

**Comment by jorispoppe** [comment]
Works as expected.
