### ISSUE TITLE
AL Page Wizard [API] issue w/ dependency runtime 12.0

### ISSUE THREAD

**Issue by tonyabriccomeske** [anzwdev/al-code-outline#523]
New Page Wizard, Page Type API
When you are selecting the fields, we are not able to see fields from a dependency where the runtime is 12.0
We are able to see fields from a dependency if the dependency's runtime is below 12.0

Feel free to reach out to me to review the issue / schedule a call if you would like me to show you.

**Comment by tonyabriccomeske** [comment]
Just to give a little more context...
Say you have app Product1, runtime 12.0. We have another app Product2 that is runtime 11.0. Both have table extensions to the Item Ledger Entry. 
We have app Consumer, runtime 12.0 that has dependencies on Product1 and Product2.
When we use the wizard in the Consumer app to create an API page, we do not see any fields from Product1. We do see fields from Product2.

I was trying to think where else a list of available fields was used by the wizard, and I came up with a report.
So if I create a new report with the Item Ledger Entry as the dataitem, I do see fields from both Product1 and Product2. 

So it's definitely a bug with the API page wizard.

**Comment by anzwdev** [comment]
I've released a new version of the extension with a lot of internal changes yesterday. Could you check if you still have these problems?

**Comment by tonyabriccomeske** [comment]
Your new release fixed the issue, thank you for addressing it so quickly!!
