### ISSUE TITLE
sortProperties doesnt work anymore in AL Language Extension v13.0.921843

### ISSUE THREAD

**Issue by guidorobben** [anzwdev/al-code-outline#526]
when running Sort Properties whit version v13.0.921843 I get the error below.
_One or more of actions failed: Sort Properties: error - Workspace command sortProperties error during processing file_

When I revert back to an older version of  AL Language Extension it works again.

**Comment by rvanbekkum** [comment]
This is a known issue with the extension. It uses a DLL to do some of the code actions, but that DLL requires to be recompiled with every major update of alc. So, the extension is only compatible with the alc version of the latest VS marketplace release version of the AL Language extension.

Maybe @anzwdev can put it in the _Known Issues_ section of the README _and_ in a GitHub issue template for this repo? :)

**Comment by guidorobben** [comment]
I'm now on v13.0.903630 and that version works fine. I have been on v13 for a while now and didn't have this problem before.

**Comment by rvanbekkum** [comment]
I think a lot of things can still work but sometimes there is some changes in alc that breaks stuff. I don't know the ins-and-outs of when it happens (maybe Andrzej knows more exactly what type of changes in alc break stuff for his extension), but it's just from my experience. 😅
The BCLinterCop also suffered from this, but is now building against both the stable and prereleases of alc.

**Comment by anzwdev** [comment]
It breaks when compiler APIs change. I was thinking about a solution and my current plan is to have prerelease version of the extension built against prerelease version of alc.

**Comment by anzwdev** [comment]
I've added 2 github devops workflows that build and publish pre-release version of the extension compiled for pre-release version of "Microsof AL Extension". You can now use it in your VS Code.
