### ISSUE TITLE
API Pages - Mandatory fields

### ISSUE THREAD

**Issue by jwikman** [anzwdev/al-code-outline#528]
According to the AL Guidelines at https://alguidelines.dev/docs/bestpractices/api-page/#mandatory-fields, there are two mandatory fields for API pages. These two fields should also have special names.

- SystemId
  - This field should be exposed with the name `id`
- SystemModifiedAt
  - This field should be exposed with the name `lastModifiedDateTime`. If you choose a different name, then the webhook functionality will not work properly.

I don't know if it is a good idea to always include these when using the "New AL File Wizard", but at least I would appreciate if the fields got the correct names. Enabled by a setting is perfectly fine. 🙂

**Comment by jorispoppe** [comment]
I use the conversion settings to get the correct names.

```
"alOutline.apiFieldNamesConversion": [
        {
            "searchRegExp": "^no$",
            "newValue": "number"
        },
        {
            "searchRegExp": "No$",
            "newValue": "Number"
        },
        {
            "searchRegExp": "^systemId$",
            "newValue": "id"
        },
        {
            "searchRegExp": "^systemModifiedAt$",
            "newValue": "lastModifiedDateTime"
        }
    ],
```

**Comment by jwikman** [comment]
> I use the conversion settings to get the correct names.
> 


Aaah, of course. I'll add those to our settings!

I think we'll close this then. 🤓
