### ISSUE TITLE
Alternative symbols path

### ISSUE THREAD

**Issue by YannRobertCargo** [anzwdev/al-code-outline#53]
Hello,
In the AL language extension settings, I changed the Package Cache Path.
![image](https://user-images.githubusercontent.com/47186314/65046245-87350f00-d960-11e9-935f-659fb7391916.png)

It seems that some of your extension's functionnalities do not work if the .alpackages directory is not in the currently opened directory in VS Code.

Did I miss something or is your extension not compatible with this ? Would it be possible to make it look for the symbols in the package cache path ?

**Comment by anzwdev** [comment]
Hello

I remember thinking about getting path from the settings, but there were plenty other, more important things to solve during development and I just forgot about it, but it is a good idea to implement it.

**Comment by anzwdev** [comment]
Hi

I've fixed the issue and released a new version of the extension. Thank you for reporting it.

**Comment by YannRobertCargo** [comment]
Hey, thanks a lot !
