### ISSUE TITLE
[TEST] is not converted to [Test] when running "fix Case"

### ISSUE THREAD

**Issue by guidorobben** [anzwdev/al-code-outline#536]
I would expect [TEST] to be converted to [Test] when running the Fix Case.

![image](https://github.com/anzwdev/al-code-outline/assets/11609736/97f1779a-0fe8-4322-9e60-45ccde3ed5c1)

**Comment by anzwdev** [comment]
Thank you for reporting this issue. It has been fixed in the latest release.
