### ISSUE TITLE
"Run Code Cleanup on Uncommited Files" requires one click per file

### ISSUE THREAD

**Issue by NKarolak** [anzwdev/al-code-outline#537]
When running command `Run Code Cleanup on Uncommited Files in the Active Project` with multiple files not yet committed, a progress bar will appear and stop at the first file:
![image](https://github.com/anzwdev/al-code-outline/assets/34504100/b8779f84-8b93-4cdd-8286-9b4b848152f1)

The command won't finish until you have clicked on every changed file in the SOURCE CONTROL part.

**Comment by anzwdev** [comment]
Thank you for reporting your issue. I've redesigned git handling part, I hope that it solves your problem.

**Comment by NKarolak** [comment]
My first test was successful; thank you :-)
