### ISSUE TITLE
RemoveProceduresSemicolon - does not remove semicolon from triggers

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [anzwdev/al-code-outline#541]
The new procedure RemoveProceduresSemicolon removes the redundant semicolon at the end of a function but not at the end of a trigger, such as trigger OnRename(); or trigger OnModify;
The search criterion and the fix should be extended to trigger so that the LinterCOP used no longer issues the warning LC00024.

**Comment by NKarolak** [comment]
I just wanted to report the same. It ignores also to triggers in codeunits, think of OnInstallAppPerCompany in an install codeunit.

**Comment by anzwdev** [comment]
Thank you for reporting your issue. The fix is available in the last release.
