### ISSUE TITLE
Major slowdown in "Run Code Cleanup on Uncommitted Files in the Active Project"

### ISSUE THREAD

**Issue by cegekaJG** [anzwdev/al-code-outline#543]
I am experiencing loading times from the action "Run Code Cleanup on Uncommitted Files in the Active Project" that are so bad, I've yet to see the command completed once. Even with just 4 files and 30 minutes of waiting, the job isn't even halfway done, whereas a cleanup of the entire project takes just a minute.
I'm not seeing any increased use in memory or CPU, so it shouldn't be a leak, but something in this command specifically causes severe slowdowns.

Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.20348
AL Language Extension Version: v12.6.936426
AZ AL Dev Tools/AL Code Outline Version: v3.0.56

**Comment by anzwdev** [comment]
Thank you for reporting your issue. I am aware about the performance problem. I've been focusing on it during the last 2 weeks. This is the last task that I want to finish before the next release.

**Comment by anzwdev** [comment]
I've released a new version with redesigned git functionality. I hope that it solves your issue.
