### ISSUE TITLE
Object Definition not available

### ISSUE THREAD

**Issue by mjelle9** [anzwdev/al-code-outline#545]
Hi Andrzej,

In the latest version 3.0.57 it appears the symbols can't be opened using "_Show All Project Symbols_". I get the error "Object definition not available". If I revert to version 3.0.56 I do not have any issues opening symbols.

Tested this using "_Microsoft_Base Application_23.4.15643.15983.app_". 

![image](https://github.com/anzwdev/al-code-outline/assets/106706841/1477411d-b26c-4543-bedc-9865c7448337)

**Comment by DomKaz** [comment]
Hi AZ,

Bit more detail on this. Double clicking the object leads to this issue. Or right clicking on an object and selecting "Go to definition (project file or server definition)" leads to the same error. But clicking "Open definition from app file" works fine. So thats a current workaround.

**Comment by anzwdev** [comment]
Thank you for finding this problem. I've just released a new version that should fix it.
