### ISSUE TITLE
[BUG] AL Page Wizard for Cust. Ledger Entry

### ISSUE THREAD

**Issue by tonyabriccomeske** [anzwdev/al-code-outline#548]
Attempting to use the AL Page Wizard to create an API page for the Cust. Ledger Entry table.
When you get to the page to select page fields, it is empty. 

working on v3.0.57

![image](https://github.com/anzwdev/al-code-outline/assets/26098636/3b9a7221-fe6e-4194-9559-56d72f60d165)

![image](https://github.com/anzwdev/al-code-outline/assets/26098636/d738e352-58b8-408a-97d6-1d05357360a5)

(Also tried making a Card page for the Cust. Ledger Entry, and it didn't load fields either)

Edited to add: This does work on v3.0.55, but NOT 56 OR 57

**Comment by anzwdev** [comment]
Thank your for reporting this bug. I've fixed it in the last release.

**Comment by ClairePRA** [comment]
> Thank your for reporting this bug. I've fixed it in the last release.

Hello, I downloaded the new update (12.0.59) but this bug isn't fix yet. Thank you.
