### ISSUE TITLE
One or more of actions failed: Add Parentheses: error - Method not found

### ISSUE THREAD

**Issue by horstoeko** [anzwdev/al-code-outline#549]
Hi,

A few days ago I received the following error message when running *Run Code Cleanup on the Active Editor*: `One or more of actions failed: Add Parentheses: error - Method not found`. For details see the attached file [AZALErrorMessage.txt](https://github.com/anzwdev/al-code-outline/files/14524079/AZALErrorMessage.txt)

AZ AL Dev Tools Version: **2024-03-05**
AL Language Extension Version: **2024-03-04 (Pre-Release)**

Can you help?

Kind Regards

**Comment by anzwdev** [comment]
Thank you for reporting your problem. The extension is compiled for the release version of Microsoft AL Extension and throws error when you try to use it with pre-release. I've added 2 github devops workflows that build and publish pre-release version of the extension compiled for pre-release version of Mcirosoft AL compiler. You should be able to install it in your VS Code now.

**Comment by horstoeko** [comment]
Hi  @anzwdev,

Many thanks for the quick support. I will try this out today and give you feedback.

Kind regards

**Comment by horstoeko** [comment]
Hi,

I have now switched back to the pre-release version of the ALLanguage extension. After that I installed the pre-release version of "AZ AL Dev Tools/AL Code Outline" and was able to execute the action "Run Code Cleanup on the Active Editor" without any errors. I think this has fixed the problem.

Many thanks and best regards...
