### ISSUE TITLE
[BUG] AL Report for Cust. Ledger Entry

### ISSUE THREAD

**Issue by ClairePRA** [anzwdev/al-code-outline#553]
Attempting to use the add multiple fields in an AL Report to add fields from the Cust. Ledger Entry table.
The selection is empty. I'm currently on v12.0.59

But I saw it's working on the v3.0.55 

![image](https://github.com/anzwdev/al-code-outline/assets/162977176/4c8c3f33-47b3-47f8-81b2-e8db6b99ecb6)

![image](https://github.com/anzwdev/al-code-outline/assets/162977176/40384698-3e3a-4e94-89e4-17d261562ba1)

this issue is similar to [
https://github.com/anzwdev/al-code-outline/issues/548](url)

**Comment by anzwdev** [comment]
Thank you for reporting your issue. The problem was caused by changes that I've made some time ago to support namespaces. The fix is available in the last release.
