### ISSUE TITLE
[BUG] Cleanup 'uncommitted' files updates a *.http file

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#554]
For the REST Client extensions, we store some *.http files in our repo to test Rest API calls.

However, when running the 'Cleanup on uncommitted files' action, the **http** files are (wrongfully?) considered to be formatted, resulting in corrupted files.

![image](https://github.com/anzwdev/al-code-outline/assets/25268332/b382c7db-da0f-4afa-af0d-7eb545abcd74)

Shouldn't the 'Cleanup' command(s) only works on '**al**' files?

**Comment by anzwdev** [comment]
Thank you for reporting the problem. I've released new version of the extension that should fix it.
