### ISSUE TITLE
Search Fields with Quotation Marks caused by spaces

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#56]
If i open the symbol view of a table and search for a field with a name enclosed by quotation marks, I'm unable to find the field, if I forget the quotation marks.

E.g.: Table Customer:

I would expect to get the following results with the search term `Name*`:

- Name
- "Name 2"

The results is only: 'Name'

**Comment by anzwdev** [comment]
I've modified filters logic to ignore double quotes characters and uploaded new version of the extension to the Visual Studio Marketplace. Thank you for reporting this issue.

**Comment by pri-kise** [comment]
Works fine. Thanks.
