### ISSUE TITLE
Create interface doesn't add procedures

### ISSUE THREAD

**Issue by aacnsilva** [anzwdev/al-code-outline#565]
I have a codeunit that has 174 public procedures and the create interface doesn't generate the interface declaration.
Is there a limit on how many procedures a codeunit can have for the command to generate the interface?
It creates an empty interface.

**Comment by anzwdev** [comment]
There is no limit. Can you see any error in the log file when you run  "Open AZ AL Dev Tools log file" command?

**Comment by aacnsilva** [comment]
There is no log.
I moved the codeunit to an app that has no objects and it worked there. Must be something related to the size of my app I guess.

Thanks anyway :)
