### ISSUE TITLE
AL File Wizard for Tables Enum Handling

### ISSUE THREAD

**Issue by mjmatthiesen** [anzwdev/al-code-outline#566]
Love the file wizards. Would be awesome if the table file wizard could select enum types, or at least allow me to enter them. I tried typing enum "sales document" and it removed sales document automagically.
Maybe we can steal the length field to enter an enum type? Not super vital, just a nice to have low prio qol kind of thing.

**Comment by rvanbekkum** [comment]
Actually, that should work. Can't check right now, but it is supposed to get the available enums based on the symbols of the active project. 😊

**Comment by mjmatthiesen** [comment]
You know, it kind of does, in a very hacky way. There's no symbol retrieval, but maybe something is borked with v13, not sure. Not using namespaces. I can type enum "Sales Document Type" but when I tab, it vanishes. I have to enter it, then click away from table entry (to avoid validation I guess?) and then I can go back and add more fields, as long as I do not touch said field again, then it works.

Maybe this worked before, honestly I don't make tables very much.


https://github.com/anzwdev/al-code-outline/assets/16603906/39b81bdb-fb80-470e-8813-237351c4511f

**Comment by anzwdev** [comment]
Thank you for reporting the issue, it has been fixed in the last release.
