### ISSUE TITLE
AZ AL Dev Tools - runtime .app file not showing extended objects

### ISSUE THREAD

**Issue by Tsmprintvis** [anzwdev/al-code-outline#569]
Hi, i wanted to ask on the viewing of the .app file that is possible when installing this extension,
not sure if it is called a object browser.

when working with .app packages that is a runtime, we have encountered a problem with viewing extended objects, 
non extended objects works fine with going to the code when clicking on the object
![image](https://github.com/anzwdev/al-code-outline/assets/36735751/a639356d-b961-4703-936c-10ae230f7d74)

when we try to open a extended object
![image](https://github.com/anzwdev/al-code-outline/assets/36735751/7e43ea94-d8d0-4c08-aeb3-e70f0beb10ae)
the opening fails and gives error
![image](https://github.com/anzwdev/al-code-outline/assets/36735751/318d59d8-411e-4acf-aae4-ed597e5be821)
it seems to be the same for Pageextension, Enumextension, Pagecustomizations - i have not checked this on all extended objects 

i could reproduce this in a fresh PTE if needed

**Comment by anzwdev** [comment]
Hi. Runtime packages don't contain AL source code inside. The code that you see when you try to open an object is downloaded from the BC server by VS Code and works only, if extension publisher allows to see it and does not work with table/page/report extensions.
