### ISSUE TITLE
Page wizard does not take fields defined in table extensions into account

### ISSUE THREAD

**Issue by PeterConijn** [anzwdev/al-code-outline#572]
When creating an API page through the wizard, the field selection only shows the base fields and not any fields from table extensions if those extensions are not defined in that same app. The dependencies are defined correctly in the app.json and the corresponding symbols are present in the .alpackages folder.

Repro:

1. Create app "A" that extends a base app table (e.g. vendor)
2. Create a second app "B" that has a dependency on app A
3. Open the page wizard in app B and create a page for Vendor
4. Note that the field selection in app B shows the base app fields, but not the fields you extended in app A

**Comment by anzwdev** [comment]
Thank you for reporting the issue. I've fixed it and included in the last release.
