### ISSUE TITLE
Command Remove Unused Variables from Active Editor incorrectly removes adjacent preprocessor directive 

### ISSUE THREAD

**Issue by ernestasjuska** [anzwdev/al-code-outline#574]
Hi,

Command Remove Unused Variables from Active Editor incorrectly removes adjacent preprocessor directive.

Before:
```al
codeunit 50037 "GEL Demo"
{
#pragma warning disable LC0010
    trigger OnRun()
#pragma warning restore LC0010
    var
        UnitedVATInvoice: Integer;
    begin
        // some code
    end;
}
```

After:
```al
codeunit 50037 "GEL Demo"
{
#pragma warning disable LC0010
    trigger OnRun()
    begin
        // some code
    end;
}
```

It should not touch pragma directive and only remove the variable.
```al
codeunit 50037 "GEL Demo"
{
#pragma warning disable LC0010
    trigger OnRun()
#pragma warning restore LC0010
    begin
        // some code
    end;
}
```

Thanks.

P.S. It would be nice to have some mechanism to detect when the code-altering command does something other than its direct purpose - e.g. show warning, message or list with places to double check. E.g. in this case it was supposed to only remove variables, but it also removed preprocessor directives that are not part of particular variable declaration.

**Comment by anzwdev** [comment]
Thank you for reporting the issue, it has been fixed in the last release.
