### ISSUE TITLE
Page wizard creates area(content) instead of area(Content)

### ISSUE THREAD

**Issue by guidorobben** [anzwdev/al-code-outline#582]
I created a new page via the wizard, and the code below is cxreated.

![image](https://github.com/anzwdev/al-code-outline/assets/11609736/67077de9-e498-4f32-8176-a56dbf7a94df)

Als you can see, the area(content) is created. This should be 'Content'. When I runt the fix casing action, it is transformed to 'Content'.

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've included the fix in one of the last releases.
