### ISSUE TITLE
"Add Multiple Fields" adding extra stuff to the tooltip

### ISSUE THREAD

**Issue by mjmatthiesen** [anzwdev/al-code-outline#583]
This seems to have happened with the most recent update.
Define a field on the table:
![image](https://github.com/anzwdev/al-code-outline/assets/16603906/4d5dde2b-68ea-4c31-8527-7b5c94ef7013)
with the use description for tooltip option enabled, it turns into
![image](https://github.com/anzwdev/al-code-outline/assets/16603906/2111645e-5bf7-4be8-8d27-c29a0ae6af44)
using the table level tooltip field it adds a default comment and adds a comment explainer param/option
![image](https://github.com/anzwdev/al-code-outline/assets/16603906/827be1d0-1484-488a-be7e-8f6b4c1750c0)
I would expect if the tooltip is on the table, it wouldn't do anything. This customer is an older bc version so they cannot use that, but thought I would test both.

Thanks for all your work!

**Comment by anzwdev** [comment]
Thank you for reporting this issue. I've included the fix in one of the last releases.

**Comment by pri-kise** [comment]
I'm still having this problem with `v13.67.0`.
