### ISSUE TITLE
[Feature Request] Code Cleanup: Sort Usings

### ISSUE THREAD

**Issue by ChrisBlankDe** [anzwdev/al-code-outline#586]
Would be nice to have an Clanup Action to Sort usings.
Sorting can be alphabetically or logical (System.*, Microsoft.*, 3rd-Party)

Bad Code:
```AL
using System.Utilities;
using Microsoft.Utilities;
using AwesomeCorp.Feature;
using System.Text;
using System.Telemetry;
```
Good Code (alphabetically):
```AL
using AwesomeCorp.Feature;
using Microsoft.Utilities;
using System.Telemetry;
using System.Text;
using System.Utilities;
```
Good Code (logical):
```AL
using System.Telemetry;
using System.Text;
using System.Utilities;
using Microsoft.Utilities;
using AwesomeCorp.Feature;
```

**Comment by anzwdev** [comment]
Thank you for reporting your issue. There was a bug preventing this functionality from working. You can use "Sort Ysings in the Active Editor" and "Sort Usings in the Active Project" commands. You can also add "SortUsings" to the "alOutline.codeActionsOnSave" setting. If sorting usings is not enabled for document save event, then you will also be able to see code action when you move the cursor to the usings declarations.

**Comment by ChrisBlankDe** [comment]
works like charm. THX
