### ISSUE TITLE
Incorrect filename after entering custom name while generating new object from AL Object Browser

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#59]
Hi @anzwdev,
I ran into the issue that the commands for creating new objects result in incorrect filenames when a custom name is provided different from the extension object name pattern.
To reproduce:
1. Use the following settings:
    ![settings](https://user-images.githubusercontent.com/7383241/68469668-e86bb700-021a-11ea-8dc7-d19884b5e80f.png)
2. Open the object browser and create a new page extension, like this:
    ![step1](https://user-images.githubusercontent.com/7383241/68469691-f6213c80-021a-11ea-9135-ac80f5fe8b6d.png)
3. Enter an object ID:
    ![step2](https://user-images.githubusercontent.com/7383241/68469793-2668db00-021b-11ea-81c1-68b7a14940b2.png)

4. Enter a custom object name:
    ![step3](https://user-images.githubusercontent.com/7383241/68469804-2b2d8f00-021b-11ea-9947-e029a6227c78.png)

You will see a mismatch in the filename and object name.
The resulting file name will be:
![result](https://user-images.githubusercontent.com/7383241/68469766-194bec00-021b-11ea-981b-5cc2f416a991.png)
The resulting object name will be:
![result2](https://user-images.githubusercontent.com/7383241/68469784-210b9080-021b-11ea-9018-adb31e1def1c.png)

I expected it to use the entered object name in the file pattern rather than the "ExtensionObjectNamePattern"-objectname.

**Comment by anzwdev** [comment]
Hi @rvanbekkum 

Was it always working like that or has something changed during last few days? I only had time for a few quick tests yesterday evening and I've found that it also works this way if you use "CRS:Rename - All Files" command. I will take a look at it again today evening.

**Comment by rvanbekkum** [comment]
Just checked, seems like it was always generating the wrong filename.
I think you sometimes need a custom extension object name, as sometimes the pattern-name would not fit in the 30 character limit.

**Comment by anzwdev** [comment]
I can see that you are on the list of Nav Tech Days attendees, so let's talk about it in Antwerp. We can also discuss it with Waldo as current code uses his extension to generate file names.

**Comment by rvanbekkum** [comment]
Looked into it. It appears the extension object file name is decided by the ObjectNamesAPI in waldo's CRS AL Language extension, i.e., `ObjectNamesApi.GetObjectExtensionFileName`.
The extensionObjectName is passed to it as an argument, but it will not be used if `CRS.ExtensionObjectNamePattern` is set: in that case it will ignore the parameter and generate the extension object name from this pattern itself and use that to substitute `<ObjectName>` in the pattern `CRS.FileNamePatternExtensions`.
If `CRS.ExtensionObjectNamePattern` is not defined, it will use the extension object name you provided in the file name.

**Comment by anzwdev** [comment]
Yes, that's how it works, names are generated by Waldo's extension. It looks like there are just 2 solutions - you can clear CRS.ExtensionObjectNamePattern setting or we can ask Waldo to change the functionality.

**Comment by rvanbekkum** [comment]
Yes, indeed, I will therefore close this issue. Thanks!
