### ISSUE TITLE
Delete unused variables with obsolete tag

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [anzwdev/al-code-outline#590]
Unused variables are deleted when the CodeCleanUp is performed. This is fine as long as they are not protected vars.
However, if they are protected vars, they must not be deleted automatically. Even if these variables are marked as obsolete. No automatic deletion may be carried out here, as the handling of the obsolete tag must remain under the control of the developer. Only the developer can decide when they may be deleted.

![image](https://github.com/anzwdev/al-code-outline/assets/27859466/3f7ed36b-9f2a-47ae-bb39-f4e8b610c7d0)

**Comment by anzwdev** [comment]
Than you for reporting your issue. I've extended "Remove unused variables" commands and code cleanup functionality and split "remove global variables" option into 2 - "remove global variables" and "remove protected global variables". For code cleanup version of this functionality, you can use "alOutline.defaultRemoveUnusedVariablesSettings" setting to decide what should be removed.
``` json
"alOutline.defaultRemoveUnusedVariablesSettings": {
    "removeGlobalVariables": true,
    "removeProtectedGlobalVariables": false,
    "removeLocalVariables": true,
    "removeLocalMethodParameters": true
}
```

**Comment by ThorstenEngelsGOB** [comment]
[like]  Engels, Thorsten reacted to your message:
________________________________
