### ISSUE TITLE
'Add Permisisons...' removes #region

### ISSUE THREAD

**Issue by guidorobben** [anzwdev/al-code-outline#593]
These are my permissions before.
![image](https://github.com/anzwdev/al-code-outline/assets/11609736/bd469d4b-860e-45b4-b17b-d1accca72c0f)

When running 'Add Permissions', the #region is removed and is not valid anymore.

![image](https://github.com/anzwdev/al-code-outline/assets/11609736/9a0b1ee5-57f8-4371-8190-70ef6c384bfb)

**Comment by anzwdev** [comment]
Do you still have this problem? Maybe there was a problem with an earlier version of the extension but it was fixed by some other changes?

I've checked both "Add all extension objects permission" and "Add permissions to all tables used by this object" code actions and it worked without any issues.

**Comment by guidorobben** [comment]
This is not happening anymore. I think this was because I was running the preview version.
