### ISSUE TITLE
Enable Object Navigation via Symbols Tree

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#60]
I would love to navigate my Objects with a click in the symbols tree.

Imagine the following scenario:

1. I open my table object
2. I want to extend a trigger of a field
3. I search the field in the symbol tree
4. I can click on the field in the symbol tree with `Ctrl`+Left Mouse or maybe rightclick an Go-To Definition....

I don't know if this is possible and how you could know if the object is already open an move the view to the open tab or instead open this object?

**Comment by anzwdev** [comment]
Hi

Thank you for the idea, I will take a look at it.

**Comment by anzwdev** [comment]
It will be possible to go to symbol in the text editor by selecting "Go to definition" from symbols tree context menu or by pressing ENTER key on a tree node. I've commited changes to the DEV branch, but I don't want to release any updates just before or during Nav TechDays. New version will be available next weekend.

**Comment by anzwdev** [comment]
Modification has been released to the visual studio marketplace
