### ISSUE TITLE
Add multiple fields - not working

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#602]
Since today the Code Action "Add multiple fields" isn't working anymore.
No fields are suggested although several fields are defined.

![image](https://github.com/user-attachments/assets/19c127b2-4c74-4571-b00c-cda9b1620746)

Versions:
- andrzejzwierzchowski.al-code-outline: v14.0.956192 (pre-release)
- AL Language Extension: v14.0.1070882 (pre-release)

Related Issue: https://github.com/anzwdev/al-code-outline/issues/603

**Comment by pri-kise** [comment]
Now the Fields are shown again, but I'm unable to select a field.
I'm unable to select a field via a mouse click and via space key.

**Comment by henrikmb** [comment]
I have the same issue. We can see the fields, but cant select any fields.

**Comment by IsabelBuechner** [comment]
I have the same issue. When adding a field the "selected" field shows 1 for a second, then 0.

**Comment by AndreasThorwesten** [comment]
I can comfirm that. Same issue here.

**Comment by pri-kise** [comment]
I updated my VS Code today.

Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z

and now it's working again with version `v13.71.0`.
