### ISSUE TITLE
Multiple "Go to Definition" windows open at the same time from AL Object Browser

### ISSUE THREAD

**Issue by kevindstanley1988** [anzwdev/al-code-outline#61]
**Enhancement**
Currently when you go to definition from any object in the AL Object Browser it will open the code window in a new tab, if you navigate back to the Object Browser and Go To Definition on a different object it will open the new object on top of the original tab. This doesn't allow me to look at multiple objects at the same time.

**Comment by anzwdev** [comment]
I've added a new "alOutline.openDefinitionInNewTab" setting to the extension. When you change it to "true", "Go to definition" will open documents in a new tab each time you run it. I have't released it yet, I will do it after Nav TechDays.

**Comment by anzwdev** [comment]
Modification has been released to the visual studio marketplace
