### ISSUE TITLE
Add Fields not working - RootSymbol return undefined

### ISSUE THREAD

**Issue by stefanoPrimo** [anzwdev/al-code-outline#64]
Hi,
the code actions won't work. I don't know if the problem is the latest vscode but always, in the class, AZActiveDocumentSymbolsLibrary returns me this:
![image](https://user-images.githubusercontent.com/36199751/70605205-53cded80-1bfa-11ea-8401-f735fafddfb2.png)

As you can see the RootSymbol is undefined. I'm updated to the latest commit.

**Comment by anzwdev** [comment]
Have you tried to run it on a different machine or open differen project? Could you also check if "AZ AL Dev Tools: Show Action Images" shows you any images or just empty window?

**Comment by stefanoPrimo** [comment]
Hi,
neither Show Action Images and Show document symbols tree showed to me something. 
Hope this helps. 
It happens also in other pc and projects.

**Comment by anzwdev** [comment]
Are you building it from the source code or are you using extension installed from vs code marketplace?

**Comment by stefanoPrimo** [comment]
i'm building it from source code

**Comment by anzwdev** [comment]
To build it from the source code you have to do these steps:
1. Manually create "bin" folder in the main folder of the al-code-outline extension (it is excluded from the repository)
2. Clone "az-al-dev-tools-server" repository 
3. Build language server from "az-al-dev-tools-server" repository using visual studio. It will compile the project and copy created files to the bin folder of al-code-outline extension using this command: 
copy "$(TargetDir)*.*" "$(SolutionDir)..\..\al-code-outline\bin\"

**Comment by rvanbekkum** [comment]
I tried to build the most recent version from the `master` branch, but I'm getting a few errors on it:
![buildErrors](https://user-images.githubusercontent.com/7383241/73606860-3d676100-45af-11ea-98f8-3ec07611a9c4.png)
Are there maybe some changes from the "az-al-dev-tools-server" repo that have not been pushed yet?
(I've worked around it now by commenting out the code that raised the errors)

**Comment by anzwdev** [comment]
Hi Rob

Have you tried to run "npm install"? I've updated required vscode version to 1.40.0 in the package.json file.

**Comment by rvanbekkum** [comment]
Hi Andrzej,

Yes, that solved it. My apologies for the late reply by the way.
