### ISSUE TITLE
AL Object Browser won't work in MacOS

### ISSUE THREAD

**Issue by elweilando** [anzwdev/al-code-outline#67]
If I downloaded symbols and try to Open in AL Object Browser. 
In Windows after loading objects, I can see and open the objects.
in MacOS, nothing happens.

```
VS Code
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Datum: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
Betriebssystem: Darwin x64 19.2.0
```

**Comment by anzwdev** [comment]
My extension uses separate .net process in the background to handle part of the functionality. To make everything work on Mac I would have to create separate version of that service, but I am not able to do it as I am only using Windows machines. I will check if I can do something with object browser part as there is a bit of code in the extension that should parse app files in javascript if .net service cannot be started, but as I can see, it is not working for you.

**Comment by anzwdev** [comment]
I've updated .net language server to use .net core and run on Mac. New version of the extension is available in the marketplace. I haven't tested in on macOS as I don't have Mac but I created separate dev version of the extension for Linux and it worked there.

**Comment by elweilando** [comment]
It works on macOS. Thank you!
