### ISSUE TITLE
"No fields found" on creating new page

### ISSUE THREAD

**Issue by TheTrueHonker** [anzwdev/al-code-outline#68]
I created a table with the object id 50010 named Test1 with 2 fields (ID, Name).
After that I tried to create a new page via the AL Page Wizard. 
After I filled out "Object Id" and "Object Name" I filled in the field "Source Table Name" with 50010.
Yet the message "No fields found" came up.

I didn't changed anything in the settings.
I tested this with the version 1.0.24.
My OS is Windows 10.

![image](https://user-images.githubusercontent.com/13810478/71824835-bb147b80-309a-11ea-9bb8-2d45d4752cc3.png)
![image](https://user-images.githubusercontent.com/13810478/71824912-e7c89300-309a-11ea-971a-40bc26f7dd42.png)

**Comment by anzwdev** [comment]
Thank you for reporting it.

I can see 2 problems here, smaller one is incorrect "No fields found" message, it should show "No tables found". This is something that I can quickly fix, but checking why it does not display you any tables might need a bit more investigation. 

Wizards don't support selecting objects by Id, but as I can see on your second screenshot, it is also not working when you use the name. Are you sure that you don't have any al errors in your project? Which version of Microsoft AL Extension are you using? Is it the one from the Visual Studio Marketplace or something installed from product dvd/installation zip?

**Comment by TheTrueHonker** [comment]
The Microsoft AL Extension comes from the installation and has the version 0.12.17091.
I can't find any errors nor do I get a message that I have them.

**Comment by anzwdev** [comment]
I will check it again, but I remember that the AL language server from that version of the Microsoft extension was unstable and was crashing when I was using it from my extension to get list of objects available in the current project.

**Comment by TheTrueHonker** [comment]
Tested it with the Al Language Extension v4.0.218468 from the marketplace and it works fine.

**Comment by TheTrueHonker** [comment]
Also when I tested it with the v4.0.218468 when I opend up the Page Wizard the Object ID was also automaticlly filled, which it does not with the Microsoft version.

**Comment by anzwdev** [comment]
I've just made a few tests with that old version of the Microsoft AL extension. My extension does not show any symbols in the wizards, because Microsoft AL extension from Nav 2018 does not expose any API. You can fix it quickly manually as there is only 1 line of code missing in one of javascript files.
You have to open extension.js file from Microsoft AL extension, it should be located in "%homepath%\.vscode\extensions\microsoft.al-0.12.17091\out\src" folder and add 
`
return extension;
`
at the end of activate() method

**Comment by TheTrueHonker** [comment]
It's working now, thanks!
