### ISSUE TITLE
"Show Code Analyzer Rules" - Sorting

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#70]
Hi @anzwdev,
Would it be possible to incorporate the following improvement into the 'Code Analyzer Rule browser'?

Sort the rules in order of **Id**. Right now there does not seem to be a logical sorting:
![incorrect_sorting_rules](https://user-images.githubusercontent.com/7383241/72341658-0d712000-36cb-11ea-802e-d13651327aac.png)

**Comment by anzwdev** [comment]
Thank you for reporting it, I'll add this functionality

**Comment by anzwdev** [comment]
I've finished this modification and uploaded new version of the extension to the Visual Studio Marketplace.
