### ISSUE TITLE
"Show Code Analyzer Rules" - Filtering

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#71]
Hi @anzwdev,
Would it be possible to incorporate the following improvement into the 'Code Analyzer Rule browser'?

Add filtering options for this browser. It would be useful, if we can view all the rules from code analyzer X with severity Y. It might also be useful to search/filter on _Title_/_Description_.

**Comment by anzwdev** [comment]
That's a good idea, I'll add it

**Comment by anzwdev** [comment]
I've added filters to the code analyzer rules viewer and published a new version of the extension. Thank you for reporting this issue.
