### ISSUE TITLE
AL Object Browser - Expand/Collapse All

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#73]
Hi @anzwdev,
It might be nice to have a button _Expand All_ and _Collapse All_ (or toggle-button) in the AL Object Browser (N.B., Tree-View).
These buttons would then be found here:
![expand_collapse](https://user-images.githubusercontent.com/7383241/72342471-c84ded80-36cc-11ea-9be7-9c5341066cdd.png)
What do you think?

**Comment by anzwdev** [comment]
I agree with you, this functionality should be there :)

**Comment by anzwdev** [comment]
I've merged your pull request and uploaded new version of the extension to the Visual Studio Marketplace. Thank you for your help.
