### ISSUE TITLE
Copy from Object Explorer

### ISSUE THREAD

**Issue by GreatScott000** [anzwdev/al-code-outline#77]
Any chance you can enable copy (Ctrl+C) from the object explorer?  Or export to excel(CSV)?  Would be nice to get the information out sometimes (build information to update license file).

**Comment by anzwdev** [comment]
That's a good idea, I'll do it.

**Comment by anzwdev** [comment]
I've added "Copy Selected" menu item to the context menu in the "Object Explorer". Columns are separated by tab in copied data, so you can paste list of objects directly into Excel. Modification is available in the latest version of the extension.

**Comment by GreatScott000** [comment]
Thank you I will test it out.

**Comment by GreatScott000** [comment]
Looks good.  Thanks you.
