### ISSUE TITLE
go to Definition no more working?

### ISSUE THREAD

**Issue by KristofKlein** [anzwdev/al-code-outline#8]
Hi,

I really appreciate your VSC extension! So helpful! But I do have an issue with it. I think it worked but now it does no longer. When I browse an .app file I can see all the Objects. Also the AL Outline is working fine. but when I try to use "go to Definition" it just opens a blank OBJECTNAME.al file (e.g. Customer.al).

I really would like to get this back (if it ever worked - really can't remember ;) ). I tried the System .app files in v11 and v13. no luck. 

If I can support you in finding the solution just let me know :)

**Comment by anzwdev** [comment]
Thank you for reporting this issue, I will take a look at it later today.

**Comment by anzwdev** [comment]
It seems than functionality building source code has been moved from al-preview vs code content provider to go-to-definition implementation in AL VS Code extension. I was trying to find workaround for it, but unfortunately it crashes al language server from the lates Business Central RC 3 sometimes. I am going to spend more time trying to find when it crashes and if it looks like a problem with RC3 I will create an issue on AL github.

**Comment by johbor** [comment]
This functionality is exactly what I'm serching for. Browse through the standard BC objects and with "Go to Definition" open the xxx.dal object.

**Comment by anzwdev** [comment]
I've found a way to make it work again and it is available in the new version of the extension.
