### ISSUE TITLE
New Table Wizard - Finish Button Disappeared

### ISSUE THREAD

**Issue by sbinesh** [anzwdev/al-code-outline#83]
I have used today New Table wizard and found one issues.
Upto the screen size its showing the Finish button as shown Table1.png attached screenshot.
![Table1](https://user-images.githubusercontent.com/36730747/74727841-c2b56b80-5267-11ea-8803-a4bee9668ee5.png)

but after adding more fields, Finish button is disappeared and there is no scroll bar to get it as shown Table2.png screenshot.

Could you please fix it for me.
Similar [issues#38](https://github.com/anzwdev/al-code-outline/issues/38) was fixed, but still I have an issue.

![table2](https://user-images.githubusercontent.com/36730747/74728105-35264b80-5268-11ea-9180-2102d505d4e8.PNG)

**Comment by anzwdev** [comment]
I've released new version of the extension, this issue should be fixed now.
