### ISSUE TITLE
CodeAction rule AA0008

### ISSUE THREAD

**Issue by stefanoPrimo** [anzwdev/al-code-outline#84]
Hi, 
I have a question about your reformat for the implementation of the CodeAction that solves the warnings generated by the rule AA0008.
Originally was of type SourceFixAll, now it is QuickFix. 
It was like that because even in small projects there are like hundreds of this warning and so, with the right command or setting, you could fix all with one command.
let me know.

for reference:
`src\canalyzerfixes\alCodeCopFixAA0008.ts`
BEFORE:
`const fix = new vscode.CodeAction(`Add parentheses`, vscode.CodeActionKind.SourceFixAll);`
AFTER:
`const fix = new vscode.CodeAction(`Add parentheses`, vscode.CodeActionKind.QuickFix);`

**Comment by anzwdev** [comment]
Hi

I've changed it to QuickFix as I was not feeling comfortable with releasing change that starts changing people's code without asking them if they want to do it. I'll add an option to the extension settings to decide if you want to report this code action as SourceFixAll or QuickFix.

**Comment by stefanoPrimo** [comment]
Oh well, thanks!
I was thinking about that it was too much "silent", so I was trying to add another method or a syntax rewriter but, your solution is way much simpler than mine. 
Thanks!

**Comment by stefanoPrimo** [comment]
Looks great! I will test it right now, thanks!
