### ISSUE TITLE
"Show Code Analyzer Rules" - Background Code Analyzer Rules

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#88]
Hi @anzwdev,
Is it possible to also include the background (AL) code analyzer rules in the Code Analyzer Rules Viewer?

**Comment by anzwdev** [comment]
Hi Rob

I've finally implemented your idea. The page displays "Compiler" on the list of available "Code Analyzers" now. If you select it and press "Search", all compiler warnings and errors will be displayed.

![image](https://user-images.githubusercontent.com/24944969/121822947-f35db780-cc99-11eb-8d27-30cb62f8b438.png)

**Comment by rvanbekkum** [comment]
Very nice! 😊😊
Thank you! This will certainly come in handy!
