### ISSUE TITLE
"Show Code Analyzer Rules" - All Rules

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#89]
Hi @anzwdev,
Would it be possible to have an option in the Code Analyzer Rules Viewer to display the rules from all code analyzers together?
That is, right now you can only view and search rules for each code analyzer individually.

**Comment by anzwdev** [comment]
Yes, it can be done. I'll take a look at it.

**Comment by anzwdev** [comment]
I've updated the extension in the Visual Studio Marketplace. It can now display rules from more than 1 analyzer. When you open "Code Analyzer Rules Viewer" it checks settings and shows rules from enabled analyzers.

**Comment by rvanbekkum** [comment]
I have used it during the week and it works great! Thank you!
