### ISSUE TITLE
XML comment on hover

### ISSUE THREAD

**Issue by bjarkihall** [anzwdev/al-code-outline#92]
Hi and thanks for your contributions!
I was just wondering if it's possible to get the xml comments to appear when the symbol it belongs to is being hovered?
I know this is baked into JS/TS + JSDoc (/**) but I'm not sure if xml documentation comments are supported out of the box in vs code (even in C#), would I need an additional extension and would you recommend any or would it have to be specifically implemented for .al files via an extension like al-code-outline?

**Comment by bjarkihall** [comment]
![image](https://user-images.githubusercontent.com/8615374/76408457-e3637380-6384-11ea-822e-9481297093cf.png)
Just an image for demonstration from the first [google result](https://stackoverflow.com/questions/45464604/how-to-enable-intellisense-jsdoc-info-on-hover-in-webstorm).

**Comment by anzwdev** [comment]
Hi

Information displayed by code completion or on hover is received from Microsoft al language server running in the background. It parses whole project and keeps information about all defined and referenced types. It means that the best option to see documentation information on hover would be to add support for documentation comments into al compiler. Original c#/vb roslyn compiler supports it but unfortuantely it seems that the task to move it into al compiler has very low priority.

**Comment by bjarkihall** [comment]
Oh I feared so, I'd read the issue before, for reference it's here:
https://github.com/microsoft/AL/issues/132
I'm closing this issue now since it was more of a question, thanks for the input!

**Comment by rvanbekkum** [comment]
The [AL XML Documentation](https://github.com/365businessdev/vscode-alxmldocumentation) VSCode extension appears to support this _for procedures_ since last week (note: only shows the contents of the `summary` tag).

**Comment by bjarkihall** [comment]
Ah, nice catch, here's their [changelog](https://marketplace.visualstudio.com/items/365businessdevelopment.bdev-al-xml-doc/changelog):
`[0.3.0] - 2020-07-02
Allow underscore in Procedure Name #1.
Hover <summary> information from xml documentation on procedures.`

I've also heard rumors about MS adding support for XML comments in vscode this fall but it might be dropped.
