### ISSUE TITLE
Reorder columns in report object

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#95]
It would be nice to have an option to easily "Sort columns" of a dataitem in a report object in natural order of column-name.

**Comment by anzwdev** [comment]
I'll add it, thank you for the idea.

**Comment by anzwdev** [comment]
I've released new version of the extension. There is a new "Sort data item columns" code acation available when cursor is on data item, column or on the first line of the report object definition. If it is invoked from data item or column, it will sort columns from that single data item only, but if it is invoked from the first report line, it will be invoked for all data items.

**Comment by duichwer** [comment]
Works like a charm. I like it to have the ability to reorder manually, but maybe for future development some sort of auto-reorder trigger OnSave would be perfect. Is it possible to trigger the ordering after the formatting?
