### ISSUE TITLE
"Show all Project Symbols" doesn't list Page Customization and Profiles

### ISSUE THREAD

**Issue by DavidFeldhoff** [anzwdev/al-code-outline#97]
I think the Page Customizations and Profiles aren't listed when I call "Show All Project Symbols" (or I don't know how to handle it :) ). 

It looks like the "ALObjectBrowser" uses the collectSymbols method which uses the isALObject method. But this one does not include the profiles and page customizations.
Maybe that's already the solution, but I couldn't get your extension running on my laptop to test it and to create a PR (maybe because I don't use the insider version of vscode). So it's just a guess in the dark - but I hope it helps.

**Comment by anzwdev** [comment]
Thank you for reporting this issue. Yes, you are correct, the probles was caused by isALObject method. I've updated development branch and will release new version of the extension later today.

**Comment by anzwdev** [comment]
New version of the extension has been released, it should fix your issue.
